-- Example of rotations generator for ROGUES.
local rogueRotationsGenerator = function ()
	local rotation = {
		["rotation/rogue/assassination"] = {
			["ActionList"] = {
				["rotation/rogue/blindside"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_t_hp"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_spellname"] = "111240",
					["v_t_hp"] = "<30%",
				},
				["rotation/rogue/blindside_proc"] = {
					["b_gunitpower"] = true,
					["b_hasproc"] = true,
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_spellname"] = "111240",
				},
				["rotation/rogue/crimson_tempest"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=4",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "121411",
					["v_t_needsdebuff"] = "_121411^3",
				},
				["rotation/rogue/crimson_tempest_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "121411",
					["v_t_needsdebuff"] = "_121411^3",
				},
				["rotation/rogue/crimson_vial"] = {
					["b_gspellcost"] = true,
					["b_p_hp"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_p_hp"] = "<60%",
					["v_spellname"] = "185311",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/deadly_poison"] = {
					["b_p_knownotspell"] = true,
					["b_p_needbuff"] = true,
					["v_p_knownotspell"] = "200802",
					["v_p_needbuff"] = "2823",
					["v_spellname"] = "2823",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/death_from_above"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=4",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "269513",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/death_from_above_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "269513",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/envenom"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=4",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "32645",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/envenom_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "32645",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/exsanguinate"] = {
					["b_gspellcost"] = true,
					["b_t_hasdebuff"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_spellname"] = "200806",
					["v_t_hasdebuff"] = "1943^20",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/garrote"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "45",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_unitpower"] = "<5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "703",
					["v_t_needsdebuff"] = "_703^5.4",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/garrote_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "45",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_unitpower"] = "<6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "703",
					["v_t_needsdebuff"] = "_703^5.4",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/garrote_stealth"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_havebuff"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "45",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_havebuff"] = "_1784",
					["v_p_unitpower"] = "<5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "703",
					["v_t_needsdebuff"] = "_703^5.4",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/hemorrhage"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_spellname"] = "16511",
					["v_t_needsdebuff"] = "_16511^6",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/kick"] = {
					["b_t_interrupt"] = true,
					["v_spellname"] = "1766",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/leeching_poison"] = {
					["b_disabled"] = true,
					["b_p_needbuff"] = true,
					["v_p_needbuff"] = "108211",
					["v_spellname"] = "108211",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/marked_for_death"] = {
					["b_gunitpower"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsbuff"] = true,
					["v_gunitpower"] = "5",
					["v_gunitpowertype"] = "4",
					["v_p_knownotspell"] = "114015||193531",
					["v_p_unitpower"] = "<1",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "137619",
					["v_t_needsbuff"] = "_137619",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/marked_for_death_deeper_stratagem"] = {
					["b_gunitpower"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsbuff"] = true,
					["v_gunitpower"] = "5",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "<2",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "137619",
					["v_t_needsbuff"] = "_137619",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/mutilate"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_knownotspell"] = true,
					["v_gspellcost"] = "55",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "2",
					["v_gunitpowertype"] = "4",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = "<4",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "1329",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/mutilate_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_knowspell"] = true,
					["v_gspellcost"] = "55",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "2",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "<5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "1329",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/rupture"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=4",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "1943",
					["v_t_needsdebuff"] = "_1943^7.2",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/rupture_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "1943",
					["v_t_needsdebuff"] = "_1943^8.4",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/toxic_blade"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["v_gspellcost"] = "20",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_spellname"] = "245388",
				},
				["rotation/rogue/vendetta"] = {
					["v_spellname"] = "79140",
					["v_togglename"] = "Toggle 1",
				},
			},
			["SortedActions"] = {
				"rotation/rogue/kick", -- [1]
				"rotation/rogue/deadly_poison", -- [2]
				"rotation/rogue/leeching_poison", -- [3]
				"rotation/rogue/crimson_vial", -- [4]
				"rotation/rogue/marked_for_death_deeper_stratagem", -- [5]
				"rotation/rogue/marked_for_death", -- [6]
				"rotation/rogue/rupture_deeper_stratagem", -- [7]
				"rotation/rogue/rupture", -- [8]
				"rotation/rogue/crimson_tempest_deeper_stratagem", -- [9]
				"rotation/rogue/crimson_tempest", -- [10]
				"rotation/rogue/death_from_above_deeper_stratagem", -- [11]
				"rotation/rogue/death_from_above", -- [12]
				"rotation/rogue/envenom_deeper_stratagem", -- [13]
				"rotation/rogue/envenom", -- [14]
				"rotation/rogue/garrote_stealth", -- [15]
				"rotation/rogue/vendetta", -- [16]
				"rotation/rogue/exsanguinate", -- [17]
				"rotation/rogue/hemorrhage", -- [18]
				"rotation/rogue/garrote", -- [19]
				"rotation/rogue/garrote_deeper_stratagem", -- [20]
				"rotation/rogue/toxic_blade", -- [21]
				"rotation/rogue/blindside_proc", -- [22]
				"rotation/rogue/blindside", -- [23]
				"rotation/rogue/mutilate_deeper_stratagem", -- [24]
				"rotation/rogue/mutilate", -- [25]
			},
			["specID"] = 1,
			["version"] = 10,
		},
		["rotation/rogue/assassination_multi"] = {
			["ActionList"] = {
				["rotation/rogue/blindside_proc"] = {
					["b_gunitpower"] = true,
					["b_hasproc"] = true,
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_spellname"] = "111240",
				},
				["rotation/rogue/crimson_tempest"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=4",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "121411",
					["v_t_needsdebuff"] = "_121411^3",
				},
				["rotation/rogue/crimson_tempest_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "121411",
					["v_t_needsdebuff"] = "_121411^3",
				},
				["rotation/rogue/crimson_vial"] = {
					["b_gspellcost"] = true,
					["b_p_hp"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_p_hp"] = "<60%",
					["v_spellname"] = "185311",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/deadly_poison"] = {
					["b_p_knownotspell"] = true,
					["b_p_needbuff"] = true,
					["v_p_knownotspell"] = "200802",
					["v_p_needbuff"] = "2823",
					["v_spellname"] = "2823",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/death_from_above"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=4",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "269513",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/death_from_above_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "269513",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/envenom"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=4",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "32645",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/envenom_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "32645",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/exsanguinate"] = {
					["b_gspellcost"] = true,
					["b_t_hasdebuff"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_spellname"] = "200806",
					["v_t_hasdebuff"] = "1943^20",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/fan_of_knives"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_spellname"] = "51723",
				},
				["rotation/rogue/garrote"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "45",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_unitpower"] = "<5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "703",
					["v_t_needsdebuff"] = "_703^5.4",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/garrote_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "45",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_unitpower"] = "<6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "703",
					["v_t_needsdebuff"] = "_703^5.4",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/hemorrhage"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_spellname"] = "16511",
					["v_t_needsdebuff"] = "_16511^6",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/kick"] = {
					["b_t_interrupt"] = true,
					["v_spellname"] = "1766",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/leeching_poison"] = {
					["b_disabled"] = true,
					["b_p_needbuff"] = true,
					["v_p_needbuff"] = "108211",
					["v_spellname"] = "108211",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/marked_for_death"] = {
					["b_gunitpower"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsbuff"] = true,
					["v_gunitpower"] = "5",
					["v_gunitpowertype"] = "4",
					["v_p_knownotspell"] = "114015||193531",
					["v_p_unitpower"] = "<1",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "137619",
					["v_t_needsbuff"] = "_137619",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/marked_for_death_deeper_stratagem"] = {
					["b_gunitpower"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsbuff"] = true,
					["v_gunitpower"] = "5",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "<2",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "137619",
					["v_t_needsbuff"] = "_137619",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/rupture"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=4",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "1943",
					["v_t_needsdebuff"] = "_1943^7.2",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/rupture_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "1943",
					["v_t_needsdebuff"] = "_1943^8.4",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/toxic_blade"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["v_gspellcost"] = "20",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_spellname"] = "245388",
				},
				["rotation/rogue/vendetta"] = {
					["v_spellname"] = "79140",
					["v_togglename"] = "Toggle 1",
				},
			},
			["SortedActions"] = {
				"rotation/rogue/kick", -- [1]
				"rotation/rogue/deadly_poison", -- [2]
				"rotation/rogue/leeching_poison", -- [3]
				"rotation/rogue/crimson_vial", -- [4]
				"rotation/rogue/marked_for_death_deeper_stratagem", -- [5]
				"rotation/rogue/marked_for_death", -- [6]
				"rotation/rogue/rupture_deeper_stratagem", -- [7]
				"rotation/rogue/rupture", -- [8]
				"rotation/rogue/crimson_tempest_deeper_stratagem", -- [9]
				"rotation/rogue/crimson_tempest", -- [10]
				"rotation/rogue/death_from_above_deeper_stratagem", -- [11]
				"rotation/rogue/death_from_above", -- [12]
				"rotation/rogue/envenom_deeper_stratagem", -- [13]
				"rotation/rogue/envenom", -- [14]
				"rotation/rogue/garrote", -- [15]
				"rotation/rogue/garrote_deeper_stratagem", -- [16]
				"rotation/rogue/vendetta", -- [17]
				"rotation/rogue/exsanguinate", -- [18]
				"rotation/rogue/hemorrhage", -- [19]
				"rotation/rogue/blindside_proc", -- [20]
				"rotation/rogue/toxic_blade", -- [21]
				"rotation/rogue/fan_of_knives", -- [22]
			},
			["isMultiTarget"] = true,
			["specID"] = 1,
			["version"] = 10,
		},
		["rotation/rogue/outlaw"] = {
			["ActionList"] = {
				["rotation/rogue/adrenaline_rush"] = {
					["b_checkothercd"] = true,
					["b_isCustomCase1"] = true,
					["v_checkothercdname"] = "202665",
					["v_checkothercdvalue"] = "<=5",
					["v_spellname"] = "13750",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/ambush"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_isstealthed"] = true,
					["v_gspellcost"] = "60",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "2",
					["v_gunitpowertype"] = "4",
					["v_spellname"] = "8676",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/between_the_eyes"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_havebuff"] = "193357",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "199804",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/between_the_eyes_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_havebuff"] = "193357",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "=6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "199804",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/blade_rush"] = {
					["b_gunitpower"] = true,
					["v_gunitpower"] = "25",
					["v_gunitpowertype"] = "3",
					["v_spellname"] = "271877",
				},
				["rotation/rogue/crimson_vial"] = {
					["b_gspellcost"] = true,
					["b_p_hp"] = true,
					["b_p_knownotspell"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_p_hp"] = "<70%",
					["v_p_knownotspell"] = "193546",
					["v_spellname"] = "185311",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/crimson_vial_iron_stomach"] = {
					["b_gspellcost"] = true,
					["b_p_hp"] = true,
					["b_p_knowspell"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_p_hp"] = "<40%",
					["v_p_knowspell"] = "193546",
					["v_spellname"] = "185311",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/death_from_above"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "269513",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/death_from_above_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "=6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "269513",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/ghostly_strike"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_knownotspell"] = "114015||193531",
					["v_p_unitpower"] = "<5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "196937",
					["v_t_needsdebuff"] = "_196937^4.5",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/ghostly_strike_anticipation"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "114015",
					["v_p_unitpower"] = "<8",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "196937",
					["v_t_needsdebuff"] = "_196937^4.5",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/ghostly_strike_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "<6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "196937",
					["v_t_needsdebuff"] = "_196937^4.5",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/kick"] = {
					["b_t_interrupt"] = true,
					["v_spellname"] = "1766",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/killing_spree"] = {
					["v_spellname"] = "51690",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/marked_for_death"] = {
					["b_gunitpower"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gunitpower"] = "5",
					["v_gunitpowertype"] = "4",
					["v_p_knownotspell"] = "114015",
					["v_p_unitpower"] = "<=1",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "137619",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/marked_for_death_anticipation"] = {
					["b_gunitpower"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsbuff"] = true,
					["v_gunitpower"] = "5",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "114015",
					["v_p_unitpower"] = "<5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "137619",
					["v_t_needsbuff"] = "_137619",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/pistol_shot"] = {
					["b_gunitpower"] = true,
					["b_hasproc"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_knownotspell"] = "196938||193531||114015",
					["v_p_unitpower"] = "<5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "185763",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/pistol_shot_anticipation"] = {
					["b_gunitpower"] = true,
					["b_hasproc"] = true,
					["b_p_knownotspell"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_knownotspell"] = "196938",
					["v_p_knowspell"] = "114015",
					["v_p_unitpower"] = "<10",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "185763",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/pistol_shot_deeper_stratagem"] = {
					["b_gunitpower"] = true,
					["b_hasproc"] = true,
					["b_p_knownotspell"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_knownotspell"] = "196938",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "<6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "185763",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/pistol_shot_quick_draw"] = {
					["b_gunitpower"] = true,
					["b_hasproc"] = true,
					["b_p_knownotspell"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gunitpower"] = "2",
					["v_gunitpowertype"] = "4",
					["v_p_knownotspell"] = "193531||114015",
					["v_p_knowspell"] = "196938",
					["v_p_unitpower"] = "<4",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "185763",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/pistol_shot_quick_draw_anticipation"] = {
					["b_gunitpower"] = true,
					["b_hasproc"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gunitpower"] = "2",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "196938||114015",
					["v_p_unitpower"] = "<9",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "185763",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/pistol_shot_quick_draw_deeper_stratagem"] = {
					["b_gunitpower"] = true,
					["b_hasproc"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gunitpower"] = "2",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "196938||193531",
					["v_p_unitpower"] = "<5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "185763",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/roll_the_bones"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_needbuff"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_needbuff"] = "193356^10.8||193357^10.8||193358^10.8||193359^10.8||199600^10.8||199603^10.8||_5171^10.8",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "193316",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/roll_the_bones_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_needbuff"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_needbuff"] = "193356^12.6||193357^12.6||193358^12.6||193359^12.6||199600^12.6||199603^12.6||_5171^12.6",
					["v_p_unitpower"] = "=6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "193316",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/run_through"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "2098",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/run_through_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "=6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "2098",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/saber_slash"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["v_gspellcost"] = "50",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_spellname"] = "193315",
					["v_togglename"] = "Toggle 1",
				},
			},
			["SortedActions"] = {
				"rotation/rogue/kick", -- [1]
				"rotation/rogue/crimson_vial_iron_stomach", -- [2]
				"rotation/rogue/crimson_vial", -- [3]
				"rotation/rogue/ambush", -- [4]
				"rotation/rogue/killing_spree", -- [5]
				"rotation/rogue/adrenaline_rush", -- [6]
				"rotation/rogue/marked_for_death_anticipation", -- [7]
				"rotation/rogue/marked_for_death", -- [8]
				"rotation/rogue/roll_the_bones_deeper_stratagem", -- [9]
				"rotation/rogue/roll_the_bones", -- [10]
				"rotation/rogue/between_the_eyes_deeper_stratagem", -- [11]
				"rotation/rogue/between_the_eyes", -- [12]
				"rotation/rogue/death_from_above_deeper_stratagem", -- [13]
				"rotation/rogue/death_from_above", -- [14]
				"rotation/rogue/run_through_deeper_stratagem", -- [15]
				"rotation/rogue/run_through", -- [16]
				"rotation/rogue/blade_rush", -- [17]
				"rotation/rogue/ghostly_strike_anticipation", -- [18]
				"rotation/rogue/ghostly_strike_deeper_stratagem", -- [19]
				"rotation/rogue/ghostly_strike", -- [20]
				"rotation/rogue/pistol_shot_quick_draw_anticipation", -- [21]
				"rotation/rogue/pistol_shot_quick_draw_deeper_stratagem", -- [22]
				"rotation/rogue/pistol_shot_quick_draw", -- [23]
				"rotation/rogue/pistol_shot_anticipation", -- [24]
				"rotation/rogue/pistol_shot_deeper_stratagem", -- [25]
				"rotation/rogue/pistol_shot", -- [26]
				"rotation/rogue/saber_slash", -- [27]
			},
			["specID"] = 2,
			["version"] = 10,
		},
		["rotation/rogue/outlaw_multi"] = {
			["ActionList"] = {
				["rotation/rogue/adrenaline_rush"] = {
					["b_checkothercd"] = true,
					["b_isCustomCase1"] = true,
					["b_p_unitpower"] = true,
					["v_checkothercdname"] = "202665",
					["v_checkothercdvalue"] = "<=5",
					["v_p_unitpower"] = "<=66%",
					["v_p_unitpowertype"] = "3",
					["v_spellname"] = "13750",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/ambush"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_isstealthed"] = true,
					["v_gspellcost"] = "60",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "2",
					["v_gunitpowertype"] = "4",
					["v_spellname"] = "8676",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/between_the_eyes"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_havebuff"] = "193357",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "199804",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/between_the_eyes_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_havebuff"] = "193357",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "=6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "199804",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/blade_flurry"] = {
					["b_gspellcost"] = true,
					["b_p_needbuff"] = true,
					["v_gspellcost"] = "15",
					["v_gspellcosttype"] = "3",
					["v_p_needbuff"] = "13877^3",
					["v_spellname"] = "13877",
				},
				["rotation/rogue/blade_rush"] = {
					["b_gunitpower"] = true,
					["b_p_havebuff"] = true,
					["v_gunitpower"] = "25",
					["v_gunitpowertype"] = "3",
					["v_p_havebuff"] = "13877",
					["v_spellname"] = "271877",
				},
				["rotation/rogue/crimson_vial"] = {
					["b_gspellcost"] = true,
					["b_p_hp"] = true,
					["b_p_knownotspell"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_p_hp"] = "<70%",
					["v_p_knownotspell"] = "193546",
					["v_spellname"] = "185311",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/crimson_vial_iron_stomach"] = {
					["b_gspellcost"] = true,
					["b_p_hp"] = true,
					["b_p_knowspell"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_p_hp"] = "<40%",
					["v_p_knowspell"] = "193546",
					["v_spellname"] = "185311",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/death_from_above"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "269513",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/death_from_above_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "=6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "269513",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/ghostly_strike"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_knownotspell"] = "114015||193531",
					["v_p_unitpower"] = "<5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "196937",
					["v_t_needsdebuff"] = "_196937^4.5",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/ghostly_strike_anticipation"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "114015",
					["v_p_unitpower"] = "<8",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "196937",
					["v_t_needsdebuff"] = "_196937^4.5",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/ghostly_strike_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "<6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "196937",
					["v_t_needsdebuff"] = "_196937^4.5",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/kick"] = {
					["b_t_interrupt"] = true,
					["v_spellname"] = "1766",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/killing_spree"] = {
					["b_p_havebuff"] = true,
					["v_p_havebuff"] = "13877",
					["v_spellname"] = "51690",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/marked_for_death"] = {
					["b_gunitpower"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gunitpower"] = "5",
					["v_gunitpowertype"] = "4",
					["v_p_knownotspell"] = "114015",
					["v_p_unitpower"] = "<=1",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "137619",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/marked_for_death_anticipation"] = {
					["b_gunitpower"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsbuff"] = true,
					["v_gunitpower"] = "5",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "114015",
					["v_p_unitpower"] = "<5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "137619",
					["v_t_needsbuff"] = "_137619",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/pistol_shot"] = {
					["b_gunitpower"] = true,
					["b_hasproc"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_knownotspell"] = "196938||193531||114015",
					["v_p_unitpower"] = "<5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "185763",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/pistol_shot_anticipation"] = {
					["b_gunitpower"] = true,
					["b_hasproc"] = true,
					["b_p_knownotspell"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_knownotspell"] = "196938",
					["v_p_knowspell"] = "114015",
					["v_p_unitpower"] = "<10",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "185763",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/pistol_shot_deeper_stratagem"] = {
					["b_gunitpower"] = true,
					["b_hasproc"] = true,
					["b_p_knownotspell"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_knownotspell"] = "196938",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "<6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "185763",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/pistol_shot_quick_draw"] = {
					["b_gunitpower"] = true,
					["b_hasproc"] = true,
					["b_p_knownotspell"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gunitpower"] = "2",
					["v_gunitpowertype"] = "4",
					["v_p_knownotspell"] = "193531||114015",
					["v_p_knowspell"] = "196938",
					["v_p_unitpower"] = "<4",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "185763",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/pistol_shot_quick_draw_anticipation"] = {
					["b_gunitpower"] = true,
					["b_hasproc"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gunitpower"] = "2",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "196938||114015",
					["v_p_unitpower"] = "<9",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "185763",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/pistol_shot_quick_draw_deeper_stratagem"] = {
					["b_gunitpower"] = true,
					["b_hasproc"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gunitpower"] = "2",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "196938||193531",
					["v_p_unitpower"] = "<5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "185763",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/roll_the_bones"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_needbuff"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_needbuff"] = "193356^10.8||193357^10.8||193358^10.8||193359^10.8||199600^10.8||199603^10.8||_5171^10.8",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "193316",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/roll_the_bones_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_needbuff"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_needbuff"] = "193356^12.6||193357^12.6||193358^12.6||193359^12.6||199600^12.6||199603^12.6||_5171^12.6",
					["v_p_unitpower"] = "=6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "193316",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/run_through"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "2098",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/run_through_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "=6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "2098",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/saber_slash"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["v_gspellcost"] = "50",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_spellname"] = "193315",
					["v_togglename"] = "Toggle 1",
				},
			},
			["SortedActions"] = {
				"rotation/rogue/kick", -- [1]
				"rotation/rogue/crimson_vial_iron_stomach", -- [2]
				"rotation/rogue/crimson_vial", -- [3]
				"rotation/rogue/blade_flurry", -- [4]
				"rotation/rogue/ambush", -- [5]
				"rotation/rogue/killing_spree", -- [6]
				"rotation/rogue/adrenaline_rush", -- [7]
				"rotation/rogue/marked_for_death_anticipation", -- [8]
				"rotation/rogue/marked_for_death", -- [9]
				"rotation/rogue/roll_the_bones_deeper_stratagem", -- [10]
				"rotation/rogue/roll_the_bones", -- [11]
				"rotation/rogue/death_from_above_deeper_stratagem", -- [12]
				"rotation/rogue/death_from_above", -- [13]
				"rotation/rogue/between_the_eyes_deeper_stratagem", -- [14]
				"rotation/rogue/between_the_eyes", -- [15]
				"rotation/rogue/run_through_deeper_stratagem", -- [16]
				"rotation/rogue/run_through", -- [17]
				"rotation/rogue/blade_rush", -- [18]
				"rotation/rogue/ghostly_strike_anticipation", -- [19]
				"rotation/rogue/ghostly_strike_deeper_stratagem", -- [20]
				"rotation/rogue/ghostly_strike", -- [21]
				"rotation/rogue/pistol_shot_quick_draw_anticipation", -- [22]
				"rotation/rogue/pistol_shot_quick_draw_deeper_stratagem", -- [23]
				"rotation/rogue/pistol_shot_quick_draw", -- [24]
				"rotation/rogue/pistol_shot_anticipation", -- [25]
				"rotation/rogue/pistol_shot_deeper_stratagem", -- [26]
				"rotation/rogue/pistol_shot", -- [27]
				"rotation/rogue/saber_slash", -- [28]
			},
			["isMultiTarget"] = true,
			["specID"] = 2,
			["version"] = 10,
		},
		["rotation/rogue/subtlety"] = {
			["ActionList"] = {
				["rotation/rogue/secret_technique"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "280719",
				},
				["rotation/rogue/secret_technique_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "=6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "280719",
				},
				["rotation/rogue/shuriken_tornado"] = {
					["b_gspellcost"] = true,
					["v_gspellcost"] = "60",
					["v_gspellcosttype"] = "3",
					["v_spellname"] = "277925",
				},
				["rotation/rogue/backstab"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_knownotspell"] = true,
					["b_p_needbuff"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_knownotspell"] = "193531||114015",
					["v_p_needbuff"] = "1784||185422",
					["v_p_unitpower"] = "<5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "53",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/backstab_anticipation"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_knowspell"] = true,
					["b_p_needbuff"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "114015",
					["v_p_needbuff"] = "1784||185422",
					["v_p_unitpower"] = "<10",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "53",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/backstab_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_knowspell"] = true,
					["b_p_needbuff"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "1",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "193531",
					["v_p_needbuff"] = "1784||185422",
					["v_p_unitpower"] = "<6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "53",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/crimson_vial"] = {
					["b_gspellcost"] = true,
					["b_p_hp"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_p_hp"] = "<60%",
					["v_spellname"] = "185311",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/death_from_above"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "269513",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/death_from_above_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "=6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "269513",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/eviscerate"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "196819",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/eviscerate_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "=6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "196819",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/kick"] = {
					["b_t_interrupt"] = true,
					["v_spellname"] = "1766",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/marked_for_death"] = {
					["b_gunitpower"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsbuff"] = true,
					["v_gunitpower"] = "5",
					["v_gunitpowertype"] = "4",
					["v_p_knownotspell"] = "193531||114015",
					["v_p_unitpower"] = "<1",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "137619",
					["v_t_needsbuff"] = "_137619",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/marked_for_death_anticipation"] = {
					["b_gunitpower"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsbuff"] = true,
					["v_gunitpower"] = "5",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "114015",
					["v_p_unitpower"] = "<5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "137619",
					["v_t_needsbuff"] = "_137619",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/marked_for_death_deeper_stratagem"] = {
					["b_gunitpower"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsbuff"] = true,
					["v_gunitpower"] = "5",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "<1",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "137619",
					["v_t_needsbuff"] = "_137619",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/nightblade"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "195452",
					["v_t_needsdebuff"] = "_195452^4.8",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/nightblade_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "=6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "195452",
					["v_t_needsdebuff"] = "_195452^5.4",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/shadow_blades"] = {
					["b_isCustomCase1"] = true,
					["v_spellname"] = "121471",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/shadow_dance"] = {
					["b_charges"] = true,
					["v_charges"] = ">=2",
					["v_p_needbuff"] = "185422||115191",
					["v_spellname"] = "185313",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/shadow_dance_symbols_of_death"] = {
					["b_charges"] = true,
					["b_checkothercd"] = true,
					["b_p_needbuff"] = true,
					["v_charges"] = ">0",
					["v_checkothercdname"] = "212283",
					["v_checkothercdvalue"] = "=0",
					["v_p_needbuff"] = "212283",
					["v_spellname"] = "185313",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/shadowstrikes"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_havebuff"] = true,
					["v_gspellcost"] = "40",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "2",
					["v_gunitpowertype"] = "4",
					["v_p_havebuff"] = "1784||185422||115191",
					["v_spellname"] = "185438",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/symbols_of_death"] = {
					["b_gunitpower"] = true,
					["b_p_havebuff"] = true,
					["b_p_needbuff"] = true,
					["v_gunitpower"] = "40",
					["v_gunitpowertype"] = "3",
					["v_p_havebuff"] = "1784||185422||115192",
					["v_p_needbuff"] = "212283^10.5",
					["v_spellname"] = "212283",
					["v_togglename"] = "Toggle 1",
				},
			},
			["SortedActions"] = {
				"rotation/rogue/kick", -- [1]
				"rotation/rogue/crimson_vial", -- [2]
				"rotation/rogue/marked_for_death_anticipation", -- [3]
				"rotation/rogue/marked_for_death_deeper_stratagem", -- [4]
				"rotation/rogue/marked_for_death", -- [5]
				"rotation/rogue/nightblade_deeper_stratagem", -- [6]
				"rotation/rogue/nightblade", -- [7]
				"rotation/rogue/death_from_above_deeper_stratagem", -- [8]
				"rotation/rogue/death_from_above", -- [9]
				"rotation/rogue/secret_technique_deeper_stratagem", -- [10]
				"rotation/rogue/secret_technique", -- [11]
				"rotation/rogue/eviscerate_deeper_stratagem", -- [12]
				"rotation/rogue/eviscerate", -- [13]
				"rotation/rogue/shadow_blades", -- [14]
				"rotation/rogue/shuriken_tornado", -- [15]
				"rotation/rogue/symbols_of_death", -- [16]
				"rotation/rogue/shadowstrikes", -- [17]
				"rotation/rogue/shadow_dance_symbols_of_death", -- [18]
				"rotation/rogue/shadow_dance", -- [19]
				"rotation/rogue/backstab_anticipation", -- [20]
				"rotation/rogue/backstab_deeper_stratagem", -- [21]
				"rotation/rogue/backstab", -- [22]
			},
			["specID"] = 3,
			["version"] = 10,
		},
		["rotation/rogue/subtlety_multi"] = {
			["ActionList"] = {
				["rotation/rogue/secret_technique"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "280719",
				},
				["rotation/rogue/secret_technique_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "=6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "280719",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/shuriken_tornado"] = {
					["b_gspellcost"] = true,
					["v_gspellcost"] = "60",
					["v_gspellcosttype"] = "3",
					["v_spellname"] = "277925",
				},
				["rotation/rogue/crimson_vial"] = {
					["b_gspellcost"] = true,
					["b_p_hp"] = true,
					["v_gspellcost"] = "30",
					["v_gspellcosttype"] = "3",
					["v_p_hp"] = "<60%",
					["v_spellname"] = "185311",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/death_from_above"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "269513",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/death_from_above_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "=6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "269513",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/eviscerate"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "196819",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/eviscerate_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "=6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "196819",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/kick"] = {
					["b_t_interrupt"] = true,
					["v_spellname"] = "1766",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/marked_for_death"] = {
					["b_gunitpower"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsbuff"] = true,
					["v_gunitpower"] = "5",
					["v_gunitpowertype"] = "4",
					["v_p_knownotspell"] = "193531||114015",
					["v_p_unitpower"] = "<1",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "137619",
					["v_t_needsbuff"] = "_137619",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/marked_for_death_anticipation"] = {
					["b_gunitpower"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsbuff"] = true,
					["v_gunitpower"] = "5",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "114015",
					["v_p_unitpower"] = "<5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "137619",
					["v_t_needsbuff"] = "_137619",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/marked_for_death_deeper_stratagem"] = {
					["b_gunitpower"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsbuff"] = true,
					["v_gunitpower"] = "5",
					["v_gunitpowertype"] = "4",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "<1",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "137619",
					["v_t_needsbuff"] = "_137619",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/nightblade"] = {
					["b_gspellcost"] = true,
					["b_p_knownotspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knownotspell"] = "193531",
					["v_p_unitpower"] = ">=5",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "195452",
					["v_t_needsdebuff"] = "_195452^4.8",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/nightblade_deeper_stratagem"] = {
					["b_gspellcost"] = true,
					["b_p_knowspell"] = true,
					["b_p_unitpower"] = true,
					["b_t_needsdebuff"] = true,
					["v_gspellcost"] = "25",
					["v_gspellcosttype"] = "3",
					["v_p_knowspell"] = "193531",
					["v_p_unitpower"] = "=6",
					["v_p_unitpowertype"] = "4",
					["v_spellname"] = "195452",
					["v_t_needsdebuff"] = "_195452^5.4",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/shadow_blades"] = {
					["b_isCustomCase1"] = true,
					["v_spellname"] = "121471",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/shadow_dance"] = {
					["b_charges"] = true,
					["v_charges"] = ">=2",
					["v_spellname"] = "185313",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/shadow_dance_symbols_of_death"] = {
					["b_charges"] = true,
					["b_checkothercd"] = true,
					["b_p_needbuff"] = true,
					["v_charges"] = ">0",
					["v_checkothercdname"] = "212283",
					["v_checkothercdvalue"] = "=0",
					["v_p_needbuff"] = "212283",
					["v_spellname"] = "185313",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/shadowstrikes"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["b_p_havebuff"] = true,
					["v_gspellcost"] = "40",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "2",
					["v_gunitpowertype"] = "4",
					["v_p_havebuff"] = "1784",
					["v_spellname"] = "185438",
					["v_togglename"] = "Toggle 1",
				},
				["rotation/rogue/shuriken_storm"] = {
					["b_gspellcost"] = true,
					["b_gunitpower"] = true,
					["v_gspellcost"] = "35",
					["v_gspellcosttype"] = "3",
					["v_gunitpower"] = "2",
					["v_gunitpowertype"] = "4",
					["v_spellname"] = "197835",
				},
				["rotation/rogue/symbols_of_death"] = {
					["b_gunitpower"] = true,
					["b_p_havebuff"] = true,
					["b_p_needbuff"] = true,
					["v_gunitpower"] = "40",
					["v_gunitpowertype"] = "3",
					["v_p_havebuff"] = "1784||185422||115192",
					["v_p_needbuff"] = "212283^10.5",
					["v_spellname"] = "212283",
					["v_togglename"] = "Toggle 1",
				},
			},
			["SortedActions"] = {
				"rotation/rogue/kick", -- [1]
				"rotation/rogue/crimson_vial", -- [2]
				"rotation/rogue/marked_for_death_anticipation", -- [3]
				"rotation/rogue/marked_for_death_deeper_stratagem", -- [4]
				"rotation/rogue/marked_for_death", -- [5]
				"rotation/rogue/death_from_above_deeper_stratagem", -- [6]
				"rotation/rogue/death_from_above", -- [7]
				"rotation/rogue/secret_technique_deeper_stratagem", -- [8]
				"rotation/rogue/secret_technique", -- [9]
				"rotation/rogue/nightblade_deeper_stratagem", -- [10]
				"rotation/rogue/nightblade", -- [11]
				"rotation/rogue/eviscerate_deeper_stratagem", -- [12]
				"rotation/rogue/eviscerate", -- [13]
				"rotation/rogue/shadow_blades", -- [14]
				"rotation/rogue/shuriken_tornado", -- [15]
				"rotation/rogue/symbols_of_death", -- [16]
				"rotation/rogue/shadowstrikes", -- [17]
				"rotation/rogue/shadow_dance_symbols_of_death", -- [18]
				"rotation/rogue/shadow_dance", -- [19]
				"rotation/rogue/shuriken_storm", -- [20]
			},
			["isMultiTarget"] = true,
			["specID"] = 3,
			["version"] = 10,
		},
	}

	return rotation;
end

local rogueRotationsGeneratorData = {
	["generator"] = rogueRotationsGenerator
};

RotationBuilder:addDefaultRotationsGenerator("ROGUE", rogueRotationsGeneratorData);
