local L = LibStub("AceLocale-3.0"):NewLocale("RotationBuilder", "enUS", true, true)
if not L then return end

--@do-not-package@
-- Default localization for development stage.
L["defaultRotation/deathknight/apocalypse"] = "Apocalypse"
L["defaultRotation/deathknight/apocalypse_soul_reaper"] = "Apocalypse (Soul Reaper)"
L["defaultRotation/deathknight/army_of_the_dead"] = "Army of the Dead"
L["defaultRotation/deathknight/blighted_rune_weapon"] = "Blighted Rune Weapon"
L["defaultRotation/deathknight/blood"] = "Blood 7.1.5"
L["defaultRotation/deathknight/blood_boil"] = "Blood Boil"
L["defaultRotation/deathknight/blood_boil_blood_plague"] = "Blood Boil (Blood Plague)"
L["defaultRotation/deathknight/blood_multi"] = "Blood Multi 7.1.5"
L["defaultRotation/deathknight/blood_tap"] = "Blood Tap"
L["defaultRotation/deathknight/blooddrinker"] = "Blooddrinker"
L["defaultRotation/deathknight/bonestorm"] = "Bonestorm"
L["defaultRotation/deathknight/breath_of_sindragosa"] = "Breath of Sindragosa"
L["defaultRotation/deathknight/consumption"] = "Consumption"
L["defaultRotation/deathknight/dark_arbiter"] = "Dark Arbiter"
L["defaultRotation/deathknight/dark_transformation"] = "Dark Transformation"
L["defaultRotation/deathknight/death_and_decay"] = "Death and Decay"
L["defaultRotation/deathknight/death_and_decay_crimson scourge"] = "Death and Decay (Crimson Scourge)"
L["defaultRotation/deathknight/death_caress"] = "Death's Caress"
L["defaultRotation/deathknight/death_coil"] = "Death Coil"
L["defaultRotation/deathknight/death_coil_dark_arbiter"] = "Death Coil (Dark Arbiter)"
L["defaultRotation/deathknight/death_coil_necrosis"] = "Death Coil (Necrosis)"
L["defaultRotation/deathknight/death_coil_shadow_infusion"] = "Death Coil (Shadow Infusion)"
L["defaultRotation/deathknight/death_coil_sudden_doom"] = "Death Coil (Sudden Doom)"
L["defaultRotation/deathknight/death_strike"] = "Death Strike"
L["defaultRotation/deathknight/defile"] = "Defile"
L["defaultRotation/deathknight/empower_rune_weapon"] = "Empower Rune Weapon"
L["defaultRotation/deathknight/empower_rune_weapon_breath_of_sindragosa"] = "Empower Rune Weapon (Breath of Sindragosa)"
L["defaultRotation/deathknight/epidemic"] = "Epidemic"
L["defaultRotation/deathknight/epidemic_defile"] = "Epidemic (Defile)"
L["defaultRotation/deathknight/festering_strike"] = "Festering Strike"
L["defaultRotation/deathknight/festering_strike_apocalypse"] = "Festering Strike (Apocalypse)"
L["defaultRotation/deathknight/festering_strike_dark_arbiter"] = "Festering Strike (Dark Arbiter)"
L["defaultRotation/deathknight/frost"] = "Frost 7.1.5"
L["defaultRotation/deathknight/frost_multi"] = "Frost Multi 7.1.5"
L["defaultRotation/deathknight/frost_strike"] = "Frost Strike"
L["defaultRotation/deathknight/frost_strike_breath_of_sindragosa"] = "Frost Strike (Breath of Sindragosa)"
L["defaultRotation/deathknight/frost_strike_icy_talons"] = "Frost Strike (Icy Talons)"
L["defaultRotation/deathknight/frost_strike_obliteration"] = "Frost Strike (Obliteration)"
L["defaultRotation/deathknight/frost_strike_runic_power"] = "Frost Strike (Runic Power)"
L["defaultRotation/deathknight/frost_strike_shattering_strikes"] = "Frost Strike (Stattering Strikes)"
L["defaultRotation/deathknight/frostscythe"] = "Frostscythe"
L["defaultRotation/deathknight/frostscythe_breath_of_sindragosa"] = "Frostscythe (Breath of Sindragosa)"
L["defaultRotation/deathknight/frostscythe_killing_machine"] = "Faux de givre (Killing Machine)"
L["defaultRotation/deathknight/glacial_advance"] = "Glacial Advance"
L["defaultRotation/deathknight/heart_strike"] = "Heart Strike"
L["defaultRotation/deathknight/horn_of_winter"] = "Horn of Winter"
L["defaultRotation/deathknight/horn_of_winter_breath_of_sindragosa"] = "Horn of Winter (Breath of Sindragosa)"
L["defaultRotation/deathknight/horn_of_winter_breath_of_sindragosa_hungering_rune"] = "Horn of Winter (Breath of Sindragosa (Hungering Rune))"
L["defaultRotation/deathknight/howling_blast"] = "Howling Blast"
L["defaultRotation/deathknight/howling_blast_breath_of_sindragosa"] = "Howling Blast (Breath of Sindragosa)"
L["defaultRotation/deathknight/howling_blast_frost_fever"] = "Howling Blast (Frost Fever)"
L["defaultRotation/deathknight/hungering_rune"] = "Hungering Rune"
L["defaultRotation/deathknight/hungering_rune_breath_of_sindragosa"] = "Hungering Rune (Breath of Sindragosa)"
L["defaultRotation/deathknight/mark_of_blood"] = "Mark of Blood"
L["defaultRotation/deathknight/marrowrend"] = "Marrowrend"
L["defaultRotation/deathknight/marrowrend_bone_shield"] = "Marrowrend (Bone Shield)"
L["defaultRotation/deathknight/mind_freeze"] = "Mind Freeze"
L["defaultRotation/deathknight/obliterate"] = "Obliterate"
L["defaultRotation/deathknight/obliterate_breath_of_sindragosa"] = "Obliterate (Breath of Sindragosa)"
L["defaultRotation/deathknight/obliterate_killing_machine"] = "Obliterate (Killing Machine)"
L["defaultRotation/deathknight/obliteration"] = "Obliteration"
L["defaultRotation/deathknight/outbreak"] = "Outbreak"
L["defaultRotation/deathknight/pillar_of_frost"] = "Pillar of Frost"
L["defaultRotation/deathknight/pillar_of_frost_breath_of_sindragosa"] = "Pillar of Frost (Breath of Sindragosa)"
L["defaultRotation/deathknight/pillar_of_frost_breath_of_sindragosa_ready"] = "Pillar of Frost (Breath of Sindragosa Ready)"
L["defaultRotation/deathknight/raise_dead"] = "Raise Dead"
L["defaultRotation/deathknight/remorseless_winter"] = "Remorseless Winter"
L["defaultRotation/deathknight/remorseless_winter_breath_of_sindragosa"] = "Remorseless Winter (Breath of Sindragosa)"
L["defaultRotation/deathknight/scourge_strike"] = "Scourge Strike"
L["defaultRotation/deathknight/scourge_strike_scourge_of_worlds"] = "Scourge Strike (Scourge of Worlds)"
L["defaultRotation/deathknight/scourge_strike_soul_reaper"] = "Scourge Strike (Soul Reaper)"
L["defaultRotation/deathknight/scourge_strike_soul_reaper_soon"] = "Scourge Strike (Soul Reaper Soon)"
L["defaultRotation/deathknight/sindragosa_fury"] = "Sindragosa's Fury"
L["defaultRotation/deathknight/soul_reaper"] = "Soul Reaper"
L["defaultRotation/deathknight/soul_reaper_apocalypse"] = "Soul Reaper (Apocalypse)"
L["defaultRotation/deathknight/soulgorge"] = "Soulgorge"
L["defaultRotation/deathknight/summon_gargoyle"] = "Summon Gargoyle"
L["defaultRotation/deathknight/unholy"] = "Unholy 7.1.5"
L["defaultRotation/deathknight/unholy_multi"] = "Unholy Multi 7.1.5"
L["defaultRotation/deathknight/vampiric_blood"] = "Vampiric Blood"
L["defaultRotation/demonhunter/annihilation"] = "Annihilation"
L["defaultRotation/demonhunter/annihilation_chaos_cleave"] = "Annihilation (Chaos Cleave)"
L["defaultRotation/demonhunter/annihilation_demon_blades"] = "Annihilation (Demon Blades)"
L["defaultRotation/demonhunter/blade_dance"] = "Blade dance"
L["defaultRotation/demonhunter/chaos_blades"] = "Chaos blades"
L["defaultRotation/demonhunter/chaos_strike"] = "Chaos Strike"
L["defaultRotation/demonhunter/chaos_strike_chaos_cleave"] = "Chaos Strike (Chaos Cleave)"
L["defaultRotation/demonhunter/chaos_strike_demon_blades"] = "Chaos Strike (Demon Blades)"
L["defaultRotation/demonhunter/consume_magic"] = "Consume Magic"
L["defaultRotation/demonhunter/death_sweep"] = "Death Sweep"
L["defaultRotation/demonhunter/demon_bite"] = "Demon's Bite"
L["defaultRotation/demonhunter/demon_spikes"] = "Demon Spikes"
L["defaultRotation/demonhunter/eye_beam"] = "Eye beam"
L["defaultRotation/demonhunter/fel_barrage"] = "Fel barrage"
L["defaultRotation/demonhunter/fel_devastation"] = "Fel devastation"
L["defaultRotation/demonhunter/fel_eruption"] = "Fel eruption"
L["defaultRotation/demonhunter/fel_rush"] = "Fel Rush"
L["defaultRotation/demonhunter/fel_rush_fel_mastery"] = "Fel Rush (Fel Mastery)"
L["defaultRotation/demonhunter/fel_rush_momentum"] = "Fel rush (Momentum)"
L["defaultRotation/demonhunter/fel_rush_momentum_fel_mastery"] = "Fel rush (Momentum + Fel mastery)"
L["defaultRotation/demonhunter/felblade"] = "Felblade"
L["defaultRotation/demonhunter/fracture"] = "Fracture"
L["defaultRotation/demonhunter/fury_of_the_illidari"] = "Fury of the Illidari"
L["defaultRotation/demonhunter/havoc"] = "Havoc 7.1.5"
L["defaultRotation/demonhunter/havoc_multi"] = "Havoc Multi 7.1.5"
L["defaultRotation/demonhunter/immolation_aura"] = "Immolation Aura"
L["defaultRotation/demonhunter/infernal_strike"] = "Infernal Strike"
L["defaultRotation/demonhunter/metamorphosis"] = "Metamorphosis"
L["defaultRotation/demonhunter/nemesis"] = "Nemesis"
L["defaultRotation/demonhunter/shear"] = "Shear"
L["defaultRotation/demonhunter/shear_blade_turning"] = "Shear (Blade turning)"
L["defaultRotation/demonhunter/sigil_of_flame"] = "Sigil of Flame"
L["defaultRotation/demonhunter/soul_barrier"] = "Soul barrier"
L["defaultRotation/demonhunter/soul_cleave"] = "Soul Cleave"
L["defaultRotation/demonhunter/soul_rending"] = "Soul rending"
L["defaultRotation/demonhunter/spirit_bomb"] = "Spirit bomb"
L["defaultRotation/demonhunter/throw_glaive"] = "Throw Glaive"
L["defaultRotation/demonhunter/throw_glaive_bloodlet"] = "Throw glaive (Bloodlet)"
L["defaultRotation/demonhunter/vengeance"] = "Vengeance 7.1.5"
L["defaultRotation/demonhunter/vengeance_multi"] = "Vengeance Multi 7.1.5"
L["defaultRotation/demonhunter/vengeful_retreat"] = "Vengeful Retreat"
L["defaultRotation/demonhunter/vengeful_retreat_momentum"] = "Vengeful Retreat (Momentum)"
L["defaultRotation/demonhunter/vengeful_retreat_momentum_prepared"] = "Vengeful Retreat (Momentum + Prepared)"
L["defaultRotation/druid/ashamane_frenzy"] = "Ashamane's Frenzy"
L["defaultRotation/druid/ashamane_frenzy_bloodtalons"] = "Ashamane's Frenzy (Bloodtalons)"
L["defaultRotation/druid/astral_communion"] = "Astral Communion"
L["defaultRotation/druid/astral_communion_fury_of_elune"] = "Astral Communion (Fury of Elune)"
L["defaultRotation/druid/balance"] = "Balance 7.1.5"
L["defaultRotation/druid/balance_multi"] = "Balance Multi 7.1.5"
L["defaultRotation/druid/bear_form"] = "Bear Form"
L["defaultRotation/druid/berserk"] = "Berserk"
L["defaultRotation/druid/blessing_of_the_ancients"] = "Blessing of the Ancients"
L["defaultRotation/druid/bristling_fur"] = "Bristling Fur"
L["defaultRotation/druid/brutal_slash"] = "Brutal Slash"
L["defaultRotation/druid/cat_form"] = "Cat Form"
L["defaultRotation/druid/celestial_alignment"] = "Celestial Alignment"
L["defaultRotation/druid/cenarion_ward"] = "Cenarion Ward"
L["defaultRotation/druid/elune_guidance"] = "Elune's Guidance"
L["defaultRotation/druid/feral"] = "Feral 7.1.5"
L["defaultRotation/druid/feral_multi"] = "Feral Multi 7.1.5"
L["defaultRotation/druid/ferocious_bite"] = "Ferocious Bite"
L["defaultRotation/druid/ferocious_bite_rip"] = "Ferocious Bite (Rip)"
L["defaultRotation/druid/ferocious_bite_rip_jagged_wounds"] = "Ferocious Bite (Rip (Jagged Wounds))"
L["defaultRotation/druid/ferocious_bite_sabertooth"] = "Ferocious Bite (Sabertooth)"
L["defaultRotation/druid/ferocious_bite_savage_roar"] = "Ferocious Bite (Savage Roar)"
L["defaultRotation/druid/force_of_nature"] = "Force of Nature"
L["defaultRotation/druid/frenzied_regeneration"] = "Frenzied Regeneration"
L["defaultRotation/druid/fury_of_elune"] = "Fury of Elune"
L["defaultRotation/druid/guardian"] = "Guardian 7.1.5"
L["defaultRotation/druid/guardian_multi"] = "Guardian Multi 7.1.5"
L["defaultRotation/druid/incarnation_chosen_of_elune"] = "Incarnation: Chosen of Elune"
L["defaultRotation/druid/incarnation_king_of_the_jungle"] = "Incarnation: King of the Jungle"
L["defaultRotation/druid/ironfur"] = "Ironfur"
L["defaultRotation/druid/lunar_beam"] = "Lunar Beam"
L["defaultRotation/druid/lunar_strike"] = "Lunar Strike"
L["defaultRotation/druid/lunar_strike_warrior_of_elune"] = "Lunar Strike (Warrior of Elune)"
L["defaultRotation/druid/mangle"] = "Mangle"
L["defaultRotation/druid/mark_of_ursol"] = "Mark of Ursol"
L["defaultRotation/druid/maul"] = "Maul"
L["defaultRotation/druid/moonfire"] = "Moonfire"
L["defaultRotation/druid/moonfire_balance"] = "Moonfire (Balance)"
L["defaultRotation/druid/moonfire_fury_of_elune"] = "Moonfire (Fury of Elune)"
L["defaultRotation/druid/moonfire_galactic_guardian"] = "Moonfire (Galactic Guardian)"
L["defaultRotation/druid/moonkin_form"] = "Moonkin Form"
L["defaultRotation/druid/new_moon"] = "New Moon"
L["defaultRotation/druid/new_moon_fury_of_elune"] = "New Moon (Fury of Elune)"
L["defaultRotation/druid/new_moon_fury_of_elune_reload"] = "New Moon (Fury of Elune Reload)"
L["defaultRotation/druid/new_moon_fury_of_elune_soon"] = "New Moon (Fury of Elune Soon)"
L["defaultRotation/druid/pulverize"] = "Pulverize"
L["defaultRotation/druid/rage_of_the_sleeper"] = "Rage of the Sleeper"
L["defaultRotation/druid/rake"] = "Rake"
L["defaultRotation/druid/rake_jagged_wounds"] = "Rake (Jagged Wounds)"
L["defaultRotation/druid/regrowth"] = "Regrowth"
L["defaultRotation/druid/regrowth_bloodtalons"] = "Regrowth (Bloodalons)"
L["defaultRotation/druid/renewal"] = "Renewal"
L["defaultRotation/druid/restoration"] = "Restoration 7.1.5"
L["defaultRotation/druid/restoration_multi"] = "Restoration Multi 7.1.5"
L["defaultRotation/druid/rip"] = "Rip"
L["defaultRotation/druid/rip_jagged_wounds"] = "Rip (Jagged Wounds)"
L["defaultRotation/druid/savage_roar"] = "Savage Roar"
L["defaultRotation/druid/shred"] = "Shred"
L["defaultRotation/druid/skull_bash"] = "Skull Bash"
L["defaultRotation/druid/solar_beam"] = "Solar Beam"
L["defaultRotation/druid/solar_wrath"] = "Solar Wrath"
L["defaultRotation/druid/starfall"] = "Starfall"
L["defaultRotation/druid/starfall_fury_of_elune"] = "Starfall (Fury of Elune)"
L["defaultRotation/druid/starsurge"] = "Starsurge"
L["defaultRotation/druid/starsurge_fury_of_elune"] = "Starsurge (Fury of Elune)"
L["defaultRotation/druid/stellar_flare"] = "Stellar Flare"
L["defaultRotation/druid/sunfire"] = "Sunfire"
L["defaultRotation/druid/sunfire_fury_of_elune"] = "Sunfire (Fury of Elune)"
L["defaultRotation/druid/swipe"] = "Swipe"
L["defaultRotation/druid/swipe_feral"] = "Swipe (Feral)"
L["defaultRotation/druid/swipe_guardian"] = "Swipe (Guardian)"
L["defaultRotation/druid/thrash"] = "Thrash"
L["defaultRotation/druid/thrash_guardian"] = "Thrash (Guardian)"
L["defaultRotation/druid/thrash_jagged_wounds"] = "Thrash (Jagged Wounds)"
L["defaultRotation/druid/tiger_fury"] = "Tiger's Fury"
L["defaultRotation/druid/warrior_of_elune"] = "Warrior of Elune"
L["defaultRotation/druid/wild_charge"] = "Wild Charge"
L["defaultRotation/hunter/a_murder_of_crows"] = "A Murder of Crows"
L["defaultRotation/hunter/aimed_shot"] = "Aimed Shot"
L["defaultRotation/hunter/aimed_shot_vunerable"] = "Aimed Shot (Vulnerable)"
L["defaultRotation/hunter/arcane_shot"] = "Arcane Shot"
L["defaultRotation/hunter/arcane_shot_steady_focus"] = "Arcane Shot (Steady Focus)"
L["defaultRotation/hunter/aspect_of_the_eagle"] = "Aspect of the Eagle"
L["defaultRotation/hunter/aspect_of_the_wild"] = "Aspect of the Wild"
L["defaultRotation/hunter/barrage"] = "Barrage"
L["defaultRotation/hunter/beast_mastery"] = "Beast Mastery 7.1.5"
L["defaultRotation/hunter/beast_mastery_multi"] = "Beast Mastery Multi 7.1.5"
L["defaultRotation/hunter/bestial_wrath"] = "Bestial Wrath"
L["defaultRotation/hunter/black_arrow"] = "Black Arrow"
L["defaultRotation/hunter/butchery"] = "Butchery"
L["defaultRotation/hunter/caltrops"] = "Caltrops"
L["defaultRotation/hunter/carve"] = "Carve"
L["defaultRotation/hunter/carve_serpent_sting"] = "Carve (Serpent Sting)"
L["defaultRotation/hunter/chimaera_shot"] = "Chimaera Shot"
L["defaultRotation/hunter/cobra_shot"] = "Cobra Shot"
L["defaultRotation/hunter/cobra_shot_bestial_wrath"] = "Cobra Shot (Bestial Wrath)"
L["defaultRotation/hunter/cobra_shot_bestial_wrath_soon"] = "Cobra Shot (Bestial Wrath Soon)"
L["defaultRotation/hunter/counter_shot"] = "Counter Shot"
L["defaultRotation/hunter/dire_beast"] = "Dire Beast"
L["defaultRotation/hunter/dire_frenzy"] = "Dire Frenzy"
L["defaultRotation/hunter/dragonsfire_grenade"] = "Dragonsfire Grenade"
L["defaultRotation/hunter/explosive_shot"] = "Explosive Shot"
L["defaultRotation/hunter/explosive_trap"] = "Explosive Trap"
L["defaultRotation/hunter/flanking_strike"] = "Flanking Strike"
L["defaultRotation/hunter/fury_of_the_eagle"] = "Fury of the Eagle"
L["defaultRotation/hunter/harpoon"] = "Harpoon"
L["defaultRotation/hunter/kill_command"] = "Kill Command"
L["defaultRotation/hunter/kill_command_bestial_wrath"] = "Kill Command (Bestial Wrath)"
L["defaultRotation/hunter/lacerate"] = "Lacerate"
L["defaultRotation/hunter/marked_shot"] = "Marked Shot"
L["defaultRotation/hunter/marksmanship"] = "Marksmanship 7.1.5"
L["defaultRotation/hunter/marksmanship_multi"] = "Marksmanship Multi 7.1.5"
L["defaultRotation/hunter/mend_pet"] = "Mend Pet"
L["defaultRotation/hunter/mongoose_bite"] = "Mongoose Bite"
L["defaultRotation/hunter/mongoose_bite_3_charges"] = "Mongoose Bite (3 Charges)"
L["defaultRotation/hunter/multi-shot"] = "Multi-Shot"
L["defaultRotation/hunter/multi-shot_barrage"] = "Multi-Shot (Barrage)"
L["defaultRotation/hunter/multi-shot_barrage_ready"] = "Multi-Shot (Barrage Ready)"
L["defaultRotation/hunter/multi-shot_steady_focus"] = "Multi-Shot (Steady Focus)"
L["defaultRotation/hunter/muzzle"] = "Muzzle"
L["defaultRotation/hunter/piercing_shot"] = "Piercing Shot"
L["defaultRotation/hunter/raptor_strike"] = "Raptor Strike"
L["defaultRotation/hunter/raptor_strike_serpent_sting"] = "Raptor Strike (Serpent Sting)"
L["defaultRotation/hunter/raptor_strike_way_of_the_mok_nathal"] = "Raptor Strike (Way of the Mok'Nathal)"
L["defaultRotation/hunter/revive_pet"] = "Revive Pet"
L["defaultRotation/hunter/sentinel"] = "Sentinel"
L["defaultRotation/hunter/sidewinders"] = "Sidewinders"
L["defaultRotation/hunter/sidewinders_2_charges"] = "Sidewinders (2 Charges)"
L["defaultRotation/hunter/snake_hunter"] = "Snake Hunter"
L["defaultRotation/hunter/spitting_cobra"] = "Spitting Cobra"
L["defaultRotation/hunter/stampede"] = "Stampede"
L["defaultRotation/hunter/steel_trap"] = "Steel Trap"
L["defaultRotation/hunter/survival"] = "Survival 7.1.5"
L["defaultRotation/hunter/survival_multi"] = "Survival Multi 7.1.5"
L["defaultRotation/hunter/throwing_axes"] = "Throwing Axes"
L["defaultRotation/hunter/titan_thunder"] = "Titan's Thunder"
L["defaultRotation/hunter/titan_thunder_dire_frenzy"] = "Titan's Thunder (Dire Frenzy)"
L["defaultRotation/hunter/trueshot"] = "Trueshot"
L["defaultRotation/hunter/volley"] = "Volley"
L["defaultRotation/hunter/windburst"] = "Windburst"
L["defaultRotation/mage/arcane"] = "Arcane 7.1.5"
L["defaultRotation/mage/arcane_barrage"] = "Arcane Barrage"
L["defaultRotation/mage/arcane_barrage_arcane_power"] = "Arcane Barrage (Arcane Power)"
L["defaultRotation/mage/arcane_barrage_mana"] = "Arcane Barrage (Mana)"
L["defaultRotation/mage/arcane_barrage_mana_85"] = "Arcane Barrage (Mana 85%)"
L["defaultRotation/mage/arcane_blast"] = "Arcane Blast"
L["defaultRotation/mage/arcane_explosion"] = "Arcane Explosion"
L["defaultRotation/mage/arcane_familiar"] = "Arcane Familiar"
L["defaultRotation/mage/arcane_missiles"] = "Arcane Missiles"
L["defaultRotation/mage/arcane_missiles_3_charges"] = "Arcane Missiles (3 Charges)"
L["defaultRotation/mage/arcane_missiles_arcane_power"] = "Arcane Missiles (Arcane Power)"
L["defaultRotation/mage/arcane_missiles_mana"] = "Arcane Missiles (Mana)"
L["defaultRotation/mage/arcane_missiles_mana_85"] = "Arcane Missiles (Mana 85%)"
L["defaultRotation/mage/arcane_multi"] = "Arcane Multi 7.1.5"
L["defaultRotation/mage/arcane_orb"] = "Arcane Orb"
L["defaultRotation/mage/arcane_power"] = "Arcane Power"
L["defaultRotation/mage/blazing_barrier"] = "Blazing Barrier"
L["defaultRotation/mage/blizzard"] = "Blizzard"
L["defaultRotation/mage/charged_up"] = "Charged Up"
L["defaultRotation/mage/cinderstorm"] = "Cinderstorm"
L["defaultRotation/mage/combustion"] = "Combustion"
L["defaultRotation/mage/comet_storm"] = "Comet Storm"
L["defaultRotation/mage/counterspell"] = "Counterspell"
L["defaultRotation/mage/dragon_breath"] = "Dragon's Breath"
L["defaultRotation/mage/ebonbolt"] = "Ebonbolt"
L["defaultRotation/mage/evocation"] = "Evocation"
L["defaultRotation/mage/fire"] = "Fire 7.1.5"
L["defaultRotation/mage/fire_blast"] = "Fire Blast"
L["defaultRotation/mage/fire_multi"] = "Fire Multi 7.1.5"
L["defaultRotation/mage/fireball"] = "Fireball"
L["defaultRotation/mage/flamestrke"] = "Flamestrike"
L["defaultRotation/mage/flurry"] = "Flurry"
L["defaultRotation/mage/frost"] = "Frost 7.1.5"
L["defaultRotation/mage/frost_bomb"] = "Frost Bomb"
L["defaultRotation/mage/frost_multi"] = "Frost Multi 7.1.5"
L["defaultRotation/mage/frostbolt"] = "Frostbolt"
L["defaultRotation/mage/frozen_orb"] = "Frozen Orb"
L["defaultRotation/mage/glacial_spike"] = "Glacial Spike"
L["defaultRotation/mage/ice_barrier"] = "Ice Barrier"
L["defaultRotation/mage/ice_lance"] = "Ice Lance"
L["defaultRotation/mage/ice_lance_brain_freeze"] = "Ice Lance (Brain Freeze)"
L["defaultRotation/mage/ice_lance_fingers_of_frost"] = "Ice Lance (Fingers of Frost)"
L["defaultRotation/mage/ice_lance_winter_chill"] = "Ice Lance (Winter's Chill)"
L["defaultRotation/mage/ice_nova"] = "Ice Nova"
L["defaultRotation/mage/icy_veins"] = "Icy Veins"
L["defaultRotation/mage/living_bomb"] = "Living Bomb"
L["defaultRotation/mage/mark_of_aluneth"] = "Mark of Aluneth"
L["defaultRotation/mage/meteor"] = "Meteor"
L["defaultRotation/mage/mirror_image"] = "Mirror Image"
L["defaultRotation/mage/nether_tempest"] = "Nether Tempest"
L["defaultRotation/mage/phoenix_flames"] = "Phoenix's Flames"
L["defaultRotation/mage/phoenix_flames_combustion"] = "Phoenix's Flames (Combustion)"
L["defaultRotation/mage/phoenix_flames_combustion_soon"] = "Phoenix's Flames (Combustion Soon)"
L["defaultRotation/mage/presence_of_mind"] = "Presence of Mind"
L["defaultRotation/mage/prismatic_barrier"] = "Prismatic Barrier"
L["defaultRotation/mage/pyroblast"] = "Pyroblast"
L["defaultRotation/mage/ray_of_frost"] = "Ray of Frost"
L["defaultRotation/mage/rune_of_power"] = "Rune of Power"
L["defaultRotation/mage/rune_of_power_2_charges"] = "Rune of Power (2 Charges)"
L["defaultRotation/mage/rune_of_power_combustion"] = "Rune of Power (Combustion)"
L["defaultRotation/mage/rune_of_power_frozen_orb"] = "Rune of Power (Frozen Orb)"
L["defaultRotation/mage/rune_of_power_icy_veins"] = "Rune of Power (Icy Veins)"
L["defaultRotation/mage/rune_of_power_ray_of_frost"] = "Rune of Power (Ray of Frost)"
L["defaultRotation/mage/scorch"] = "Scorch"
L["defaultRotation/mage/scorch_combustion"] = "Scorch (Combustion)"
L["defaultRotation/mage/spellsteal"] = "Spellsteal"
L["defaultRotation/mage/summon_water_elemental"] = "Summon Water Elemental"
L["defaultRotation/mage/supernova"] = "Supernova"
L["defaultRotation/mage/water_jet"] = "Water Jet"
L["defaultRotation/monk/black_ox_brew"] = "Black Ox Brew"
L["defaultRotation/monk/blackout_kick"] = "Blackout Kick"
L["defaultRotation/monk/blackout_kick_blackout_kick"] = "Blackout Kick (Blackout kick!)"
L["defaultRotation/monk/blackout_kick_serenity"] = "Blackout Kick (Serenity)"
L["defaultRotation/monk/blackout_kick_spirit_of_the_crane"] = "Blackout Kick (Spirit of the Crane)"
L["defaultRotation/monk/blackout_strike"] = "Blackout Strike"
L["defaultRotation/monk/breath_of_fire"] = "Breath of Fire"
L["defaultRotation/monk/brewmaster"] = "Brewmaster 7.1.5"
L["defaultRotation/monk/brewmaster_multi"] = "Brewmaster Multi 7.1.5"
L["defaultRotation/monk/chi_burst"] = "Chi Burst"
L["defaultRotation/monk/chi_wave"] = "Chi Wave"
L["defaultRotation/monk/energising_elixir"] = "Energising Elixir"
L["defaultRotation/monk/expel_harm"] = "Expel Harm"
L["defaultRotation/monk/exploding_keg"] = "Exploding Keg"
L["defaultRotation/monk/fists_of_fury"] = "Fists of Fury"
L["defaultRotation/monk/fists_of_fury_serenity"] = "Fists of Fury (Serenity)"
L["defaultRotation/monk/healing_elixir"] = "Healing Elixir"
L["defaultRotation/monk/invoke_xuen_the_white_tiger"] = "Invoke Xuen, the White Tiger"
L["defaultRotation/monk/ironskin_brew"] = "Ironskin Brew"
L["defaultRotation/monk/keg_smash"] = "Keg Smash"
L["defaultRotation/monk/mistweaver"] = "Mistweaver 7.1.5"
L["defaultRotation/monk/mistweaver_multi"] = "Mistweaver Multi 7.1.5"
L["defaultRotation/monk/purifying_brew"] = "Purifying Brew"
L["defaultRotation/monk/rising_sun_kick"] = "Rising Sun Kick"
L["defaultRotation/monk/rising_sun_kick_serenity"] = "Rising Sun Kick (Serenity)"
L["defaultRotation/monk/rushing_jade_wind"] = "Rushing Jade Wind"
L["defaultRotation/monk/rushing_jade_wind_serenity"] = "Rushing Jade Wind (Serenity)"
L["defaultRotation/monk/serenity"] = "Serenity"
L["defaultRotation/monk/spear_hand_strike"] = "Spear Hand Strike"
L["defaultRotation/monk/spinning_crane_kick"] = "Spinning Crane Kick"
L["defaultRotation/monk/spinning_crane_kick_serenity"] = "Spinning Crane Kick (Serenity)"
L["defaultRotation/monk/storm_earth_and_fire"] = "Storm, Earth, and Fire"
L["defaultRotation/monk/storm_earth_and_fire_fists_of_fury"] = "Storm, Earth, and Fire (Fists of Fury)"
L["defaultRotation/monk/strike_of_the_windlord"] = "Strike of the Windlord"
L["defaultRotation/monk/strike_of_the_windlord_serenity"] = "Strike of the Windlord (Serenity)"
L["defaultRotation/monk/thunder_focus_tea"] = "Thunder Focus Tea"
L["defaultRotation/monk/tiger_palm"] = "Tiger Palm"
L["defaultRotation/monk/tiger_palm_energy"] = "Tiger Palm (Energy)"
L["defaultRotation/monk/tiger_palm_eye_of_the_tiger"] = "Tiger Palm (Eye of the Tiger)"
L["defaultRotation/monk/touch_of_death"] = "Touch of Death"
L["defaultRotation/monk/whirling_dragon_punch"] = "Whirling Dragon Punch"
L["defaultRotation/monk/windwalker"] = "Windwalker 7.1.5"
L["defaultRotation/monk/windwalker_multi"] = "Windwalker Multi 7.1.5"
L["defaultRotation/monk/zen_pulse"] = "Zen Pulse"
L["defaultRotation/paladin/avenger_shield"] = "Avenger's Shield"
L["defaultRotation/paladin/avenging_wrath"] = "Avenging Wrath"
L["defaultRotation/paladin/blade_of_justice"] = "Blade of Justice"
L["defaultRotation/paladin/blessed_hammer"] = "Blessed Hammer"
L["defaultRotation/paladin/consecration"] = "Consecration"
L["defaultRotation/paladin/crusade"] = "Crusade"
L["defaultRotation/paladin/crusader_strike"] = "Crusader Strike"
L["defaultRotation/paladin/divine_hammer"] = "Divine Hammer"
L["defaultRotation/paladin/divine_storm"] = "Divine Storm"
L["defaultRotation/paladin/execution_sentence"] = "Execution Sentence"
L["defaultRotation/paladin/eye_of_tyr"] = "Eye of Tyr"
L["defaultRotation/paladin/greater_blessing_of_kings"] = "Greater Blessing of Kings"
L["defaultRotation/paladin/greater_blessing_of_wisdom"] = "Greater Blessing of Wisdom"
L["defaultRotation/paladin/hammer_of_justice"] = "Hammer of Justice"
L["defaultRotation/paladin/hammer_of_the_righteous"] = "Hammer of the Righteous"
L["defaultRotation/paladin/hand_of_the_protector"] = "Hand of the Protector"
L["defaultRotation/paladin/holy"] = "Holy 7.1.5"
L["defaultRotation/paladin/holy_multi"] = "Holy Multi 7.1.5"
L["defaultRotation/paladin/holy_prism"] = "Holy Prism"
L["defaultRotation/paladin/holy_shock"] = "Holy Shock"
L["defaultRotation/paladin/holy_wrath"] = "Holy Wrath"
L["defaultRotation/paladin/judgment"] = "Judgment"
L["defaultRotation/paladin/judgment_execution_sentence"] = "Judgment (Execution Sentence)"
L["defaultRotation/paladin/justicar_vengeance"] = "Justicar's Vengeance"
L["defaultRotation/paladin/lay_on_hands"] = "Lay on Hands"
L["defaultRotation/paladin/light_of_the_protector"] = "Light of the Protector"
L["defaultRotation/paladin/protection"] = "Protection 7.1.5"
L["defaultRotation/paladin/protection_multi"] = "Protection Multi 7.1.5"
L["defaultRotation/paladin/rebuke"] = "Rebuke"
L["defaultRotation/paladin/retribution"] = "Retribution 7.1.5"
L["defaultRotation/paladin/retribution_multi"] = "Retribution Multi 7.1.5"
L["defaultRotation/paladin/shield_of_the_righteous"] = "Shield of the Righteous"
L["defaultRotation/paladin/templar_verdict"] = "Templar's Verdict"
L["defaultRotation/paladin/wake_of_ashes"] = "Wake of Ashes"
L["defaultRotation/paladin/word_of_glory"] = "Word of Glory"
L["defaultRotation/paladin/zeal"] = "Zeal"
L["defaultRotation/priest/desperate_prayer"] = "Desperate Prayer"
L["defaultRotation/priest/discipline"] = "Discipline 7.1.5"
L["defaultRotation/priest/discipline_multi"] = "Discipline Multi 7.1.5"
L["defaultRotation/priest/dispel_magic"] = "Dispel Magic"
L["defaultRotation/priest/divine_star"] = "Divine Star"
L["defaultRotation/priest/flash_heal"] = "Flash Heal"
L["defaultRotation/priest/halo"] = "Halo"
L["defaultRotation/priest/holy"] = "Holy 7.1.5"
L["defaultRotation/priest/holy_fire"] = "Holy Fire"
L["defaultRotation/priest/holy_multi"] = "Holy Multi 7.1.5"
L["defaultRotation/priest/holy_nova"] = "Holy Nova"
L["defaultRotation/priest/holy_word_chastise"] = "Holy Word: Chastise"
L["defaultRotation/priest/light_wrath"] = "Light's Wrath"
L["defaultRotation/priest/light_wrath_atonement"] = "Light's Wrath (Atonement 10+)"
L["defaultRotation/priest/mind_blast"] = "Mind Blast"
L["defaultRotation/priest/mind_flay"] = "Mind Flay"
L["defaultRotation/priest/mindbender"] = "Mindbender"
L["defaultRotation/priest/penance"] = "Penance"
L["defaultRotation/priest/power_infusion"] = "Power Infusion"
L["defaultRotation/priest/purge_the_wicked"] = "Purge the Wicked"
L["defaultRotation/priest/schism"] = "Schism"
L["defaultRotation/priest/shadow"] = "Shadow 7.1.5"
L["defaultRotation/priest/shadow_crash"] = "Shadow Crash"
L["defaultRotation/priest/shadow_multi"] = "Shadow Multi 7.1.5"
L["defaultRotation/priest/shadow_word_death"] = "Shadow Word: Death"
L["defaultRotation/priest/shadow_word_death_2_charges"] = "Shadow Word: Death (2 Charges)"
L["defaultRotation/priest/shadow_word_pain"] = "Shadow Word: Pain"
L["defaultRotation/priest/shadow_word_pain_void_eruption"] = "Shadow Word: Pain (Void Eruption)"
L["defaultRotation/priest/shadow_word_solace"] = "Shadow Word: Solace"
L["defaultRotation/priest/shadow_word_void"] = "Shadow Word: Void"
L["defaultRotation/priest/shadowfiend"] = "Shadowfiend"
L["defaultRotation/priest/shadowform"] = "Shadowform"
L["defaultRotation/priest/silence"] = "Silence"
L["defaultRotation/priest/smite"] = "Smite"
L["defaultRotation/priest/surrender_to_madness"] = "Surrender to Madness"
L["defaultRotation/priest/vampiric_touch"] = "Vampiric Touch"
L["defaultRotation/priest/vampiric_touch_misery"] = "Vampiric Touch (Misery)"
L["defaultRotation/priest/vampiric_touch_void_eruption"] = "Vampiric Touch (Void Eruption)"
L["defaultRotation/priest/vampiric_touch_void_eruption_misery"] = "Vampiric Touch (Void Eruption (Misery))"
L["defaultRotation/priest/void_bolt"] = "Void Bolt"
L["defaultRotation/priest/void_eruption"] = "Void Eruption"
L["defaultRotation/priest/void_eruption_legacy_of_the_void"] = "Void Eruption (Legacy of the Void)"
L["defaultRotation/priest/void_torrent"] = "Void Torrent"
L["defaultRotation/rogue/adrenaline_rush"] = "Adrenaline Rush"
L["defaultRotation/rogue/agonizing_poison"] = "Agonizing poison"
L["defaultRotation/rogue/ambush"] = "Ambush"
L["defaultRotation/rogue/assassination"] = "Assassination 7.1.5"
L["defaultRotation/rogue/assassination_multi"] = "Assassination Multi 7.1.5"
L["defaultRotation/rogue/backstab"] = "Backstab"
L["defaultRotation/rogue/backstab_anticipation"] = "Backstab (Anticipation)"
L["defaultRotation/rogue/backstab_deeper_stratagem"] = "Backstab (Deeper Stratagem)"
L["defaultRotation/rogue/between_the_eyes"] = "Between the Eyes"
L["defaultRotation/rogue/between_the_eyes_deeper_stratagem"] = "Between the Eyes (Deeper Stratagem)"
L["defaultRotation/rogue/blade_flurry"] = "Blade Flurry"
L["defaultRotation/rogue/cannonball_barrage"] = "Cannonball Barrage"
L["defaultRotation/rogue/crimson_vial"] = "Crimson Vial"
L["defaultRotation/rogue/crimson_vial_iron_stomach"] = "Crimson Vial (Iron Stomach)"
L["defaultRotation/rogue/curse_of_the_dreadblades"] = "Curse of the Dreadblades"
L["defaultRotation/rogue/deadly_poison"] = "Deadly Poison"
L["defaultRotation/rogue/death_from_above"] = "Death from Above"
L["defaultRotation/rogue/death_from_above_deeper_stratagem"] = "Death from Above (Deeper Stratagem)"
L["defaultRotation/rogue/enveloping_shadows"] = "Enveloping shadows"
L["defaultRotation/rogue/enveloping_shadows_deeper_stratagem"] = "Enveloping shadows (Deeper Stratagem)"
L["defaultRotation/rogue/envenom"] = "Envenom"
L["defaultRotation/rogue/envenom_deeper_stratagem"] = "Envenom (Deeper Stratagem)"
L["defaultRotation/rogue/eviscerate"] = "Eviscerate"
L["defaultRotation/rogue/eviscerate_deeper_stratagem"] = "Eviscerate (Deeper Stratagem)"
L["defaultRotation/rogue/exsanguinate"] = "Exsanguinate"
L["defaultRotation/rogue/fan_of_knives"] = "Fan of Knives"
L["defaultRotation/rogue/garrote"] = "Garrote"
L["defaultRotation/rogue/garrote_deeper_stratagem"] = "Garrote (Deeper Stratagem)"
L["defaultRotation/rogue/garrote_stealth"] = "Garrote (Stealth)"
L["defaultRotation/rogue/ghostly_strike"] = "Ghostly strike"
L["defaultRotation/rogue/ghostly_strike_anticipation"] = "Ghostly strike (Anticipation)"
L["defaultRotation/rogue/ghostly_strike_deeper_stratagem"] = "Ghostly strike (Deeper Stratagem)"
L["defaultRotation/rogue/goremaw_s_bite"] = "Goremaw's Bite"
L["defaultRotation/rogue/hemorrhage"] = "Hemorrhage"
L["defaultRotation/rogue/kick"] = "Kick"
L["defaultRotation/rogue/killing_spree"] = "Killing Spree"
L["defaultRotation/rogue/kingsbane"] = "Kingsbane"
L["defaultRotation/rogue/leeching_poison"] = "Leeching Poison"
L["defaultRotation/rogue/marked_for_death"] = "Marked for Death"
L["defaultRotation/rogue/marked_for_death_anticipation"] = "Marked for Death (Anticipation)"
L["defaultRotation/rogue/marked_for_death_deeper_stratagem"] = "Marked for Death (Deeper Stratagem)"
L["defaultRotation/rogue/mutilate"] = "Mutilate"
L["defaultRotation/rogue/mutilate_deeper_stratagem"] = "Mutilate (Deeper Stratagem)"
L["defaultRotation/rogue/nightblade"] = "Nightblade"
L["defaultRotation/rogue/nightblade_deeper_stratagem"] = "Nightblade (Deeper Stratagem)"
L["defaultRotation/rogue/outlaw"] = "Outlaw 7.1.5"
L["defaultRotation/rogue/outlaw_multi"] = "Outlaw Multi 7.1.5"
L["defaultRotation/rogue/pistol_shot"] = "Pistol Shot"
L["defaultRotation/rogue/pistol_shot_anticipation"] = "Pistol Shot (Anticipation)"
L["defaultRotation/rogue/pistol_shot_deeper_stratagem"] = "Pistol Shot (Deeper Stratagem)"
L["defaultRotation/rogue/pistol_shot_quick_draw"] = "Pistol Shot (Quick Draw)"
L["defaultRotation/rogue/pistol_shot_quick_draw_anticipation"] = "Pistol Shot (Quick Draw (Anticipation))"
L["defaultRotation/rogue/pistol_shot_quick_draw_deeper_stratagem"] = "Pistol Shot (Quick Draw (Deeper Stratagem))"
L["defaultRotation/rogue/roll_the_bones"] = "Roll the Bones"
L["defaultRotation/rogue/roll_the_bones_deeper_stratagem"] = "Roll the Bones (Deeper Stratagem)"
L["defaultRotation/rogue/run_through"] = "Run Through"
L["defaultRotation/rogue/run_through_deeper_stratagem"] = "Run Through (Deeper Stratagem)"
L["defaultRotation/rogue/rupture"] = "Rupture"
L["defaultRotation/rogue/rupture_deeper_stratagem"] = "Rupture (Deeper Stratagem)"
L["defaultRotation/rogue/saber_slash"] = "Saber Slash"
L["defaultRotation/rogue/shadow_blades"] = "Shadow Blades"
L["defaultRotation/rogue/shadow_dance"] = "Shadow Dance"
L["defaultRotation/rogue/shadow_dance_symbols_of_death"] = "Shadow Dance (Symbols of Death)"
L["defaultRotation/rogue/shadowstrikes"] = "Shadowstrikes"
L["defaultRotation/rogue/shadowstrikes_premeditation"] = "Shadowstrikes (Premeditation)"
L["defaultRotation/rogue/shuriken_storm"] = "Shuriken Storm"
L["defaultRotation/rogue/subtlety"] = "Subtlety 7.1.5"
L["defaultRotation/rogue/subtlety_multi"] = "Subtlety Multi 7.1.5"
L["defaultRotation/rogue/symbols_of_death"] = "Symbols of Death"
L["defaultRotation/rogue/vendetta"] = "Vendetta"
L["defaultRotation/shaman/ascendance"] = "Ascendance"
L["defaultRotation/shaman/boulderfist"] = "Boulderfist"
L["defaultRotation/shaman/boulderfist_2_charges"] = "Boulderfist (2 Charges)"
L["defaultRotation/shaman/boulderfist_landslide"] = "Boulderfist (Landslide)"
L["defaultRotation/shaman/chain_lightning"] = "Chain Lightning"
L["defaultRotation/shaman/cloudburst_totem"] = "Cloudburst Totem"
L["defaultRotation/shaman/crash_lightning"] = "Crash Ligntning"
L["defaultRotation/shaman/doom_winds"] = "Doom Winds"
L["defaultRotation/shaman/earth_shock"] = "Earth Shock"
L["defaultRotation/shaman/earthen_spike"] = "Earthen Spike"
L["defaultRotation/shaman/earthquake"] = "Earthquake"
L["defaultRotation/shaman/elemental"] = "Elemental 7.1.5"
L["defaultRotation/shaman/elemental_blast"] = "Elemental Blast"
L["defaultRotation/shaman/elemental_mastery"] = "Elemental Mastery"
L["defaultRotation/shaman/elemental_multi"] = "Elemental Multi 7.1.5"
L["defaultRotation/shaman/enhancement"] = "Enhancement 7.1.5"
L["defaultRotation/shaman/enhancement_multi"] = "Enhancement Multi 7.1.5"
L["defaultRotation/shaman/feral_lunge"] = "Feral Lunge"
L["defaultRotation/shaman/feral_spirit"] = "Feral Spirit"
L["defaultRotation/shaman/fire_elemental"] = "Fire Elemental"
L["defaultRotation/shaman/flame_shock"] = "Flame Shock"
L["defaultRotation/shaman/flame_shock_elemental_focus"] = "Flame Shock (Elemental Focus)"
L["defaultRotation/shaman/flametongue"] = "Flametongue"
L["defaultRotation/shaman/frost_shock"] = "Frost Shock"
L["defaultRotation/shaman/frostbrand"] = "Frostbrand"
L["defaultRotation/shaman/fury_of_air"] = "Fury of Air"
L["defaultRotation/shaman/healing_rain"] = "Healing Rain"
L["defaultRotation/shaman/healing_stream_totem"] = "Healing Steam Totem"
L["defaultRotation/shaman/icefury"] = "Icefury"
L["defaultRotation/shaman/lava_burst"] = "Lava Burst"
L["defaultRotation/shaman/lava_burst_echo_of_the_elements"] = "Lava Burst (Echo of the Elements)"
L["defaultRotation/shaman/lava_burst_lava_surge"] = "Lava Burst (Lava Surge)"
L["defaultRotation/shaman/lava_lash"] = "Lava Lash"
L["defaultRotation/shaman/lava_lash_hot_hand"] = "Lava Lash (Hot Hand)"
L["defaultRotation/shaman/lightning_bolt"] = "Lightning Bolt"
L["defaultRotation/shaman/lightning_bolt_overcharge"] = "Lightning Bolt (Overcharge)"
L["defaultRotation/shaman/lightning_bolt_power_of_the_maelstrom"] = "Lightning Bolt (Power of the Maelstrom)"
L["defaultRotation/shaman/lightning_shield"] = "Lightning Shield"
L["defaultRotation/shaman/liquid_magma_totem"] = "Liquid Magma Totem"
L["defaultRotation/shaman/purge"] = "Purge"
L["defaultRotation/shaman/rainfall"] = "Rainfall"
L["defaultRotation/shaman/restoration"] = "Restoration 7.1.5"
L["defaultRotation/shaman/restoration_multi"] = "Restoration Multi 7.1.5"
L["defaultRotation/shaman/rockbiter"] = "Rockbiter"
L["defaultRotation/shaman/rockbiter_landslide"] = "Rockbiter (Landslide)"
L["defaultRotation/shaman/stormkeeper"] = "Stormkeeper"
L["defaultRotation/shaman/stormstrike"] = "Stormstrike"
L["defaultRotation/shaman/stormstrike_stormbringer"] = "Stormstrike (Stormbringer)"
L["defaultRotation/shaman/sundering"] = "Sundering"
L["defaultRotation/shaman/totem_mastery"] = "Totem Mastery"
L["defaultRotation/shaman/wind_shear"] = "Wind Shear"
L["defaultRotation/shaman/windsong"] = "Windsong"
L["defaultRotation/warlock/affliction"] = "Affliction 7.1.5"
L["defaultRotation/warlock/affliction_multi"] = "Affliction Multi 7.1.5"
L["defaultRotation/warlock/agony"] = "Agony"
L["defaultRotation/warlock/call_dreadstalkers"] = "Call Dreadstalkers"
L["defaultRotation/warlock/cataclysm"] = "Cataclysm"
L["defaultRotation/warlock/cauterize_master"] = "Cauterize Master"
L["defaultRotation/warlock/channel_demonfire"] = "Channel Demonfire"
L["defaultRotation/warlock/chaos_bolt"] = "Choas Bolt"
L["defaultRotation/warlock/chaos_bolt_5_soul_shards"] = "Choas Bolt (5 Soul Shards)"
L["defaultRotation/warlock/conflagrate"] = "Conflagrate"
L["defaultRotation/warlock/conflagrate_roaring_blaze"] = "Conflagrate (Roaring Blaze)"
L["defaultRotation/warlock/corruption"] = "Corruption"
L["defaultRotation/warlock/corruption_absolute_corruption"] = "Corruption (Absolute Corruption)"
L["defaultRotation/warlock/demonic_empowerment"] = "Demonic Empowerment"
L["defaultRotation/warlock/demonic_empowerment_call_dreadstalkers"] = "Demonic Empowerment (Call Dreadstalkers)"
L["defaultRotation/warlock/demonic_empowerment_grimoire_felguard"] = "Demonic Empowerment (Grimoire: Felguard)"
L["defaultRotation/warlock/demonic_empowerment_hand_of_guldan"] = "Demonic Empowerment (Hand of Gul'dan)"
L["defaultRotation/warlock/demonic_empowerment_summon_darkglare"] = "Demonic Empowerment (Summon Darkglare)"
L["defaultRotation/warlock/demonic_empowerment_summon_doomguard"] = "Demonic Empowerment (Summon Doomguard)"
L["defaultRotation/warlock/demonic_empowerment_summon_infernal"] = "Demonic Empowerment (Summon Infernal)"
L["defaultRotation/warlock/demonology"] = "Demonology 7.1.5"
L["defaultRotation/warlock/demonology_multi"] = "Demonology Multi 7.1.5"
L["defaultRotation/warlock/demonwrath"] = "Demonwrath"
L["defaultRotation/warlock/demonwrath_moving"] = "Demonwrath (Moving)"
L["defaultRotation/warlock/destruction"] = "Destruction 7.1.5"
L["defaultRotation/warlock/destruction_multi"] = "Destruction Multi 7.1.5"
L["defaultRotation/warlock/dimensional_rift"] = "Dimensional Rift"
L["defaultRotation/warlock/doom"] = "Doom"
L["defaultRotation/warlock/drain_life"] = "Drain Life"
L["defaultRotation/warlock/drain_soul"] = "Drain Soul"
L["defaultRotation/warlock/felstorm"] = "Felstorm"
L["defaultRotation/warlock/grimoire_felguard"] = "Grimoire: Felguard"
L["defaultRotation/warlock/grimoire_felhunter"] = "Grimoire: Felhunter"
L["defaultRotation/warlock/grimoire_imp"] = "Grimoire: Imp"
L["defaultRotation/warlock/grimoire_of_sacrifice"] = "Grimoire of Sacrifice"
L["defaultRotation/warlock/hand_of_guldan"] = "Hand of Gul'dan"
L["defaultRotation/warlock/haunt"] = "Haunt"
L["defaultRotation/warlock/immolate"] = "Immolate"
L["defaultRotation/warlock/implosion"] = "Implosion"
L["defaultRotation/warlock/incinerate"] = "Incinerate"
L["defaultRotation/warlock/life_tap"] = "Life Tap"
L["defaultRotation/warlock/life_tap_empowered_life_tap"] = "Life Tap (Empowered Life Tap)"
L["defaultRotation/warlock/mortal_coil"] = "Mortal Coil"
L["defaultRotation/warlock/phantom_singularity"] = "Phantom Singularity"
L["defaultRotation/warlock/rain_of_fire"] = "Rain of Fire"
L["defaultRotation/warlock/rain_of_fire_5_sould_shards"] = "Rain of Fire (5 Soul Shards)"
L["defaultRotation/warlock/reap_souls"] = "Reap Souls"
L["defaultRotation/warlock/seed_of_corruption"] = "Seed of Corruption"
L["defaultRotation/warlock/shadow_bolt"] = "Shadow Bolt"
L["defaultRotation/warlock/shadow_bolt_shadowy_inspiration"] = "Shadow Bolt (Shadowy Inspiration)"
L["defaultRotation/warlock/shadow_lock"] = "Shadow Lock"
L["defaultRotation/warlock/shadowburn"] = "Shadowburn"
L["defaultRotation/warlock/shadowflame"] = "Shadowflame"
L["defaultRotation/warlock/siphon_life"] = "Siphon Life"
L["defaultRotation/warlock/soul_effigy"] = "Soul Effigy"
L["defaultRotation/warlock/soul_harvest"] = "Soul Harvest"
L["defaultRotation/warlock/spell_lock"] = "Spell Lock"
L["defaultRotation/warlock/summon_darkglare"] = "Summon Darkglare"
L["defaultRotation/warlock/summon_doomguard"] = "Summon Doomguard"
L["defaultRotation/warlock/summon_doomguard_grimoire_of_supremacy"] = "Summon Doomguard (Grimoire of Supremacy)"
L["defaultRotation/warlock/summon_felguard"] = "Summon Felguard"
L["defaultRotation/warlock/summon_felhunter"] = "Summon Felhunter"
L["defaultRotation/warlock/summon_imp"] = "Summon Imp"
L["defaultRotation/warlock/summon_infernal"] = "Summon Infernal"
L["defaultRotation/warlock/summon_infernal_grimoire_of_supremacy"] = "Summon Infernal (Grimoire of Supremacy)"
L["defaultRotation/warlock/thalkiel_consumption"] = "Thal'Kiels Consumption"
L["defaultRotation/warlock/unstable_affliction"] = "Unstable Affliction"
L["defaultRotation/warlock/unstable_affliction_3+_soul_shards"] = "Unstable Affliction (3+ Soul Shards)"
L["defaultRotation/warlock/unstable_affliction_contagion"] = "Unstable Affliction (Contagion)"
L["defaultRotation/warlock/unstable_affliction_second"] = "Unstable Affliction (Second)"
L["defaultRotation/warrior/arms"] = "Arms 7.1.5"
L["defaultRotation/warrior/arms_multi"] = "Arms Multi 7.1.5"
L["defaultRotation/warrior/avatar"] = "Avatar"
L["defaultRotation/warrior/battle_cry"] = "Battle Cry"
L["defaultRotation/warrior/battle_cry_avatar"] = "Battle Cry (Avatar)"
L["defaultRotation/warrior/battle_cry_ravager"] = "Battle Cry (Ravager)"
L["defaultRotation/warrior/battle_cry_reckless_abandon"] = "Battle Cry (Reckless Abandon)"
L["defaultRotation/warrior/battle_cry_renewed_fury"] = "Battle Cry (Renewed Fury)"
L["defaultRotation/warrior/berserker_rage"] = "Berserker Rage"
L["defaultRotation/warrior/bladestorm"] = "Bladestorm"
L["defaultRotation/warrior/bloodbath"] = "Bloodbath"
L["defaultRotation/warrior/bloodthirst"] = "Bloodthrist"
L["defaultRotation/warrior/bloodthirst_enrage"] = "Bloodthrist (Enrage)"
L["defaultRotation/warrior/charge"] = "Charge"
L["defaultRotation/warrior/cleave"] = "Cleave"
L["defaultRotation/warrior/colossus_smash"] = "Colossus Smash"
L["defaultRotation/warrior/devastate"] = "Devastate"
L["defaultRotation/warrior/dragon_roar"] = "Dragon Roar"
L["defaultRotation/warrior/dragon_roar_berserker_rage"] = "Dragon Roar (Berserker Rage)"
L["defaultRotation/warrior/dragon_roar_rampage"] = "Dragon Roar (Rampage)"
L["defaultRotation/warrior/dragon_roar_rampage_carnage"] = "Dragon Roar (Rampage (Carnage))"
L["defaultRotation/warrior/dragon_roar_rampage_massacre"] = "Dragon Roar (Rampage (Massacre))"
L["defaultRotation/warrior/dragon_roar_rampage_rage"] = "Dragon Roar (Rampage (Rage))"
L["defaultRotation/warrior/execute"] = "Execute"
L["defaultRotation/warrior/execute_massacre"] = "Execute (Massacre)"
L["defaultRotation/warrior/execute_massacre_enrage"] = "Execute (Massacre (Enrage))"
L["defaultRotation/warrior/focused_rage"] = "Focused Rage"
L["defaultRotation/warrior/focused_rage_colossus_smash"] = "Focused Rage (Colossus Smash)"
L["defaultRotation/warrior/focused_rage_deadly_calm"] = "Rage concentrée (Deadly Calm)"
L["defaultRotation/warrior/furious_slash"] = "Furious Slash"
L["defaultRotation/warrior/furious_slash_frenzy"] = "Furious Slash (Frenzy)"
L["defaultRotation/warrior/fury"] = "Fury 7.1.5"
L["defaultRotation/warrior/fury_multi"] = "Fury Multi 7.1.5"
L["defaultRotation/warrior/ignore_pain"] = "Ignore Pain"
L["defaultRotation/warrior/ignore_pain_vengeance"] = "Ignore Pain (Vengeance)"
L["defaultRotation/warrior/impending_victory"] = "Impending Victory"
L["defaultRotation/warrior/intercept"] = "Intercept"
L["defaultRotation/warrior/mortal_strike"] = "Mortal Strike"
L["defaultRotation/warrior/neltharion_fury"] = "Neltharion's Fury"
L["defaultRotation/warrior/odyn_fury"] = "Odyn's Fury"
L["defaultRotation/warrior/overpower"] = "Overpower"
L["defaultRotation/warrior/overpower_focused_rage"] = "Overpower (Focused Rage)"
L["defaultRotation/warrior/protection"] = "Protection 7.1.5"
L["defaultRotation/warrior/protection_multi"] = "Protection Multi 7.1.5"
L["defaultRotation/warrior/pummel"] = "Pummel"
L["defaultRotation/warrior/raging_blow"] = "Raging Blow"
L["defaultRotation/warrior/raging_blow_inner_rage"] = "Raging Blow (Inner Rage)"
L["defaultRotation/warrior/rampage"] = "Rampage"
L["defaultRotation/warrior/rampage_massacre"] = "Rampage (Massacre)"
L["defaultRotation/warrior/rampage_rage"] = "Rampage (Rage)"
L["defaultRotation/warrior/ravager"] = "Ravager"
L["defaultRotation/warrior/rend"] = "Rend"
L["defaultRotation/warrior/revenge"] = "Revenge"
L["defaultRotation/warrior/revenge_vengeance"] = "Revenge (Vengeance)"
L["defaultRotation/warrior/shield_block"] = "Shield Block"
L["defaultRotation/warrior/shield_slam"] = "Shield Slam"
L["defaultRotation/warrior/slam"] = "Slam"
L["defaultRotation/warrior/slam_focused_rage"] = "Slam (Focused Rage)"
L["defaultRotation/warrior/thunder_clap"] = "Thunder Clap"
L["defaultRotation/warrior/victory_rush"] = "Victory Rush"
L["defaultRotation/warrior/warbreaker"] = "Warbreaker"
L["defaultRotation/warrior/whirlwind"] = "Whirlwind"
L["defaultRotation/warrior/whirlwind_focused_rage"] = "Whirlwind (Focused Rage)"
L["defaultRotation/warrior/whirlwind_meat_cleaver"] = "Whirlwind (Meat Cleaver)"
L["message/core/fullCleanUp"] = "We have cleaned your RotationBuilder data with this new revision. This was need because ever your installation was too old and some error could have occured, or a new functionality needed it."
L["msg/action/keybinds/customCase/disabled"] = "Disable custom case: "
L["msg/action/keybinds/customCase/enabled"] = "Enable custom case: "
L["msg/action/keybinds/multiTarget/disabled"] = "Multi-target mode disabled"
L["msg/action/keybinds/multiTarget/enabled"] = "Multi-target mode enabled"
L["msg/action/switch_rotation"] = "Switch rotation to: "
L["ROB_ACTION_MOVEDOWN_TT"] = "Move selected action down one position"
L["ROB_ACTION_MOVEUP_TT"] = "Move selected action up one position"
L["ROB_ACTION_REMOVE_TT"] = "Remove action from list"
L["ROB_ADDON_NAME"] = "RotationBuilder"
L["ROB_AO_G_HasMinRangeCheckButton"] = "Spell has a minimum range"
L["ROB_AO_G_HasMinRangeCheckButton_TT"] = "Only display this action if the player's target is farther than 8 yards"
L["ROB_AO_G_SpellInRangeCheckButton"] = "Target in range"
L["ROB_AO_G_SpellInRangeCheckButton_TT"] = "Only display this action if the player's target is in this spell's range"
L["ROB_FRAME_CLOSE_TT"] = "Close Rotation Builder Window"
L["ROB_FRAME_OPTIONS_TT"] = "Show Options"
L["ROB_FRAME_ROTATIONS_TT"] = "Show Rotations"
L["ROB_LOADED"] = "Rotation Builder v%s loaded"
L["ROB_OPTION_ENEMY"] = "Target is hostile or neutral"
L["ROB_OPTION_ENEMY_TT"] = "Only display the icons if the target is hostile or neutral"
L["ROB_OPTION_EXPORTBINDS"] = "Export binds"
L["ROB_OPTION_EXPORTBINDS_TT"] = "Export action key binds with export"
L["ROB_OPTION_HIDECD"] = "Hide Cooldowns"
L["ROB_OPTION_HIDECD_TT"] = "Hide the cooldown clock and flashing animations"
L["ROB_OPTION_ICONS"] = "Icon Options:"
L["ROB_OPTION_ICONS_C_A"] = "Current Action Transparency:"
L["ROB_OPTION_ICONS_CV"] = "1"
L["ROB_OPTION_ICONS_MAX"] = "3.5"
L["ROB_OPTION_ICONS_MIN"] = ".1"
L["ROB_OPTION_ICONS_N_A"] = "Next Action Transparency:"
L["ROB_OPTION_ICONS_T_A"] = "Toggle Icons Transparency:"
L["ROB_OPTION_ICONS_T_ATT"] = [=[Enter the transparency level for the icon
 |cFF00FF00.1|r to |cFF00FF00 1|r
|cFF00FF00 1|r is fully visible
|cFF00FF00 .1|r is near invisible]=]
L["ROB_OPTION_ICONSCALE"] = "Icon Scale:"
L["ROB_OPTION_IMPORT"] = "Import / Export Options:"
L["ROB_OPTION_LOADDEFAULT"] = "LOAD"
L["ROB_OPTION_LOADDEFAULT_TT"] = "Load default rotations for your class"
L["ROB_OPTION_LOCKICONS"] = "Lock icons"
L["ROB_OPTION_LOCKICONS_TT"] = "Lock icons to prevent movement"
L["ROB_OPTION_MINIMAP"] = "Minimap button:"
L["ROB_OPTION_MINIMAP_TT"] = "Toggle Minimap Button"
L["ROB_OPTION_MINIMAPO"] = "Minimap Options:"
L["ROB_OPTION_MINIMAPPOS"] = "Position Around Minimap"
L["ROB_OPTION_MINIMAPRAD"] = "Radius Outside Minimap"
L["ROB_OPTION_MMPOS_CV"] = "300"
L["ROB_OPTION_MMPOS_MAX"] = "360"
L["ROB_OPTION_MMPOS_MIN"] = "1"
L["ROB_OPTION_MMRAD_CV"] = "80"
L["ROB_OPTION_MMRAD_MAX"] = "120"
L["ROB_OPTION_MMRAD_MIN"] = "1"
L["ROB_OPTION_NAIL"] = "Next Action Location:"
L["ROB_OPTION_OVERWRITE"] = "Overwrite"
L["ROB_OPTION_OVERWRITE_TT"] = "Allow importing rotations to overwrite existing rotations"
L["ROB_OPTION_RESETUI"] = "Reset UI"
L["ROB_OPTION_RESETUI_EXP"] = "Reset all UI windows to center of screen"
L["ROB_OPTION_RESETUI_TT"] = "Reset UI Window Locations"
L["ROB_OPTION_UI"] = "UI Options:"
L["ROB_OPTION_UISCALE"] = "UI Scale"
L["ROB_OPTION_UISCALE_ADD"] = "+"
L["ROB_OPTION_UISCALE_MIN"] = "-"
L["ROB_OPTION_UPDATERATE"] = "Updates Per Second:"
L["ROB_OPTION_UPDATERATE_CV"] = "5"
L["ROB_OPTION_UPDATERATE_MAX"] = "10"
L["ROB_OPTION_UPDATERATE_MIN"] = "1"
L["ROB_PROMPT_LIST_DELETE"] = "Are you sure you want to delete?"
L["ROB_UI_A_ADD"] = "Add"
L["ROB_UI_A_ADD_TT"] = "Add new action to the rotation"
L["ROB_UI_A_COPY"] = "Copy"
L["ROB_UI_A_COPY_TT"] = "Copy the selected action to the clipboard"
L["ROB_UI_A_PASTE"] = "Paste"
L["ROB_UI_A_PASTE_TT"] = "Paste the copied action into the rotation"
L["ROB_UI_ACTION_COLUMN"] = "Actions"
L["ROB_UI_ADD_ACTION_CFAIL"] = "Action names can not use these characters [ ] , ="
L["ROB_UI_ADD_ROTATION_CFAIL"] = "Rotation names can not use these characters [ ] ,"
L["ROB_UI_AO_G_CHARGES"] = "Spell Charges:"
L["ROB_UI_AO_G_CHARGES_TT"] = [=[Check this option if this action has charges
This is used for calculating the next ready action]=]
L["ROB_UI_AO_G_CHARGESIB_TT"] = [=[Input the number of charges
Example: |cFF00FF001|r]=]
L["ROB_UI_AO_G_DEBUG"] = "Debug"
L["ROB_UI_AO_G_DEBUG_TT"] = "Turn on debug for this spell"
L["ROB_UI_AO_G_DISABLE"] = "Disable"
L["ROB_UI_AO_G_DISABLE_TT"] = "Temporarily disable this action so you dont have to delete it"
L["ROB_UI_AO_G_DURATION"] = "Wait to recast:"
L["ROB_UI_AO_G_DURATION_TT"] = [=[Wait specified seconds to display this action after you have casted it
Useful for giving air born spells time to land before calculating next action]=]
L["ROB_UI_AO_G_DURATIONIB_TT"] = "Input the number of seconds to wait before redisplaying action"
L["ROB_UI_AO_G_GSPELLCOST"] = "Cost Power:"
L["ROB_UI_AO_G_GSPELLCOST_TT"] = [=[Check this option if this action use a type of power
This is used for calculating the next ready action]=]
L["ROB_UI_AO_G_GSPELLCOST1_TT"] = [=[Input the type of power used
|cFF00FF000|r=MANA |cFF00FF001|r=RAGE |cFF00FF002|r=FOCUS |cFF00FF003|r=ENERGY  |cFF00FF004|r=COMBO POINTS |cFF00FF006|r=RUNIC POWER |cFF00FF007|r=SOUL SHARDS
|cFF00FF008|r=ASTRAL POWER |cFF00FF009|r=HOLY POWER |cFF00FF0011|r=MAELSTROM |cFF00FF0012|r=CHI |cFF00FF0013|r=INSANITY |cFF00FF0016|r=ARCANE POWER
|cFF00FF0017|r=FURY  |cFF00FF0018|r=PAIN]=]
L["ROB_UI_AO_G_GSPELLCOST2_TT"] = [=[Input the amount of power used
Example1: |cFF00FF003|r
Example2: |cFF00FF0090%|r]=]
L["ROB_UI_AO_G_GUNITPOWER"] = "Generates Power:"
L["ROB_UI_AO_G_GUNITPOWER_TT"] = [=[Check this option if this action generates a type of power
This is used for calculating the next ready action]=]
L["ROB_UI_AO_G_GUNITPOWER1_TT"] = [=[Input the type of power generated
|cFF00FF000|r=MANA |cFF00FF001|r=RAGE |cFF00FF002|r=FOCUS |cFF00FF003|r=ENERGY  |cFF00FF004|r=COMBO POINTS |cFF00FF006|r=RUNIC POWER |cFF00FF007|r=SOUL SHARDS
|cFF00FF008|r=ASTRAT POWER |cFF00FF009|r=HOLY POWER |cFF00FF0011|r=MAELSTROM |cFF00FF0012|r=CHI |cFF00FF0013|r=INSANITY |cFF00FF0016|r=ARCANE POWER
|cFF00FF0017|r=FURY  |cFF00FF0018|r=PAIN]=]
L["ROB_UI_AO_G_GUNITPOWER2_TT"] = [=[Input the amount of power generated
Example1: |cFF00FF003|r
Example2: |cFF00FF0090%|r]=]
L["ROB_UI_AO_G_HASPROC"] = "Has Proc"
L["ROB_UI_AO_G_HASPROC_TT"] = "Only display action when it has a proc"
L["ROB_UI_AO_G_ICON_L"] = "Icon:"
L["ROB_UI_AO_G_ICON_TT"] = [=[Input the spell name or spell id of the icon you want to display for this action
If left blank the spellname will be used]=]
L["ROB_UI_AO_G_INCOMBAT"] = "In combat"
L["ROB_UI_AO_G_INCOMBAT_TT"] = "Only display this action if player is in combat"
L["ROB_UI_AO_G_LASTCAST"] = "Last casted:"
L["ROB_UI_AO_G_LASTCAST_TT"] = "Only display action if the last casted spell was this"
L["ROB_UI_AO_G_LASTCASTIB_TT"] = "Input the name of the last casted spell to check"
L["ROB_UI_AO_G_MAXCASTS"] = "Max sequential casts:"
L["ROB_UI_AO_G_MAXCASTS_TT"] = "Only display this action specified sequential times"
L["ROB_UI_AO_G_MAXCASTSIB_TT"] = "Input the number of casts allowed in succession"
L["ROB_UI_AO_G_MOVING"] = "Moving"
L["ROB_UI_AO_G_MOVING_TT"] = "Only display this action if player is moving"
L["ROB_UI_AO_G_NMOVING"] = "Not Moving"
L["ROB_UI_AO_G_NMOVING_TT"] = "Only display this action if player is not moving"
L["ROB_UI_AO_G_NOTINCOMBAT"] = "Not in combat"
L["ROB_UI_AO_G_NOTINCOMBAT_TT"] = "Only display this action if player is not in combat"
L["ROB_UI_AO_G_NOTINSPELLBOOK"] = "Not a character spell"
L["ROB_UI_AO_G_NOTINSPELLBOOK_TT"] = [=[Only display this action if the spell is not one of your character spell
Example : If it is one of your familiar spell (hunter's pet, warlock's demon, mage's water elemental, ...]=]
L["ROB_UI_AO_G_NOTSPELL"] = "Not a spell"
L["ROB_UI_AO_G_NOTSPELL_TT"] = [=[Ignore spell mana type checks and just use the keybind to perform the action
Check this when spellname=Trinket0Slot or HandsSlot]=]
L["ROB_UI_AO_G_OTHERCD"] = "Check other cooldown:"
L["ROB_UI_AO_G_OTHERCD_TT"] = "Only display this action when other cooldown specified passes check"
L["ROB_UI_AO_G_OTHERCDNIB_TT"] = "Input the name or spell id of the other cooldown to check"
L["ROB_UI_AO_G_OTHERCDVIB_TT"] = [=[Input the value of the other cooldown to check
Example1: |cFF00FF00<3|r means only display action when other action has less than 3 seconds left
Example2: |cFF00FF00>3|r means only display action when other action has more than 3 seconds left
Example3: |cFF00FF00<=3|r means only display action when other action has less than or equal to 3 seconds left
Example4: |cFF00FF00=3|r means only display this action when other action has exactly 3 seconds left]=]
L["ROB_UI_AO_G_OTHERCHARGES"] = "Other Spell Charges:"
L["ROB_UI_AO_G_OTHERCHARGES_TT"] = [=[Check this option if you want to check another spell charges
This is used for calculating the next ready action]=]
L["ROB_UI_AO_G_OTHERCHARGESNIB_TT"] = "Input the spell name or spell id of which you want to check the charges"
L["ROB_UI_AO_G_SID_VFAIL"] = "Spell or Slot not found"
L["ROB_UI_AO_G_SPELLNAME_L"] = "Spell ID/Name:"
L["ROB_UI_AO_G_SPELLNAME_TT"] = [=[Input the spell id/name or inventory slot
Example1: |cFF00FF00Trinket0Slot|r for first trinket slot
Example2: |cFF00FF00Trinket1Slot|r for second trinket slot
Example3: |cFF00FF00HandsSlot|r
Example4: |cFF00FF00Growl|r
Example5: |cFF00FF002649|r id for Growl]=]
L["ROB_UI_AO_GENERAL_LABEL"] = "General Options:"
L["ROB_UI_AO_GENERAL_TAB"] = "General"
L["ROB_UI_AO_P_HAVEBUFF"] = "Have Buff:"
L["ROB_UI_AO_P_HAVEBUFF_TT"] = "Only display action when player has the specified buff or buffs"
L["ROB_UI_AO_P_HAVEBUFFIB_TT"] = [=[Input the name of the buff or buffs
Syntax: |cFF00FF00| |r= OR |cFF00FF00&|r = AND |cFF00FF00_|r = casted by player |cFF00FF00#|r = number of stacks |cFF00FF00^|r = refresh at seconds
Example1: |cFF00FF00Earth Shield#2|r display action when player has 2 stacks of Earth Shield
Example2: |cFF00FF00_Earth Shield#2|r display action when player has a player casted Earth Shield at 2 stacks
Example3: |cFF00FF00_Earth Shield#2^3|r display action when player has a player casted Earth Shield at 2 stacks with >=3 seconds left
Example4: |cFF00FF00Earth Shield||Inner Fire|r display action when player has Earth Shield or Inner Fire
Example5: |cFF00FF00Earth Shield&Inner Fire|r display action when player has both Earth Shield and Inner Fire]=]
L["ROB_UI_AO_P_HAVEDB"] = "Have Debuff:"
L["ROB_UI_AO_P_HAVEDB_TT"] = "Only display action when player has the specified debuff or debuffs"
L["ROB_UI_AO_P_HAVEDBIB_TT"] = [=[Input the name of the debuff or debuffs
Syntax: |cFF00FF00| |r= OR |cFF00FF00&|r = AND |cFF00FF00_|r = casted by player |cFF00FF00#|r = number of stacks |cFF00FF00^|r = refresh at seconds
Example1: |cFF00FF00Dark Plague#2|r display action when player has the debuff Dark Plague 2 stacks
Example2: |cFF00FF00_Dark Plague#2|r display action when player has a player casted Dark Plague at 2 stacks
Example3: |cFF00FF00_Dark Plague#2^3|r display action when player has a player casted Dark Plague at 2 stacks with >=3 seconds left
Example4: |cFF00FF00Dark Plague|Forbearance|r display action when player has Dark Plague or Forbearance debuffs
Example5: |cFF00FF00Dark Plague&Forbearance|r display action when player has both Dark Plague and Forbearance debuffs]=]
L["ROB_UI_AO_P_HP"] = "HP:"
L["ROB_UI_AO_P_HP_TT"] = "Only display action when player meets specified hit points"
L["ROB_UI_AO_P_HPIB_TT"] = [=[Input the percent of player hit points to check
Example1: |cFF00FF00<90%|r means only display this action when player is under 90% hitpoints
Example2: |cFF00FF00>90%|r means only display this action when player is over 90% hitpoints
Example3: |cFF00FF00<=90%|r means only display this action when player is under or equal to 90% hitpoints
Example4: |cFF00FF00>=90%|r means only display this action when player is over or equal to 90% hitpoints
Example5: |cFF00FF00=90%|r means only display this action when player is at exactly 90% hitpoints]=]
L["ROB_UI_AO_P_ISSTEALTHED"] = "Is stealthed"
L["ROB_UI_AO_P_ISSTEALTHED_TT"] = "Only display action when the player is stealthed"
L["ROB_UI_AO_P_KNOWNOTSPELL"] = "Do not know Spell"
L["ROB_UI_AO_P_KNOWNOTSPELL_TT"] = "Only display action when specified spell is unknown"
L["ROB_UI_AO_P_KNOWNOTSPELLIB_TT"] = "Input the spell name or spell id of the spell you want check"
L["ROB_UI_AO_P_KNOWSPELL"] = "Know Spell"
L["ROB_UI_AO_P_KNOWSPELL_TT"] = "Only display action when specified spell is known"
L["ROB_UI_AO_P_KNOWSPELLIB_TT"] = "Input the spell name or spell id of the spell you want check"
L["ROB_UI_AO_P_NEEDBUFF"] = "Need Buff:"
L["ROB_UI_AO_P_NEEDBUFF_TT"] = "Only display action when player needs specified buff or buffs"
L["ROB_UI_AO_P_NEEDBUFFIB_TT"] = [=[Input the name of the buff or buffs
Syntax: |cFF00FF00| |r= OR |cFF00FF00&|r = AND |cFF00FF00_|r = casted by player |cFF00FF00#|r = number of stacks |cFF00FF00^|r = refresh at seconds
Example1: |cFF00FF00Earth Shield#2|r display action when player is missing 2 stacks of Earth Shield
Example2: |cFF00FF00_Earth Shield#2|r display action when player is missing a player casted Earth Shield at 2 stacks
Example3: |cFF00FF00_Earth Shield#2^3|r display action when player is missing a player casted Earth Shield at 2 stacks with >=3 seconds left
Example4: |cFF00FF00Earth Shield||Inner Fire|r display action when player is missing Earth Shield or Inner Fire
Example5: |cFF00FF00Earth Shield&Inner Fire|r display action when player is missing both Earth Shield and Inner Fire]=]
L["ROB_UI_AO_P_NEEDDB"] = "Need Debuff:"
L["ROB_UI_AO_P_NEEDDB_TT"] = "Only display action when player is missing the specified debuff or debuffs"
L["ROB_UI_AO_P_NEEDDBIB_TT"] = [=[Input the name of the debuff or debuffs
Syntax: |cFF00FF00| |r= OR |cFF00FF00&|r = AND |cFF00FF00_|r = casted by player |cFF00FF00#|r = number of stacks |cFF00FF00^|r = refresh at seconds
Example1: |cFF00FF00Dark Plague#2|r display action when player is missing the debuff Dark Plague 2 stacks
Example2: |cFF00FF00_Dark Plague#2|r display action when player is missing a player casted Dark Plague at 2 stacks
Example3: |cFF00FF00_Dark Plague#2^3|r display action when player is missing a player casted Dark Plague at 2 stacks with >=3 seconds left
Example4: |cFF00FF00Dark Plague|Forbearance|r display action when player is missing Dark Plague or Forbearance debuffs
Example5: |cFF00FF00Dark Plague&Forbearance|r display action when player is missing both Dark Plague and Forbearance debuffs]=]
L["ROB_UI_AO_P_POWER"] = "Power:"
L["ROB_UI_AO_P_POWER_TT"] = "Only display action when player has the specified power"
L["ROB_UI_AO_P_POWER1_TT"] = [=[Input the type of unit power
|cFF00FF000|r=MANA |cFF00FF001|r=RAGE |cFF00FF002|r=FOCUS |cFF00FF003|r=ENERGY  |cFF00FF004|r=COMBO POINTS |cFF00FF006|r=RUNIC POWER |cFF00FF007|r=SOUL SHARDS
|cFF00FF008|r=ASTRAL POWER |cFF00FF009|r=HOLY POWER |cFF00FF0011|r=MAELSTROM |cFF00FF0012|r=CHI |cFF00FF0013|r=INSANITY |cFF00FF0016|r=ARCANE POWER
|cFF00FF0017|r=FURY  |cFF00FF0018|r=PAIN]=]
L["ROB_UI_AO_P_POWER2"] = "Power 2:"
L["ROB_UI_AO_P_POWER2_TT"] = [=[Input the amount of power required
Example1: |cFF00FF00>20|r
Example2: |cFF00FF00<=20|r
Example3: |cFF00FF00=20|r
Example4: |cFF00FF00<90%|r]=]
L["ROB_UI_AO_P_RUNES"] = "Runes:"
L["ROB_UI_AO_P_RUNES_TT"] = "Only display action when player has specified runes"
L["ROB_UI_AO_P_RUNESIB_TT"] = [=[Input the number of runes
Example1: |cFF00FF00>1|r means only display this action when player has more than 1 rune
Example2: |cFF00FF00<=1|r means only display this action when player has less than or equal to 1 rune
Example3: |cFF00FF00>=1|r means only display this action when player has 1 or more runes]=]
L["ROB_UI_AO_PET_HAVEBUFF"] = "Has Buff:"
L["ROB_UI_AO_PET_HAVEBUFF_TT"] = "Only display action when your pet has the specified buff or buffs"
L["ROB_UI_AO_PET_HAVEBUFFIB_TT"] = [=[Input the name of the buff or buffs
Syntax: |cFF00FF00| |r= OR |cFF00FF00&|r = AND |cFF00FF00_|r = casted by player |cFF00FF00#|r = number of stacks |cFF00FF00^|r = refresh at seconds
Example1: |cFF00FF00Earth Shield#2|r display action when your pet has 2 stacks of Earth Shield
Example2: |cFF00FF00_Earth Shield#2|r display action when your pet has a player casted Earth Shield at 2 stacks
Example3: |cFF00FF00_Earth Shield#2^3|r display action when your pet has a player casted Earth Shield at 2 stacks with >=3 seconds left
Example4: |cFF00FF00Earth Shield||Inner Fire|r display action when your pet has Earth Shield or Inner Fire
Example5: |cFF00FF00Earth Shield&Inner Fire|r display action when your pet has both Earth Shield and Inner Fire]=]
L["ROB_UI_AO_PET_HP_TT"] = "Only display action when pet meets specified hit points"
L["ROB_UI_AO_PET_HPIB_TT"] = [=[Input the pet hit points to check
Example1: |cFF00FF00<90%|r means only display this action when pet is under 90% hitpoints
Example2: |cFF00FF00>90%|r means only display this action when pet is over 90% hitpoints
Example3: |cFF00FF00<=90%|r means only display this action when pet is under or equal to 90% hitpoints
Example4: |cFF00FF00>=90%|r means only display this action when pet is over or equal to 90% hitpoints
Example5: |cFF00FF00=90%|r means only display this action when pet is at exactly 90% hitpoints]=]
L["ROB_UI_AO_PET_NEEDBUFF"] = "Needs Buff:"
L["ROB_UI_AO_PET_NEEDBUFF_TT"] = "Only display action when your pet needs specified buff or buffs"
L["ROB_UI_AO_PET_NEEDBUFFIB_TT"] = [=[Input the name of the buff or buffs
Syntax: |cFF00FF00| |r= OR |cFF00FF00&|r = AND |cFF00FF00_|r = casted by player |cFF00FF00#|r = number of stacks |cFF00FF00^|r = refresh at seconds
Example1: |cFF00FF00Earth Shield#2|r display action when your pet is missing 2 stacks of Earth Shield
Example2: |cFF00FF00_Earth Shield#2|r display action when your pet is missing a player casted Earth Shield at 2 stacks
Example3: |cFF00FF00_Earth Shield#2^3|r display action when your pet is missing a player casted Earth Shield at 2 stacks with >=3 seconds left
Example4: |cFF00FF00Earth Shield||Inner Fire|r display action when your pet is missing Earth Shield or Inner Fire
Example5: |cFF00FF00Earth Shield&Inner Fire|r display action when your pet is missing both Earth Shield and Inner Fire]=]
L["ROB_UI_AO_PET_TAB"] = "Pet"
L["ROB_UI_AO_PLAYER_TAB"] = "Player"
L["ROB_UI_AO_T_BOSS"] = "Boss"
L["ROB_UI_AO_T_BOSS_TT"] = "Only display action if target is a boss"
L["ROB_UI_AO_T_DISPEL"] = "Dispel"
L["ROB_UI_AO_T_DISPEL_TT"] = "Only display this action if the target has a dispelable buff"
L["ROB_UI_AO_T_HAVEBUFF"] = "Has Buff:"
L["ROB_UI_AO_T_HAVEBUFF_TT"] = "Only display action when target has the specified buff or buffs"
L["ROB_UI_AO_T_HAVEBUFFIB_TT"] = [=[Input the name of the buff or buffs
Syntax: |cFF00FF00| |r= OR |cFF00FF00&|r = AND |cFF00FF00_|r = casted by player |cFF00FF00#|r = number of stacks |cFF00FF00^|r = refresh at seconds
Example1: |cFF00FF00Earth Shield#2|r display action when target has 2 stacks of Earth Shield
Example2: |cFF00FF00_Earth Shield#2|r display action when target has a player casted Earth Shield at 2 stacks
Example3: |cFF00FF00_Earth Shield#2^3|r display action when target has a player casted Earth Shield at 2 stacks with >=3 seconds left
Example4: |cFF00FF00Earth Shield||Inner Fire|r display action when target has Earth Shield or Inner Fire
Example5: |cFF00FF00Earth Shield&Inner Fire|r display action when target has both Earth Shield and Inner Fire]=]
L["ROB_UI_AO_T_HAVEDB"] = "Have Debuff:"
L["ROB_UI_AO_T_HAVEDB_TT"] = "Only display action when target has the specified debuff or debuffs"
L["ROB_UI_AO_T_HAVEDBIB_TT"] = [=[Input the name of the debuff or debuffs
Syntax: |cFF00FF00| |r= OR |cFF00FF00&|r = AND |cFF00FF00_|r = casted by player |cFF00FF00#|r = number of stacks |cFF00FF00^|r = refresh at seconds
Example1: |cFF00FF00Dark Plague#2|r display action when target has the debuff Dark Plague 2 stacks
Example2: |cFF00FF00_Dark Plague#2|r display action when target has a player casted Dark Plague at 2 stacks
Example3: |cFF00FF00_Dark Plague#2^3|r display action when target has a player casted Dark Plague at 2 stacks with >=3 seconds left
Example4: |cFF00FF00Dark Plague|Forbearance|r display action when target has Dark Plague or Forbearance debuffs
Example5: |cFF00FF00Dark Plague&Forbearance|r display action when target has both Dark Plague and Forbearance debuffs]=]
L["ROB_UI_AO_T_HP_TT"] = "Only display action when target meets specified hit points"
L["ROB_UI_AO_T_HPIB_TT"] = [=[Input the target hit points to check
Example1: |cFF00FF00<90%|r means only display this action when target is under 90% hitpoints
Example2: |cFF00FF00>90%|r means only display this action when target is over 90% hitpoints
Example3: |cFF00FF00<=90%|r means only display this action when target is under or equal to 90% hitpoints
Example4: |cFF00FF00>=90%|r means only display this action when target is over or equal to 90% hitpoints
Example5: |cFF00FF00=90%|r means only display this action when target is at exactly 90% hitpoints]=]
L["ROB_UI_AO_T_INTERRUPT"] = "Interrupt"
L["ROB_UI_AO_T_INTERRUPT_TT"] = "Only display this action if the target is casting an interruptible spell"
L["ROB_UI_AO_T_NEEDBUFF"] = "Needs Buff:"
L["ROB_UI_AO_T_NEEDBUFF_TT"] = "Only display action when target needs specified buff or buffs"
L["ROB_UI_AO_T_NEEDBUFFIB_TT"] = [=[Input the name of the buff or buffs
Syntax: |cFF00FF00| |r= OR |cFF00FF00&|r = AND |cFF00FF00_|r = casted by player |cFF00FF00#|r = number of stacks |cFF00FF00^|r = refresh at seconds
Example1: |cFF00FF00Earth Shield#2|r display action when target is missing 2 stacks of Earth Shield
Example2: |cFF00FF00_Earth Shield#2|r display action when target is missing a player casted Earth Shield at 2 stacks
Example3: |cFF00FF00_Earth Shield#2^3|r display action when target is missing a player casted Earth Shield at 2 stacks with >=3 seconds left
Example4: |cFF00FF00Earth Shield||Inner Fire|r display action when target is missing Earth Shield or Inner Fire
Example5: |cFF00FF00Earth Shield&Inner Fire|r display action when target is missing both Earth Shield and Inner Fire]=]
L["ROB_UI_AO_T_NEEDDB"] = "Need Debuff:"
L["ROB_UI_AO_T_NEEDDB_TT"] = "Only display action when target is missing the specified debuff or debuffs"
L["ROB_UI_AO_T_NEEDDBIB_TT"] = [=[Input the name of the debuff or debuffs
Syntax: |cFF00FF00| |r= OR |cFF00FF00&|r = AND |cFF00FF00_|r = casted by player |cFF00FF00#|r = number of stacks |cFF00FF00^|r = refresh at seconds
Example1: |cFF00FF00Dark Plague#2|r display action when target is missing the debuff Dark Plague 2 stacks
Example2: |cFF00FF00_Dark Plague#2|r display action when target is missing a player casted Dark Plague at 2 stacks
Example3: |cFF00FF00_Dark Plague#2^3|r display action when target is missing a player casted Dark Plague at 2 stacks with >=3 seconds left
Example4: |cFF00FF00Dark Plague|Forbearance|r display action when target is missing Dark Plague or Forbearance debuffs
Example5: |cFF00FF00Dark Plague&Forbearance|r display action when target is missing both Dark Plague and Forbearance debuffs]=]
L["ROB_UI_AO_T_NOTABOSS"] = "Not a Boss"
L["ROB_UI_AO_T_NOTABOSS_TT"] = "Only display action if target is not a boss"
L["ROB_UI_AO_T_SPELLSTEAL"] = "Spellsteal"
L["ROB_UI_AO_T_SPELLSTEAL_TT"] = "Only display this action if the target has a stealable buff"
L["ROB_UI_AO_TARGET_TAB"] = "Target"
L["ROB_UI_CANCEL_BUTTON"] = "Cancel"
L["ROB_UI_CLOSE_BUTTON"] = "Close"
L["ROB_UI_CREATE"] = "Create"
L["ROB_UI_CREATE_TT"] = "Create a new rotation"
L["ROB_UI_DEBUG_E1"] = "NOT showing Action : "
L["ROB_UI_DEBUG_E2"] = "Action : "
L["ROB_UI_DEBUG_PREFIX"] = "Debug : "
L["ROB_UI_DELETE"] = "Delete"
L["ROB_UI_DELETE_TT"] = "Delete selected rotation"
L["ROB_UI_DISCARD"] = "Discard"
L["ROB_UI_DISCARD_TT"] = "Discard changes to selected rotation"
L["ROB_UI_EXPORT"] = "Export"
L["ROB_UI_EXPORT_MESSAGE"] = "Press CTRL+C to copy the following rotation, and then press Ctrl+V to paste it later."
L["ROB_UI_EXPORT_TT"] = "Export rotation"
L["ROB_UI_IMPORT"] = "Import"
L["ROB_UI_IMPORT_ERROR1"] = "Import failed no rotation name found"
L["ROB_UI_IMPORT_ERROR2"] = "Import failed because you already have this rotation"
L["ROB_UI_IMPORT_ERROR3"] = "Import failed because import string is not a Rotation Builder export"
L["ROB_UI_IMPORT_MESSAGE"] = "Press CTRL+V to paste a rotation build that you've copied from another source here:"
L["ROB_UI_IMPORT_SUCCESS"] = "Import successful"
L["ROB_UI_IMPORT_TT"] = "Import rotation"
L["ROB_UI_LDB_TT1"] = "<Right Click> to open Rotation Builder"
L["ROB_UI_LDB_TT2"] = "<Left Click> to select a Rotation"
L["ROB_UI_MODIFY"] = "Modify"
L["ROB_UI_MODIFY_TT"] = "Modify selected rotation"
L["ROB_UI_OK_BUTTON"] = "Ok"
L["ROB_UI_OPTIONS_TAB"] = "Options"
L["ROB_UI_PRESSKEY"] = "Press Key"
L["ROB_UI_RCOLUMNHEADER"] = "Rotations"
L["ROB_UI_RN_LABEL"] = "Rotation Name:"
L["ROB_UI_ROTATION_E1"] = "No rotation setup for that key"
L["ROB_UI_ROTATION_E2"] = "Rotation not found"
L["ROB_UI_ROTATION_TAB"] = "Rotations"
L["ROB_UI_RS_LABEL"] = "Rotation Specialization:"
L["ROB_UI_SAVE"] = "Save"
L["ROB_UI_SAVE_TT"] = "Save selected rotation"
L["ROB_UI_TITLE"] = "Rotation Builder"
L["ROB_UI_TOGGLE"] = "Open Rotation Builder's options panel"
L["ROB_UI_VERSION_LABEL"] = "Version:"
L["ui/keybinds/toggleCustomCase/text"] = "Enable/Disable custom case:"
L["ui/keybinds/toggleMultiTarget/text"] = "Enable/Disable multi-target mode"
L["ui/options/importExport/useOld/text"] = "Old import/export"
L["ui/options/importExport/useOld/tooltip"] = "Use old import/export system (compatibility purpose)"
L["ui/rotations/toggleMultiTarget/text"] = "Enable/Disable multi-target mode"
L["ui/spells/general/isCustomCase/text"] = "Custom case "
L["ui/spells/general/isCustomCase/tooltip"] = "Display this action only if this custom case is enable"
L["ui/spells/general/notCustomCase/text"] = "Not custom case "
L["ui/spells/general/notCustomCase/tooltip"] = "Display this action only if this custom case is disabled"
--@end-do-not-package@
--@localization(locale="enUS", format="lua_additive_table")@
