local L = LibStub("AceLocale-3.0"):NewLocale("RotationBuilder", "frFR")
if not L then return end

--@do-not-package@
-- Default localization for development stage.
L["defaultRotation/deathknight/apocalypse"] = "Apocalypse"
L["defaultRotation/deathknight/apocalypse_soul_reaper"] = "Apocalypse (Faucheur d'âme)"
L["defaultRotation/deathknight/army_of_the_dead"] = "Armée des morts"
L["defaultRotation/deathknight/blighted_rune_weapon"] = "Arme runique chancreuse"
L["defaultRotation/deathknight/blood"] = "Sang 7.1.5"
L["defaultRotation/deathknight/blood_boil"] = "Furoncle sanglant"
L["defaultRotation/deathknight/blood_boil_blood_plague"] = "Furoncle sanglant (Peste de sang)"
L["defaultRotation/deathknight/blood_multi"] = "Sang Multi 7.1.5"
L["defaultRotation/deathknight/blood_tap"] = "Drain sanglant"
L["defaultRotation/deathknight/blooddrinker"] = "Buveur de sang"
L["defaultRotation/deathknight/bonestorm"] = "Tempête d'os"
L["defaultRotation/deathknight/breath_of_sindragosa"] = "Souffle de Sindragosa"
L["defaultRotation/deathknight/consumption"] = "Consomption"
L["defaultRotation/deathknight/dark_arbiter"] = "Sombre médiateur"
L["defaultRotation/deathknight/dark_transformation"] = "Sombre transformation"
L["defaultRotation/deathknight/death_and_decay"] = "Mort et décomposition"
L["defaultRotation/deathknight/death_and_decay_crimson scourge"] = "Mort et décomposition (Fléau cramoisi)"
L["defaultRotation/deathknight/death_caress"] = "Caresse de la mort"
L["defaultRotation/deathknight/death_coil"] = "Voile mortel"
L["defaultRotation/deathknight/death_coil_dark_arbiter"] = "Voile mortel (Sombre médiateur)"
L["defaultRotation/deathknight/death_coil_necrosis"] = "Voile mortel (Nécrose)"
L["defaultRotation/deathknight/death_coil_shadow_infusion"] = "Voile mortel (Infusion d'ombre)"
L["defaultRotation/deathknight/death_coil_sudden_doom"] = "Voile mortel (Malédiction soudaine)"
L["defaultRotation/deathknight/death_strike"] = "Frappe de mort"
L["defaultRotation/deathknight/defile"] = "Profanation"
L["defaultRotation/deathknight/empower_rune_weapon"] = "Renforcer l'arme runique"
L["defaultRotation/deathknight/empower_rune_weapon_breath_of_sindragosa"] = "Renforcer l'arme runique (Souffle de Sindragosa)"
L["defaultRotation/deathknight/epidemic"] = "Epidémie"
L["defaultRotation/deathknight/epidemic_defile"] = "Epidémie (Profanation)"
L["defaultRotation/deathknight/festering_strike"] = "Frappe purulente"
L["defaultRotation/deathknight/festering_strike_apocalypse"] = "Frappe purulente (Apocalypse)"
L["defaultRotation/deathknight/festering_strike_dark_arbiter"] = "Frappe purulente (Sombre médiateur)"
L["defaultRotation/deathknight/frost"] = "Givre 7.1.5"
L["defaultRotation/deathknight/frost_multi"] = "Givre Multi 7.1.5"
L["defaultRotation/deathknight/frost_strike"] = "Frappe de givre"
L["defaultRotation/deathknight/frost_strike_breath_of_sindragosa"] = "Frappe de givre (Souffle de Sindragosa)"
L["defaultRotation/deathknight/frost_strike_icy_talons"] = "Frappe de givre (Serres glaciales)"
L["defaultRotation/deathknight/frost_strike_obliteration"] = "Frappe de givre (Oblitération)"
L["defaultRotation/deathknight/frost_strike_runic_power"] = "Frappe de givre (Puissance runique)"
L["defaultRotation/deathknight/frost_strike_shattering_strikes"] = "Frappe de givre (Attaques fracassantes)"
L["defaultRotation/deathknight/frostscythe"] = "Faux de givre"
L["defaultRotation/deathknight/frostscythe_breath_of_sindragosa"] = "Faux de givre (Souffle de Sindragosa)"
L["defaultRotation/deathknight/frostscythe_killing_machine"] = "Faux de givre (Machine à tuer)"
L["defaultRotation/deathknight/glacial_advance"] = "Avancée glaciale"
L["defaultRotation/deathknight/heart_strike"] = "Frappe au coeur"
L["defaultRotation/deathknight/horn_of_winter"] = "Cor de l'hiver"
L["defaultRotation/deathknight/horn_of_winter_breath_of_sindragosa"] = "Cor de l'hiver (Souffle de Sindragosa)"
L["defaultRotation/deathknight/horn_of_winter_breath_of_sindragosa_hungering_rune"] = "Cor de l'hiver (Souffle de Sindragosa (Arme runique affamée))"
L["defaultRotation/deathknight/howling_blast"] = "Rafale hurlante"
L["defaultRotation/deathknight/howling_blast_breath_of_sindragosa"] = "Rafale hurlante (Souffle de Sindragosa)"
L["defaultRotation/deathknight/howling_blast_frost_fever"] = "Rafale hurlante (Fièvre de givre)"
L["defaultRotation/deathknight/hungering_rune"] = "Arme runique affamée"
L["defaultRotation/deathknight/hungering_rune_breath_of_sindragosa"] = "Arme runique affamée (Souffle de Sindragosa)"
L["defaultRotation/deathknight/mark_of_blood"] = "Marque de sang"
L["defaultRotation/deathknight/marrowrend"] = "Déchirure de moelle"
L["defaultRotation/deathknight/marrowrend_bone_shield"] = "Déchirure de moelle (Bouclier d'os)"
L["defaultRotation/deathknight/mind_freeze"] = "Gel de l'esprit"
L["defaultRotation/deathknight/obliterate"] = "Anéantissement"
L["defaultRotation/deathknight/obliterate_breath_of_sindragosa"] = "Anéantissement (Souffle de Sindragosa)"
L["defaultRotation/deathknight/obliterate_killing_machine"] = "Anéantissement (Machine à tuer)"
L["defaultRotation/deathknight/obliteration"] = "Oblitération"
L["defaultRotation/deathknight/outbreak"] = "Poussée de fièvre"
L["defaultRotation/deathknight/pillar_of_frost"] = "Pillier de givre"
L["defaultRotation/deathknight/pillar_of_frost_breath_of_sindragosa"] = "Pillier de givre (Souffle de Sindragosa)"
L["defaultRotation/deathknight/pillar_of_frost_breath_of_sindragosa_ready"] = "Pillier de givre (Souffle de Sindragosa prêt)"
L["defaultRotation/deathknight/raise_dead"] = "Réanimation morbide"
L["defaultRotation/deathknight/remorseless_winter"] = "Hiver impitoyable"
L["defaultRotation/deathknight/remorseless_winter_breath_of_sindragosa"] = "Hiver impitoyable (Souffle de Sindragosa)"
L["defaultRotation/deathknight/scourge_strike"] = "Frappe du fléau"
L["defaultRotation/deathknight/scourge_strike_scourge_of_worlds"] = "Frappe du fléau (Fléau des mondes)"
L["defaultRotation/deathknight/scourge_strike_soul_reaper"] = "Frappe du fléau (Faucheur d'âme)"
L["defaultRotation/deathknight/scourge_strike_soul_reaper_soon"] = "Frappe du fléau (Faucheur d'âme bientôt)"
L["defaultRotation/deathknight/sindragosa_fury"] = "Fureur de Sindragosa"
L["defaultRotation/deathknight/soul_reaper"] = "Faucheur d'âme"
L["defaultRotation/deathknight/soul_reaper_apocalypse"] = "Faucheur d'âme (Apocalypse)"
L["defaultRotation/deathknight/soulgorge"] = "Gorgé d'âmes"
L["defaultRotation/deathknight/summon_gargoyle"] = "Invocation d'une gargouille"
L["defaultRotation/deathknight/unholy"] = "Impie 7.1.5"
L["defaultRotation/deathknight/unholy_multi"] = "Impie Multi 7.1.5"
L["defaultRotation/deathknight/vampiric_blood"] = "Sang vampirique"
L["defaultRotation/demonhunter/annihilation"] = "Annihiler"
L["defaultRotation/demonhunter/annihilation_chaos_cleave"] = "Annihiler (Enchaînement du chaos)"
L["defaultRotation/demonhunter/annihilation_demon_blades"] = "Annihiler (Lames du démon)"
L["defaultRotation/demonhunter/blade_dance"]= "Danse des lames"
L["defaultRotation/demonhunter/chaos_blades"]= "Lames du chaos"
L["defaultRotation/demonhunter/chaos_strike"] = "Frappe du chaos"
L["defaultRotation/demonhunter/chaos_strike_chaos_cleave"] = "Frappe du chaos (Enchaînement du chaos)"
L["defaultRotation/demonhunter/chaos_strike_demon_blades"] = "Frappe du chaos (Lames du démon)"
L["defaultRotation/demonhunter/consume_magic"] = "Manavore"
L["defaultRotation/demonhunter/death_sweep"] = "Balayage mortel"
L["defaultRotation/demonhunter/demon_bite"] = "Morsure du démon"
L["defaultRotation/demonhunter/demon_spikes"] = "Pointes démoniaques"
L["defaultRotation/demonhunter/eye_beam"]= "Rayon accablant"
L["defaultRotation/demonhunter/fel_barrage"]= "Barrage gangrené"
L["defaultRotation/demonhunter/fel_devastation"]= "Dévastation gangrenée"
L["defaultRotation/demonhunter/fel_eruption"]= "Éruption gangrenée"
L["defaultRotation/demonhunter/fel_rush"] = "Ruée fulgurante"
L["defaultRotation/demonhunter/fel_rush_fel_mastery"] = "Ruée fulgurante (Maîtrise de la corruption)"
L["defaultRotation/demonhunter/fel_rush_momentum"] = "Ruée fulgurante (Inertie)"
L["defaultRotation/demonhunter/fel_rush_momentum_fel_mastery"]= "Ruée fulgurante (Inertie + Maîtrise de la corruption)"
L["defaultRotation/demonhunter/felblade"]= "Gangrelame"
L["defaultRotation/demonhunter/fracture"]= "Fracture"
L["defaultRotation/demonhunter/fury_of_the_illidari"]= "Fureur des Illidari"
L["defaultRotation/demonhunter/havoc"] = "Dévastation 7.1.5"
L["defaultRotation/demonhunter/havoc_multi"] = "Dévastation Multi 7.1.5"
L["defaultRotation/demonhunter/immolation_aura"] = "Aura d'immolation"
L["defaultRotation/demonhunter/infernal_strike"] = "Frappe infernale"
L["defaultRotation/demonhunter/metamorphosis"] = "Métamorphose"
L["defaultRotation/demonhunter/nemesis"]= "Némésis"
L["defaultRotation/demonhunter/shear"] = "Entaille"
L["defaultRotation/demonhunter/shear_blade_turning"]= "Entaille (Déviation de lame)"
L["defaultRotation/demonhunter/sigil_of_flame"] = "Sigil de feu"
L["defaultRotation/demonhunter/soul_barrier"]= "Barrière d’âme"
L["defaultRotation/demonhunter/soul_cleave"] = "Division de l'âme"
L["defaultRotation/demonhunter/soul_rending"]= "Déchirement d’âme"
L["defaultRotation/demonhunter/spirit_bomb"]= "Bombe spirituelle"
L["defaultRotation/demonhunter/throw_glaive"] = "Lancer de glaive"
L["defaultRotation/demonhunter/throw_glaive_bloodlet"]= "Lancer de glaive (Suppuration)"
L["defaultRotation/demonhunter/vengeance"] = "Vengeance 7.1.5"
L["defaultRotation/demonhunter/vengeance_multi"] = "Vengeance Multi 7.1.5"
L["defaultRotation/demonhunter/vengeful_retreat"] = "Retraite vengeresse"
L["defaultRotation/demonhunter/vengeful_retreat_momentum"] = "Retraite vengeresse (Inertie)"
L["defaultRotation/demonhunter/vengeful_retreat_momentum_prepared"]= "Retraite vengeresse (Inertie + Combativité)"
L["defaultRotation/druid/ashamane_frenzy"] = "Frénésie d'Ashamane"
L["defaultRotation/druid/ashamane_frenzy_bloodtalons"] = "Frénésie d'Ashamane (Griffes de sang)"
L["defaultRotation/druid/astral_communion"] = "Communion astrale"
L["defaultRotation/druid/astral_communion_fury_of_elune"] = "Communion astrale (Fureur d'Élune)"
L["defaultRotation/druid/balance"] = "Équilibre 7.1.5"
L["defaultRotation/druid/balance_multi"] = "Équilibre Multi 7.1.5"
L["defaultRotation/druid/bear_form"] = "Forme d'ours"
L["defaultRotation/druid/berserk"] = "Berserk"
L["defaultRotation/druid/blessing_of_the_ancients"] = "Bénédiction des anciens"
L["defaultRotation/druid/bristling_fur"] = "Poils hérissés"
L["defaultRotation/druid/brutal_slash"] = "Entaille brutale"
L["defaultRotation/druid/cat_form"] = "Forme de félin"
L["defaultRotation/druid/celestial_alignment"] = "Alignement céleste"
L["defaultRotation/druid/cenarion_ward"] = "Protection cénarienne"
L["defaultRotation/druid/elune_guidance"] = "Soutien d'Élune"
L["defaultRotation/druid/feral"] = "Farouche 7.1.5"
L["defaultRotation/druid/feral_multi"] = "Farouche Multi 7.1.5"
L["defaultRotation/druid/ferocious_bite"] = "Morsure féroce"
L["defaultRotation/druid/ferocious_bite_rip"] = "Morsure féroce (Déchirure)"
L["defaultRotation/druid/ferocious_bite_rip_jagged_wounds"] = "Morsure féroce (Déchirure (Blessures sanguinolantes))"
L["defaultRotation/druid/ferocious_bite_sabertooth"] = "Morsure féroce (Dent de sabre)"
L["defaultRotation/druid/ferocious_bite_savage_roar"] = "Morsure féroce (Rugissement sauvage)"
L["defaultRotation/druid/force_of_nature"] = "Force de la nature"
L["defaultRotation/druid/frenzied_regeneration"] = "Régénération frénétique"
L["defaultRotation/druid/fury_of_elune"] = "Fureur d'Élune"
L["defaultRotation/druid/guardian"] = "Gardien 7.1.5"
L["defaultRotation/druid/guardian_multi"] = "Gardien Multi 7.1.5"
L["defaultRotation/druid/incarnation_chosen_of_elune"] = "Incarnation : Appelé d'Élune"
L["defaultRotation/druid/incarnation_king_of_the_jungle"] = "Incarnation : Roi de la jungle"
L["defaultRotation/druid/ironfur"] = "Ferpoil"
L["defaultRotation/druid/lunar_beam"] = "Rayon lunaire"
L["defaultRotation/druid/lunar_strike"] = "Frappe lunaire"
L["defaultRotation/druid/lunar_strike_warrior_of_elune"] = "Frappe lunaire (Guerrier d'Élune)"
L["defaultRotation/druid/mangle"] = "Mutilation"
L["defaultRotation/druid/mark_of_ursol"] = "Marque d'Ursol"
L["defaultRotation/druid/maul"] = "Mutiler"
L["defaultRotation/druid/moonfire"] = "Eclat lunaire"
L["defaultRotation/druid/moonfire_balance"] = "Eclat lunaire (Équilibre)"
L["defaultRotation/druid/moonfire_fury_of_elune"] = "Eclat lunaire (Fureur d'Élune)"
L["defaultRotation/druid/moonfire_galactic_guardian"] = "Eclat lunaire (Gardien galactique)"
L["defaultRotation/druid/moonkin_form"] = "Forme de sélénien"
L["defaultRotation/druid/new_moon"] = "Nouvelle lune"
L["defaultRotation/druid/new_moon_fury_of_elune"] = "Nouvelle lune (Fureur d'Élune)"
L["defaultRotation/druid/new_moon_fury_of_elune_reload"] = "Nouvelle lune (Fureur d'Élune recharge)"
L["defaultRotation/druid/new_moon_fury_of_elune_soon"] = "Nouvelle lune (Fureur d'Élune bientôt)"
L["defaultRotation/druid/pulverize"] = "Pulvérisation"
L["defaultRotation/druid/rage_of_the_sleeper"] = "Rage du dormeur"
L["defaultRotation/druid/rake"] = "Griffure"
L["defaultRotation/druid/rake_jagged_wounds"] = "Griffure (Blessures sanguinolantes)"
L["defaultRotation/druid/regrowth"] = "Rétablissement"
L["defaultRotation/druid/regrowth_bloodtalons"] = "Rétablissement (Griffes de sang)"
L["defaultRotation/druid/renewal"] = "Renouveau"
L["defaultRotation/druid/restoration"] = "Restauration 7.1.5"
L["defaultRotation/druid/restoration_multi"] = "Restauration Multi 7.1.5"
L["defaultRotation/druid/rip"] = "Déchirure"
L["defaultRotation/druid/rip_jagged_wounds"] = "Déchirure (Blessures sanguinolantes)"
L["defaultRotation/druid/savage_roar"] = "Rugissement sauvage"
L["defaultRotation/druid/shred"] = "Lambeau"
L["defaultRotation/druid/skull_bash"] = "Coup de crâne"
L["defaultRotation/druid/solar_beam"] = "Rayon solaire"
L["defaultRotation/druid/solar_wrath"] = "Courroux solaire"
L["defaultRotation/druid/starfall"] = "Météores"
L["defaultRotation/druid/starfall_fury_of_elune"] = "Météores (Fureur d'Élune)"
L["defaultRotation/druid/starsurge"] = "Eruption stellaire"
L["defaultRotation/druid/starsurge_fury_of_elune"] = "Eruption stellaire (Fureur d'Élune)"
L["defaultRotation/druid/stellar_flare"] = "Flamboiement stellaire"
L["defaultRotation/druid/sunfire"] = "Eclat solaire"
L["defaultRotation/druid/sunfire_fury_of_elune"] = "Eclat solaire (Fureur d'Élune)"
L["defaultRotation/druid/swipe"] = "Balayage"
L["defaultRotation/druid/swipe_feral"] = "Balayage (Farouche)"
L["defaultRotation/druid/swipe_guardian"] = "Balayage (Gardien)"
L["defaultRotation/druid/thrash"] = "Rosser"
L["defaultRotation/druid/thrash_guardian"] = "Rosser (Gardien)"
L["defaultRotation/druid/thrash_jagged_wounds"] = "Rosser (Blessures sanguinolantes)"
L["defaultRotation/druid/tiger_fury"] = "Fureur du tigre"
L["defaultRotation/druid/warrior_of_elune"] = "Guerrier d'Élune"
L["defaultRotation/druid/wild_charge"] = "Charge sauvage"
L["defaultRotation/hunter/a_murder_of_crows"] = "Corbeaux hargneux"
L["defaultRotation/hunter/aimed_shot"] = "Visée"
L["defaultRotation/hunter/aimed_shot_vunerable"] = "Visée (Vulnérable)"
L["defaultRotation/hunter/arcane_shot"] = "Tir des Arcanes"
L["defaultRotation/hunter/arcane_shot_steady_focus"] = "Tir des Arcanes (Focalisation assurée)"
L["defaultRotation/hunter/aspect_of_the_eagle"] = "Aspect de l'aigle"
L["defaultRotation/hunter/aspect_of_the_wild"] = "Aspect de la Nature"
L["defaultRotation/hunter/barrage"] = "Barrage"
L["defaultRotation/hunter/beast_mastery"] = "Maîtrise des bêtes 7.1.5"
L["defaultRotation/hunter/beast_mastery_multi"] = "Maîtrise des bêtes Multi 7.1.5"
L["defaultRotation/hunter/bestial_wrath"] = "Courroux bestial"
L["defaultRotation/hunter/black_arrow"] = "Flèche noire"
L["defaultRotation/hunter/butchery"] = "Boucherie"
L["defaultRotation/hunter/caltrops"] = "Chausse-trapes"
L["defaultRotation/hunter/carve"] = "Echarper"
L["defaultRotation/hunter/carve_serpent_sting"] = "Echarper (Morsure de serpent)"
L["defaultRotation/hunter/chimaera_shot"] = "Tir de la chimère"
L["defaultRotation/hunter/cobra_shot"] = "Tir du cobra"
L["defaultRotation/hunter/cobra_shot_bestial_wrath"] = "Tir du cobra (Courroux bestial)"
L["defaultRotation/hunter/cobra_shot_bestial_wrath_soon"] = "Tir du cobra (Courroux bestial bientôt)"
L["defaultRotation/hunter/counter_shot"] = "Tir de riposte"
L["defaultRotation/hunter/dire_beast"] = "Bête féroce"
L["defaultRotation/hunter/dire_frenzy"] = "Frénésie féroce"
L["defaultRotation/hunter/dragonsfire_grenade"] = "Grenade de feu draconique"
L["defaultRotation/hunter/explosive_shot"] = "Tir explosif"
L["defaultRotation/hunter/explosive_trap"] = "Piège explosif"
L["defaultRotation/hunter/flanking_strike"] = "Frappe latérale"
L["defaultRotation/hunter/fury_of_the_eagle"] = "Fureur de l'aigle"
L["defaultRotation/hunter/harpoon"] = "Harpon"
L["defaultRotation/hunter/kill_command"] = "Ordre de tuer"
L["defaultRotation/hunter/kill_command_bestial_wrath"] = "Ordre de tuer (Courroux bestial)"
L["defaultRotation/hunter/lacerate"] = "Lacérer"
L["defaultRotation/hunter/marked_shot"] = "Tir marqué"
L["defaultRotation/hunter/marksmanship"] = "Précision 7.1.5"
L["defaultRotation/hunter/marksmanship_multi"] = "Précision Multi 7.1.5"
L["defaultRotation/hunter/mend_pet"] = "Guérison du familier"
L["defaultRotation/hunter/mongoose_bite"] = "Morsure de mangouste"
L["defaultRotation/hunter/mongoose_bite_3_charges"] = "Morsure de mangouste (3 Charges)"
L["defaultRotation/hunter/multi-shot"] = "Flèches multiples"
L["defaultRotation/hunter/multi-shot_barrage"] = "Flèches multiples (Barrage)"
L["defaultRotation/hunter/multi-shot_barrage_ready"] = "Flèches multiples (Barrage prêt)"
L["defaultRotation/hunter/multi-shot_steady_focus"] = "Flèches multiples (Focalisation assurée)"
L["defaultRotation/hunter/muzzle"] = "Muselière"
L["defaultRotation/hunter/piercing_shot"] = "Tir perforant"
L["defaultRotation/hunter/raptor_strike"] = "Attaque du raptor"
L["defaultRotation/hunter/raptor_strike_serpent_sting"] = "Attaque du raptor (Morsure de serpent)"
L["defaultRotation/hunter/raptor_strike_way_of_the_mok_nathal"] = "Attaque du raptor (Voie des Mok'Nathal)"
L["defaultRotation/hunter/revive_pet"] = "Ressuciter le familier"
L["defaultRotation/hunter/sentinel"] = "Sentinelle"
L["defaultRotation/hunter/sidewinders"] = "Crotales cornus"
L["defaultRotation/hunter/sidewinders_2_charges"] = "Crotales cornus (2 Charges)"
L["defaultRotation/hunter/snake_hunter"] = "Chasseur de serpents"
L["defaultRotation/hunter/spitting_cobra"] = "Cobra cracheur"
L["defaultRotation/hunter/stampede"] = "Ruée"
L["defaultRotation/hunter/steel_trap"] = "Piège d'acier"
L["defaultRotation/hunter/survival"] = "Survie 7.1.5"
L["defaultRotation/hunter/survival_multi"] = "Survie Multi 7.1.5"
L["defaultRotation/hunter/throwing_axes"] = "Haches de lancer"
L["defaultRotation/hunter/titan_thunder"] = "Tonnerre du titan"
L["defaultRotation/hunter/titan_thunder_dire_frenzy"] = "Tonnerre du titan (Frénésie féroce)"
L["defaultRotation/hunter/trueshot"] = "Précision"
L["defaultRotation/hunter/volley"] = "Salve"
L["defaultRotation/hunter/windburst"] = "Bourrasque de vent"
L["defaultRotation/mage/arcane"] = "Arcane 7.0.3"
L["defaultRotation/mage/arcane_barrage"] = "Barrage des Arcanes"
L["defaultRotation/mage/arcane_blast"] = "Déflagration des Arcanes"
L["defaultRotation/mage/arcane_familiar"] = "Familier arcanique"
L["defaultRotation/mage/arcane_missiles"] = "Projectiles des Arcanes"
L["defaultRotation/mage/arcane_missiles_3_charges"] = "Projectiles des Arcanes (3 Charges)"
L["defaultRotation/mage/arcane_missiles_arcane_power"] = "Projectiles des Arcanes (Pouvoir des Arcanes)"
L["defaultRotation/mage/arcane_orb"] = "Orbe arcanique"
L["defaultRotation/mage/arcane_power"] = "Pouvoir des Arcanes"
L["defaultRotation/mage/blizzard"] = "Blizzard"
L["defaultRotation/mage/charged_up"] = "Chargé à bloc"
L["defaultRotation/mage/cinderstorm"] = "Tempête de cendres"
L["defaultRotation/mage/combustion"] = "Combustion"
L["defaultRotation/mage/commet_storm"] = "Tempête de comètes"
L["defaultRotation/mage/counterspell"] = "Contresort"
L["defaultRotation/mage/ebonbolt"] = "Eclair d'ébène"
L["defaultRotation/mage/evocation"] = "Evocation"
L["defaultRotation/mage/fire"] = "Feu 7.0.3"
L["defaultRotation/mage/fire_blast"] = "Trait de feu"
L["defaultRotation/mage/fireball"] = "Boule de feu"
L["defaultRotation/mage/flame_on"] = "Enflammé"
L["defaultRotation/mage/flurry"] = "Rafale"
L["defaultRotation/mage/frost"] = "Givre 7.1.5"
L["defaultRotation/mage/frost_bomb"] = "Bombe de givre"
L["defaultRotation/mage/frost_multi"] = "Givre Multi 7.1.5"
L["defaultRotation/mage/frostbolt"] = "Eclair de givre"
L["defaultRotation/mage/frostbolt_brain_freeze"] = "Eclair de givre (Gel mental)"
L["defaultRotation/mage/frozen_orb"] = "Orbe gelé"
L["defaultRotation/mage/glacial_spike"] = "Pointe glaciaire"
L["defaultRotation/mage/ice_barrier"] = "Barrière de glace"
L["defaultRotation/mage/ice_lance"] = "Javelot de glace"
L["defaultRotation/mage/ice_lance_brain_freeze"] = "Javelot de glace (Gel mental)"
L["defaultRotation/mage/ice_lance_fingers_of_frost"] = "Javelot de glace (Doigts de givre)"
L["defaultRotation/mage/ice_lance_flurry"] = "Javelot de glace (Rafale)"
L["defaultRotation/mage/ice_nova"] = "Nova de glace"
L["defaultRotation/mage/icy_veins"] = "Veines glaciales"
L["defaultRotation/mage/living_bomb"] = "Bombe vivante"
L["defaultRotation/mage/meteor"] = "Météore"
L["defaultRotation/mage/mirror_image"] = "Image miroir"
L["defaultRotation/mage/nether_tempest"] = "Tempête du Néant"
L["defaultRotation/mage/presence_of_mind"] = "Présence spirituelle"
L["defaultRotation/mage/pyroblast"] = "Explosion pyrotechnique"
L["defaultRotation/mage/ray_of_frost"] = "Rayon de givre"
L["defaultRotation/mage/rune_of_power"] = "Rune de puissance"
L["defaultRotation/mage/rune_of_power_2_charges"] = "Rune de puissance (2 Charges)"
L["defaultRotation/mage/rune_of_power_combustion"] = "Rune de puissance (Combustion)"
L["defaultRotation/mage/rune_of_power_frozen_orb"] = "Rune de puissance (Orbe gelé)"
L["defaultRotation/mage/rune_of_power_icy_veins"] = "Rune de puissance (Veines glaciales)"
L["defaultRotation/mage/rune_of_power_ray_of_frost"] = "Rune de puissance (Rayon de givre)"
L["defaultRotation/mage/spellsteal"] = "Vol de sort"
L["defaultRotation/mage/summon_water_elemental"] = "Invocation d'un élémentaire d'eau"
L["defaultRotation/mage/supernova"] = "Supernova"
L["defaultRotation/mage/water_jet"] = "Jaillissement d'eau"
L["defaultRotation/monk/black_ox_brew"] = "Breuvage du Buffle noir"
L["defaultRotation/monk/blackout_kick"] = "Frappe du voile noir"
L["defaultRotation/monk/blackout_kick_blackout_kick"] = "Frappe du voile noir (Frappe du voile noir !)"
L["defaultRotation/monk/blackout_kick_serenity"] = "Frappe du voile noir (Sérénité)"
L["defaultRotation/monk/blackout_kick_spirit_of_the_crane"] = "Frappe du voile noir (Esprit de la grue)"
L["defaultRotation/monk/blackout_strike"] = "Frappe aveuglante"
L["defaultRotation/monk/breath_of_fire"] = "Souffle de feu"
L["defaultRotation/monk/brewmaster"] = "Maître brasseur 7.1.5"
L["defaultRotation/monk/brewmaster_multi"] = "Maître brasseur Multi 7.1.5"
L["defaultRotation/monk/chi_burst"] = "Explosion de chi"
L["defaultRotation/monk/chi_wave"] = "Onde de chi"
L["defaultRotation/monk/energising_elixir"] = "Elixir énergisant"
L["defaultRotation/monk/expel_harm"] = "Extraction du mal"
L["defaultRotation/monk/exploding_keg"] = "Tonneau explosif"
L["defaultRotation/monk/fists_of_fury"] = "Poings de fureur"
L["defaultRotation/monk/fists_of_fury_serenity"] = "Poings de fureur (Sérénité)"
L["defaultRotation/monk/healing_elixir"] = "Elixir de soins"
L["defaultRotation/monk/invoke_xuen_the_white_tiger"] = "Invocation de Xuen, le Tigre blanc"
L["defaultRotation/monk/ironskin_brew"] = "Infusion peau-de-fer"
L["defaultRotation/monk/keg_smash"] = "Fracasse-tonneau"
L["defaultRotation/monk/mistweaver"] = "Tisse-brume 7.1.5"
L["defaultRotation/monk/mistweaver_multi"] = "Tisse-brume Multi 7.1.5"
L["defaultRotation/monk/purifying_brew"] = "Infusion purificatrice"
L["defaultRotation/monk/rising_sun_kick"] = "Coup de pied du soleil levant"
L["defaultRotation/monk/rising_sun_kick_serenity"] = "Coup de pied du soleil levant (Sérénité)"
L["defaultRotation/monk/rushing_jade_wind"] = "Vent de jade fulgurant"
L["defaultRotation/monk/rushing_jade_wind_serenity"] = "Vent de jade fulgurant (Sérénité)"
L["defaultRotation/monk/serenity"] = "Sérénité"
L["defaultRotation/monk/spear_hand_strike"] = "Pique de main"
L["defaultRotation/monk/spinning_crane_kick"] = "Coup tournoyant de la grue"
L["defaultRotation/monk/spinning_crane_kick_serenity"] = "Coup tournoyant de la grue (Sérénité)"
L["defaultRotation/monk/storm_earth_and_fire"] = "Tempête, Terre et Feu"
L["defaultRotation/monk/storm_earth_and_fire_fists_of_fury"] = "Tempête, Terre et Feu (Poings de fureur)"
L["defaultRotation/monk/strike_of_the_windlord"] = "Frappe du seigneur des Vents"
L["defaultRotation/monk/strike_of_the_windlord_serenity"] = "Frappe du seigneur des Vents (Sérénité)"
L["defaultRotation/monk/thunder_focus_tea"] = "Thé de concentration foudroyante"
L["defaultRotation/monk/tiger_palm"] = "Paume du tigre"
L["defaultRotation/monk/tiger_palm_energy"] = "Paume du tigre (Energie)"
L["defaultRotation/monk/tiger_palm_eye_of_the_tiger"] = "Paume du tigre (Oeil du tigre)"
L["defaultRotation/monk/touch_of_death"] = "Toucher mortel"
L["defaultRotation/monk/whirling_dragon_punch"] = "Coup de poing du dragon tourbillonant"
L["defaultRotation/monk/windwalker"] = "Marche-vent 7.1.5"
L["defaultRotation/monk/windwalker_multi"] = "Marche-vent Multi 7.1.5"
L["defaultRotation/monk/zen_pulse"] = "Impulsion zen"
L["defaultRotation/paladin/avenger_shield"] = "Bouclier du vengeur"
L["defaultRotation/paladin/avenging_wrath"] = "Courroux vengeur"
L["defaultRotation/paladin/blade_of_justice"] = "Lame de justice"
L["defaultRotation/paladin/blessed_hammer"] = "Marteau béni"
L["defaultRotation/paladin/consecration"] = "Consécration"
L["defaultRotation/paladin/crusade"] = "Croisade"
L["defaultRotation/paladin/crusader_strike"] = "Frappe du croisé"
L["defaultRotation/paladin/divine_hammer"] = "Marteau divin"
L["defaultRotation/paladin/divine_storm"] = "Tempête divine"
L["defaultRotation/paladin/execution_sentence"] = "Condamnation à mort"
L["defaultRotation/paladin/eye_of_tyr"] = "Oeil de Tyr"
L["defaultRotation/paladin/greater_blessing_of_kings"] = "Bénédiction des rois supérieure"
L["defaultRotation/paladin/greater_blessing_of_wisdom"] = "Bénédiction de sagesse supérieure"
L["defaultRotation/paladin/hammer_of_justice"] = "Marteau de la justice"
L["defaultRotation/paladin/hammer_of_the_righteous"] = "Marteau du vertueux"
L["defaultRotation/paladin/hand_of_the_protector"] = "Main du protecteur"
L["defaultRotation/paladin/holy"] = "Sacré 7.1.5"
L["defaultRotation/paladin/holy_multi"] = "Sacré Multi 7.1.5"
L["defaultRotation/paladin/holy_prism"] = "Prisme sacré"
L["defaultRotation/paladin/holy_shock"] = "Horion sacré"
L["defaultRotation/paladin/holy_wrath"] = "Colère divine"
L["defaultRotation/paladin/judgment"] = "Jugement"
L["defaultRotation/paladin/judgment_execution_sentence"] = "Jugement (Condamnation à mort)"
L["defaultRotation/paladin/justicar_vengeance"] = "Vengeance du justicier"
L["defaultRotation/paladin/lay_on_hands"] = "Imposition des mains"
L["defaultRotation/paladin/light_of_the_protector"] = "Lumière du protecteur"
L["defaultRotation/paladin/protection"] = "Protection 7.1.5"
L["defaultRotation/paladin/protection_multi"] = "Protection Multi 7.1.5"
L["defaultRotation/paladin/rebuke"] = "Réprimandes"
L["defaultRotation/paladin/retribution"] = "Vindicte 7.1.5"
L["defaultRotation/paladin/retribution_multi"] = "Vindicte Multi 7.1.5"
L["defaultRotation/paladin/shield_of_the_righteous"] = "Bouclier du vertueux"
L["defaultRotation/paladin/templar_verdict"] = "Verdict du templier"
L["defaultRotation/paladin/wake_of_ashes"] = "Trainée de cendres"
L["defaultRotation/paladin/word_of_glory"] = "Mot de gloire"
L["defaultRotation/paladin/zeal"] = "Zèle"
L["defaultRotation/priest/desperate_prayer"] = "Prière de désespoir"
L["defaultRotation/priest/discipline"] = "Discipline 7.1.5"
L["defaultRotation/priest/discipline_multi"] = "Discipline Multi 7.1.5"
L["defaultRotation/priest/dispel_magic"] = "Dissipation de la magie"
L["defaultRotation/priest/divine_star"] = "Etoile divine"
L["defaultRotation/priest/flash_heal"] = "Soins rapides"
L["defaultRotation/priest/halo"] = "Halo"
L["defaultRotation/priest/holy"] = "Sacré 7.1.5"
L["defaultRotation/priest/holy_fire"] = "Flammes sacrées"
L["defaultRotation/priest/holy_multi"] = "Sacré Multi 7.1.5"
L["defaultRotation/priest/holy_nova"] = "Nova sacrée"
L["defaultRotation/priest/holy_word_chastise"] = "Mot sacré : Châtier"
L["defaultRotation/priest/light_wrath"] = "Courroux de la Lumière"
L["defaultRotation/priest/light_wrath_atonement"] = "Courroux de la Lumière (Expiation 10+)"
L["defaultRotation/priest/mind_blast"] = "Attaque mentale"
L["defaultRotation/priest/mind_flay"] = "Fouet mental"
L["defaultRotation/priest/mindbender"] = "Torve-esprit"
L["defaultRotation/priest/penance"] = "Pénitence"
L["defaultRotation/priest/power_infusion"] = "Infusion de puissance"
L["defaultRotation/priest/purge_the_wicked"] = "Purge du mal"
L["defaultRotation/priest/schism"] = "Schisme"
L["defaultRotation/priest/shadow"] = "Ombre 7.1.5"
L["defaultRotation/priest/shadow_crash"] = "Déferlante d'ombre"
L["defaultRotation/priest/shadow_multi"] = "Ombre Multi 7.1.5"
L["defaultRotation/priest/shadow_word_death"] = "Mot de l'ombre : mort"
L["defaultRotation/priest/shadow_word_death_2_charges"] = "Mot de l'ombre : mort (2 Charges)"
L["defaultRotation/priest/shadow_word_pain"] = "Mot de l'ombre : douleur"
L["defaultRotation/priest/shadow_word_pain_void_eruption"] = "Mot de l'ombre : douleur (Eruption du Vide)"
L["defaultRotation/priest/shadow_word_solace"] = "Mot de pouvoir : Réconfort"
L["defaultRotation/priest/shadow_word_void"] = "Mot de l'ombre : Vide"
L["defaultRotation/priest/shadowfiend"] = "Ombrefiel"
L["defaultRotation/priest/shadowform"] = "Forme d'Ombre"
L["defaultRotation/priest/silence"] = "Silence"
L["defaultRotation/priest/smite"] = "Châtiment"
L["defaultRotation/priest/surrender_to_madness"] = "Sombre dans la folie"
L["defaultRotation/priest/vampiric_touch"] = "Toucher vampirique"
L["defaultRotation/priest/vampiric_touch_misery"] = "Toucher vampirique (Misère)"
L["defaultRotation/priest/vampiric_touch_void_eruption"] = "Toucher vampirique (Eruption du Vide)"
L["defaultRotation/priest/vampiric_touch_void_eruption_misery"] = "Toucher vampirique (Eruption du Vide (Misère))"
L["defaultRotation/priest/void_bolt"] = "Eclair de Vide"
L["defaultRotation/priest/void_eruption"] = "Eruption du Vide"
L["defaultRotation/priest/void_eruption_legacy_of_the_void"] = "Eruption du Vide (Héritage du Vide)"
L["defaultRotation/priest/void_torrent"] = "Torrent du Vide"
L["defaultRotation/rogue/adrenaline_rush"] = "Poussée d'adrénaline"
L["defaultRotation/rogue/agonizing_poison"] = "Poison déchirant"
L["defaultRotation/rogue/ambush"] = "Embuscade"
L["defaultRotation/rogue/assassination"] = "Assassinat 7.1.5"
L["defaultRotation/rogue/assassination_multi"] = "Assassinat Multi 7.1.5"
L["defaultRotation/rogue/backstab"] = "Attaque sournoise"
L["defaultRotation/rogue/backstab_anticipation"] = "Attaque sournoise (Anticipation)"
L["defaultRotation/rogue/backstab_deeper_stratagem"] = "Attaque sournoise (Stratagème approfondi)"
L["defaultRotation/rogue/between_the_eyes"] = "Entre les deux yeux"
L["defaultRotation/rogue/between_the_eyes_deeper_stratagem"] = "Entre les deux yeux (Stratagème approfondi)"
L["defaultRotation/rogue/blade_flurry"] = "Déluge de lames"
L["defaultRotation/rogue/cannonball_barrage"] = "Barrage de canons"
L["defaultRotation/rogue/crimson_vial"] = "Fiole cramoisie"
L["defaultRotation/rogue/crimson_vial_iron_stomach"] = "Fiole cramoisie (Estomac de fer)"
L["defaultRotation/rogue/curse_of_the_dreadblades"] = "Malédiction des lames d'effroi"
L["defaultRotation/rogue/deadly_poison"] = "Poison mortel"
L["defaultRotation/rogue/death_from_above"] = "La mort venue d'en haut"
L["defaultRotation/rogue/death_from_above_deeper_stratagem"] = "La mort venue d'en haut (Stratagème approfondi)"
L["defaultRotation/rogue/enveloping_shadows"] = "Ombres enveloppantes"
L["defaultRotation/rogue/enveloping_shadows_deeper_stratagem"] = "Ombres enveloppantes (Stratagème approfondi)"
L["defaultRotation/rogue/envenom"] = "Envenimer"
L["defaultRotation/rogue/envenom_deeper_stratagem"] = "Envenimer (Stratagème approfondi)"
L["defaultRotation/rogue/eviscerate"] = "Eviscération"
L["defaultRotation/rogue/eviscerate_deeper_stratagem"] = "Eviscération (Stratagème approfondi)"
L["defaultRotation/rogue/exsanguinate"] = "Exsangue"
L["defaultRotation/rogue/fan_of_knives"] = "Eventail de couteaux"
L["defaultRotation/rogue/garrote"] = "Garrot"
L["defaultRotation/rogue/garrote_deeper_stratagem"] = "Garrot (Stratagème approfondi)"
L["defaultRotation/rogue/garrote_stealth"] = "Garrot (Camouflage)"
L["defaultRotation/rogue/ghostly_strike"] = "Frappe fantomatique"
L["defaultRotation/rogue/ghostly_strike_anticipation"] = "Frappe fantomatique (Anticipation)"
L["defaultRotation/rogue/ghostly_strike_deeper_stratagem"] = "Frappe fantomatique (Stratagème approfondi)"
L["defaultRotation/rogue/goremaw_s_bite"] = "Morsure de Gueulétripe"
L["defaultRotation/rogue/hemorrhage"] = "Hémorragie"
L["defaultRotation/rogue/kick"] = "Coup de pied"
L["defaultRotation/rogue/killing_spree"] = "Série meurtrière"
L["defaultRotation/rogue/kingsbane"] = "Plaie des rois"
L["defaultRotation/rogue/leeching_poison"] = "Poison sangsue"
L["defaultRotation/rogue/marked_for_death"] = "Désigné pour mourir"
L["defaultRotation/rogue/marked_for_death_anticipation"] = "Désigné pour mourir (Anticipation)"
L["defaultRotation/rogue/marked_for_death_deeper_stratagem"] = "Désigné pour mourir (Stratagème approfondi)"
L["defaultRotation/rogue/mutilate"] = "Estropier"
L["defaultRotation/rogue/mutilate_deeper_stratagem"] = "Estropier (Stratagème approfondi)"
L["defaultRotation/rogue/nightblade"] = "Lamenuit"
L["defaultRotation/rogue/nightblade_deeper_stratagem"] = "Lamenuit (Stratagème approfondi)"
L["defaultRotation/rogue/outlaw"] = "Hors-la-loi 7.1.5"
L["defaultRotation/rogue/outlaw_multi"] = "Hors-la-loi Multi 7.1.5"
L["defaultRotation/rogue/pistol_shot"] = "Coup de pistolet"
L["defaultRotation/rogue/pistol_shot_anticipation"] = "Coup de pistolet (Anticipation)"
L["defaultRotation/rogue/pistol_shot_deeper_stratagem"] = "Coup de pistolet (Stratagème approfondi)"
L["defaultRotation/rogue/pistol_shot_quick_draw"] = "Coup de pistolet (Tireur rapide)"
L["defaultRotation/rogue/pistol_shot_quick_draw_anticipation"] = "Coup de pistolet (Tireur rapide (Anticipation))"
L["defaultRotation/rogue/pistol_shot_quick_draw_deeper_stratagem"] = "Coup de pistolet (Tireur Rapide (Stratagème approfondi))"
L["defaultRotation/rogue/roll_the_bones"] = "Jet d'osselets"
L["defaultRotation/rogue/roll_the_bones_deeper_stratagem"] = "Jet d'osselets (Stratagème approfondi)"
L["defaultRotation/rogue/run_through"] = "Percée"
L["defaultRotation/rogue/run_through_deeper_stratagem"] = "Percée (Stratagème approfondi)"
L["defaultRotation/rogue/rupture"] = "Rupture"
L["defaultRotation/rogue/rupture_deeper_stratagem"] = "Rupture (Stratagème approfondi)"
L["defaultRotation/rogue/saber_slash"] = "Coup de sabre"
L["defaultRotation/rogue/shadow_blades"] = "Lames de l'ombre"
L["defaultRotation/rogue/shadow_dance"] = "Danse de l'ombre"
L["defaultRotation/rogue/shadow_dance_symbols_of_death"] = "Danse de l'ombre (Symboles de mort)"
L["defaultRotation/rogue/shadowstrikes"] = "Frappe-ténèbres"
L["defaultRotation/rogue/shadowstrikes_premeditation"] = "Frappe-ténèbres (Préméditation)"
L["defaultRotation/rogue/shuriken_storm"] = "Tempête de shurikens"
L["defaultRotation/rogue/subtlety"] = "Finesse 7.1.5"
L["defaultRotation/rogue/subtlety_multi"] = "Finesse Multi 7.1.5"
L["defaultRotation/rogue/symbols_of_death"] = "Symboles de mort"
L["defaultRotation/rogue/vendetta"] = "Vendetta"
L["defaultRotation/shaman/ascendance"] = "Ascendance"
L["defaultRotation/shaman/boulderfist"] = "Rochepoing"
L["defaultRotation/shaman/boulderfist_2_charges"] = "Rochepoing (2 Charges)"
L["defaultRotation/shaman/boulderfist_landslide"] = "Rochepoing (Glissement de terrain)"
L["defaultRotation/shaman/chain_lightning"] = "Chaîne d'éclairs"
L["defaultRotation/shaman/cloudburst_totem"] = "Totem d'explosion nuageuse"
L["defaultRotation/shaman/crash_lightning"] = "Impact foudroyant"
L["defaultRotation/shaman/doom_winds"] = "Vents funestes"
L["defaultRotation/shaman/earth_shock"] = "Horion de terre"
L["defaultRotation/shaman/earthen_spike"] = "Pointe terrestre"
L["defaultRotation/shaman/earthquake"] = "Séisme"
L["defaultRotation/shaman/elemental"] = "Elémentaire 7.1.5"
L["defaultRotation/shaman/elemental_blast"] = "Explosion élémentaire"
L["defaultRotation/shaman/elemental_mastery"] = "Maîtrise élémentaire"
L["defaultRotation/shaman/elemental_multi"] = "Elémentaire Multi 7.1.5"
L["defaultRotation/shaman/enhancement"] = "Amélioration 7.1.5"
L["defaultRotation/shaman/enhancement_multi"] = "Amélioration Multi 7.1.5"
L["defaultRotation/shaman/feral_lunge"] = "Impulsion farouche"
L["defaultRotation/shaman/feral_spirit"] = "Esprit farouche"
L["defaultRotation/shaman/fire_elemental"] = "Elémentaire de feu"
L["defaultRotation/shaman/flame_shock"] = "Horion de flammes"
L["defaultRotation/shaman/flame_shock_elemental_focus"] = "Horion des flammes (Focalisation élémentaire)"
L["defaultRotation/shaman/flametongue"] = "Langue de feu"
L["defaultRotation/shaman/frost_shock"] = "Horion de givre"
L["defaultRotation/shaman/frostbrand"] = "Arme de givre"
L["defaultRotation/shaman/fury_of_air"] = "Fureur de l'Air"
L["defaultRotation/shaman/healing_rain"] = "Pluie guérisseuse"
L["defaultRotation/shaman/healing_stream_totem"] = "Totem guérisseur"
L["defaultRotation/shaman/icefury"] = "Furie-de-glace"
L["defaultRotation/shaman/lava_burst"] = "Explosion de lave"
L["defaultRotation/shaman/lava_burst_echo_of_the_elements"] = "Explosion de lave (Echo des éléments)"
L["defaultRotation/shaman/lava_burst_lava_surge"] = "Explosion de lave (Vague de lave)"
L["defaultRotation/shaman/lava_lash"] = "Fouet de lave"
L["defaultRotation/shaman/lava_lash_hot_hand"] = "Fouet de lave (Main brûlante)"
L["defaultRotation/shaman/lightning_bolt"] = "Eclair"
L["defaultRotation/shaman/lightning_bolt_overcharge"] = "Eclair (Surcharge)"
L["defaultRotation/shaman/lightning_bolt_power_of_the_maelstrom"] = "Eclair (Pouvoir du Maelström)"
L["defaultRotation/shaman/lightning_shield"] = "Bouclier de foudre"
L["defaultRotation/shaman/liquid_magma_totem"] = "Totem de magma liquide"
L["defaultRotation/shaman/purge"] = "Purge"
L["defaultRotation/shaman/rainfall"] = "Averse"
L["defaultRotation/shaman/restoration"] = "Restauration 7.1.5"
L["defaultRotation/shaman/restoration_multi"] = "Restauration Multi 7.1.5"
L["defaultRotation/shaman/rockbiter"] = "Croque-roc"
L["defaultRotation/shaman/rockbiter_landslide"] = "Croque-roc (Glissement de terrain)"
L["defaultRotation/shaman/stormkeeper"] = "Gardien des tempêtes"
L["defaultRotation/shaman/stormstrike"] = "Frappe-tempête"
L["defaultRotation/shaman/stormstrike_stormbringer"] = "Frappe-tempête (Porte-tempête)"
L["defaultRotation/shaman/sundering"] = "Fracture"
L["defaultRotation/shaman/totem_mastery"] = "Maîtrise des totems"
L["defaultRotation/shaman/wind_shear"] = "Cisaille de vent"
L["defaultRotation/shaman/windsong"] = "Chant-du-Vent"
L["defaultRotation/warlock/affliction"] = "Affliction 7.1.5"
L["defaultRotation/warlock/affliction_multi"] = "Affliction Multi 7.1.5"
L["defaultRotation/warlock/agony"] = "Agonie"
L["defaultRotation/warlock/call_dreadstalkers"] = "Appel des traqueffrois"
L["defaultRotation/warlock/cataclysm"] = "Cataclysme"
L["defaultRotation/warlock/cauterize_master"] = "Cautérisation du maître"
L["defaultRotation/warlock/channel_demonfire"] = "Canalisation de feu démoniaque"
L["defaultRotation/warlock/chaos_bolt"] = "Trait du chaos"
L["defaultRotation/warlock/chaos_bolt_5_soul_shards"] = "Trait du chaos (5 Eclats d'âme)"
L["defaultRotation/warlock/conflagrate"] = "Conflagration"
L["defaultRotation/warlock/conflagrate_roaring_blaze"] = "Conflagration (Brasier rugissant)"
L["defaultRotation/warlock/corruption"] = "Corruption"
L["defaultRotation/warlock/corruption_absolute_corruption"] = "Corruption (Corruption absolue)"
L["defaultRotation/warlock/demonic_empowerment"] = "Renforcement démoniaque"
L["defaultRotation/warlock/demonic_empowerment_call_dreadstalkers"] = "Renforcement démoniaque (Appel des traqueffrois)"
L["defaultRotation/warlock/demonic_empowerment_grimoire_felguard"] = "Renforcement démoniaque (Grimoire : Gangregarde)"
L["defaultRotation/warlock/demonic_empowerment_hand_of_guldan"] = "Renforcement démoniaque (Main de Gul'dan)"
L["defaultRotation/warlock/demonic_empowerment_summon_darkglare"] = "Renforcement démoniaque (Invocation de Regard-noir)"
L["defaultRotation/warlock/demonic_empowerment_summon_doomguard"] = "Renforcement démoniaque (Invocation : Garde funeste)"
L["defaultRotation/warlock/demonic_empowerment_summon_infernal"] = "Renforcement démoniaque (Invocation : Infernal)"
L["defaultRotation/warlock/demonology"] = "Démonologie 7.1.5"
L["defaultRotation/warlock/demonology_multi"] = "Démonologie Multi 7.1.5"
L["defaultRotation/warlock/demonwrath"] = "Courroux démoniaque"
L["defaultRotation/warlock/demonwrath_moving"] = "Courroux démoniaque (Mouvement)"
L["defaultRotation/warlock/destruction"] = "Destruction 7.1.5"
L["defaultRotation/warlock/destruction_multi"] = "Destruction Multi 7.1.5"
L["defaultRotation/warlock/dimensional_rift"] = "Faille dimensionnelle"
L["defaultRotation/warlock/doom"] = "Destin funeste"
L["defaultRotation/warlock/drain_life"] = "Drain de vie"
L["defaultRotation/warlock/drain_soul"] = "Drain d'âme"
L["defaultRotation/warlock/felstorm"] = "Gangrorage"
L["defaultRotation/warlock/grimoire_felguard"] = "Grimoire : Gangregarde"
L["defaultRotation/warlock/grimoire_felhunter"] = "Grimoire : Chasseur corrompu"
L["defaultRotation/warlock/grimoire_imp"] = "Grimoire : Diablotin"
L["defaultRotation/warlock/grimoire_of_sacrifice"] = "Grimoire de sacrifice"
L["defaultRotation/warlock/hand_of_guldan"] = "Main de Gul'dan"
L["defaultRotation/warlock/haunt"] = "Hanter"
L["defaultRotation/warlock/immolate"] = "Immolation"
L["defaultRotation/warlock/implosion"] = "Implosion"
L["defaultRotation/warlock/incinerate"] = "Incinérer"
L["defaultRotation/warlock/life_tap"] = "Connexion"
L["defaultRotation/warlock/life_tap_empowered_life_tap"] = "Connexion (Connexion surpuissante)"
L["defaultRotation/warlock/mortal_coil"] = "Voile de mort"
L["defaultRotation/warlock/phantom_singularity"] = "Singularité fantomatique"
L["defaultRotation/warlock/rain_of_fire"] = "Pluie de feu"
L["defaultRotation/warlock/rain_of_fire_5_sould_shards"] = "Pluie de feu (5 Eclats d'âme)"
L["defaultRotation/warlock/reap_souls"] = "Fauchage d'âmes"
L["defaultRotation/warlock/seed_of_corruption"] = "Graine de Corruption"
L["defaultRotation/warlock/shadow_bolt"] = "Trait de l'ombre"
L["defaultRotation/warlock/shadow_bolt_shadowy_inspiration"] = "Trait de l'ombre (Inspiration ténébreuse)"
L["defaultRotation/warlock/shadow_lock"] = "Verrou d'ombre"
L["defaultRotation/warlock/shadowburn"] = "Brûlure de l'ombre"
L["defaultRotation/warlock/shadowflame"] = "Ombreflamme"
L["defaultRotation/warlock/siphon_life"] = "Siphon de vie"
L["defaultRotation/warlock/soul_effigy"] = "Effigie de l'âme"
L["defaultRotation/warlock/soul_harvest"] = "Récolte d'âmes"
L["defaultRotation/warlock/spell_lock"] = "Verrou magique"
L["defaultRotation/warlock/summon_darkglare"] = "Invocation de Regard-noir"
L["defaultRotation/warlock/summon_doomguard"] = "Invocation : Garde funeste"
L["defaultRotation/warlock/summon_doomguard_grimoire_of_supremacy"] = "Invocation : Garde funeste (Grimoire de suprématie)"
L["defaultRotation/warlock/summon_felguard"] = "Invocation : gangregarde"
L["defaultRotation/warlock/summon_felhunter"] = "Invocation : chasseur corrompu"
L["defaultRotation/warlock/summon_imp"] = "Invocation : diablotin"
L["defaultRotation/warlock/summon_infernal"] = "Invocation : Infernal"
L["defaultRotation/warlock/summon_infernal_grimoire_of_supremacy"] = "Invocation : Infernal (Grimoire de suprématie)"
L["defaultRotation/warlock/thalkiel_consumption"] = "Consomption de Thal'kiel"
L["defaultRotation/warlock/unstable_affliction"] = "Affliction instable"
L["defaultRotation/warlock/unstable_affliction_3+_soul_shards"] = "Affliction instable (3+ Eclats d'âme)"
L["defaultRotation/warlock/unstable_affliction_contagion"] = "Affliction instable (Contagion)"
L["defaultRotation/warlock/unstable_affliction_second"] = "Affliction instable (Second)"
L["defaultRotation/warrior/arms"] = "Armes 7.1.5"
L["defaultRotation/warrior/arms_multi"] = "Armes Multi 7.1.5"
L["defaultRotation/warrior/avatar"] = "Avatar"
L["defaultRotation/warrior/battle_cry"] = "Cri de bataille"
L["defaultRotation/warrior/battle_cry_avatar"] = "Cri de bataille (Avatar)"
L["defaultRotation/warrior/battle_cry_ravager"] = "Cri de bataille (Ravageur)"
L["defaultRotation/warrior/battle_cry_reckless_abandon"] = "Cri de bataille (Fougue téméraire)"
L["defaultRotation/warrior/battle_cry_renewed_fury"] = "Cri de bataille (Regain de fureur)"
L["defaultRotation/warrior/berserker_rage"] = "Rage de berserker"
L["defaultRotation/warrior/bladestorm"] = "Tempête de lames"
L["defaultRotation/warrior/bloodbath"] = "Bain de sang"
L["defaultRotation/warrior/bloodthirst"] = "Sanguinaire"
L["defaultRotation/warrior/bloodthirst_enrage"] = "Sanguinaire (Enrager)"
L["defaultRotation/warrior/charge"] = "Charge"
L["defaultRotation/warrior/cleave"] = "Enchaînement"
L["defaultRotation/warrior/colossus_smash"] = "Frappe du colosse"
L["defaultRotation/warrior/devastate"] = "Dévaster"
L["defaultRotation/warrior/dragon_roar"] = "Rugissement de dragon"
L["defaultRotation/warrior/dragon_roar_berserker_rage"] = "Rugissement de dragon (Rage de berserker)"
L["defaultRotation/warrior/dragon_roar_rampage"] = "Rugissement de dragon (Saccager)"
L["defaultRotation/warrior/dragon_roar_rampage_carnage"] = "Rugissement de dragon (Saccager (Carnage))"
L["defaultRotation/warrior/dragon_roar_rampage_massacre"] = "Rugissement de dragon (Saccager (Massacre))"
L["defaultRotation/warrior/dragon_roar_rampage_rage"] = "Rugissement de dragon (Saccager (Rage))"
L["defaultRotation/warrior/execute"] = "Exécution"
L["defaultRotation/warrior/execute_massacre"] = "Exécution (Massacre)"
L["defaultRotation/warrior/execute_massacre_enrage"] = "Exécution (Massacre (Enrager))"
L["defaultRotation/warrior/focused_rage"] = "Rage concentrée"
L["defaultRotation/warrior/focused_rage_colossus_smash"] = "Rage concentrée (Frappe du colosse)"
L["defaultRotation/warrior/focused_rage_deadly_calm"] = "Rage concentrée (Sérénité meurtrière)"
L["defaultRotation/warrior/furious_slash"] = "Entaille furieuse"
L["defaultRotation/warrior/furious_slash_frenzy"] = "Entaille furieuse (Frénésie)"
L["defaultRotation/warrior/fury"] = "Fureur 7.1.5"
L["defaultRotation/warrior/fury_multi"] = "Fureur Multi 7.1.5"
L["defaultRotation/warrior/ignore_pain"] = "Dur au mal"
L["defaultRotation/warrior/ignore_pain_vengeance"] = "Dur au mal (Vengeance)"
L["defaultRotation/warrior/impending_victory"] = "Victoire imminente"
L["defaultRotation/warrior/intercept"] = "Interception"
L["defaultRotation/warrior/mortal_strike"] = "Frappe mortelle"
L["defaultRotation/warrior/neltharion_fury"] = "Fureur de Neltharion"
L["defaultRotation/warrior/odyn_fury"] = "Fureur d'Odyn"
L["defaultRotation/warrior/overpower"] = "Fulgurance"
L["defaultRotation/warrior/overpower_focused_rage"] = "Fulgurance (Rage concentrée)"
L["defaultRotation/warrior/protection"] = "Protection 7.1.5"
L["defaultRotation/warrior/protection_multi"] = "Protection Multi 7.1.5"
L["defaultRotation/warrior/pummel"] = "Volée de coups"
L["defaultRotation/warrior/raging_blow"] = "Coup déchainé"
L["defaultRotation/warrior/raging_blow_inner_rage"] = "Coup déchainé (Rage intérieure)"
L["defaultRotation/warrior/rampage"] = "Saccager"
L["defaultRotation/warrior/rampage_massacre"] = "Saccager (Massacre)"
L["defaultRotation/warrior/rampage_rage"] = "Saccager (Rage)"
L["defaultRotation/warrior/ravager"] = "Ravageur"
L["defaultRotation/warrior/rend"] = "Pourfendre"
L["defaultRotation/warrior/revenge"] = "Revanche"
L["defaultRotation/warrior/revenge_vengeance"] = "Revanche (Vengeance)"
L["defaultRotation/warrior/shield_block"] = "Maîtrise du blocage"
L["defaultRotation/warrior/shield_slam"] = "Heurt de bouclier"
L["defaultRotation/warrior/slam"] = "Heurtoir"
L["defaultRotation/warrior/slam_focused_rage"] = "Heurtoir (Rage concentrée)"
L["defaultRotation/warrior/thunder_clap"] = "Coup de tonnerre"
L["defaultRotation/warrior/victory_rush"] = "Ivresse de la victoire"
L["defaultRotation/warrior/warbreaker"] = "Brise-Guerre"
L["defaultRotation/warrior/whirlwind"] = "Tourbillon"
L["defaultRotation/warrior/whirlwind_focused_rage"] = "Tourbillon (Rage concentrée)"
L["defaultRotation/warrior/whirlwind_meat_cleaver"] = "Tourbillon (Fendoir à viande)"
L["message/core/fullCleanUp"] = "Nous avons nettoyé vos donnée de RotationBuilder avec cette nouvelle version. Ceci était requis parceque soit votre version était trop vielle et une erreur aurait pu apparaître, ou une nouvelle fonctionalité en avais besoin"
L["msg/action/keybinds/customCase/disabled"] = "Désactiver cas particulier : "
L["msg/action/keybinds/customCase/enabled"] = "Activer cas particulier : "
L["msg/action/keybinds/multiTarget/disabled"] = "Mode rotation multi-cibles désactivé"
L["msg/action/keybinds/multiTarget/enabled"] = "Mode rotation multi-cibles activé"
L["msg/action/switch_rotation"] = "Changement de la rotation pour : "
L["ROB_ACTION_MOVEDOWN_TT"] = "Déplacer l'action sélectionnée d'une position vers le bas"
L["ROB_ACTION_MOVEUP_TT"] = "Déplacer l'action sélectionnée d'une position vers le haut"
L["ROB_ACTION_REMOVE_TT"] = "Retirer l'action de la liste"
L["ROB_ADDON_NAME"] = "RotationBuilder"
L["ROB_AO_G_HasMinRangeCheckButton"] = "Le sort a une portée minimum"
L["ROB_AO_G_HasMinRangeCheckButton_TT"] = "N'affiche cette action que si la cible est plus loin que 8 mètres"
L["ROB_AO_G_SpellInRangeCheckButton"] = "Cible à porté"
L["ROB_AO_G_SpellInRangeCheckButton_TT"] = "N'affiche cette action que si la cible est à porté"
L["ROB_FRAME_CLOSE_TT"] = "Fermer la Fenêtre de Rotation Builder"
L["ROB_FRAME_OPTIONS_TT"] = "Montrer Options"
L["ROB_FRAME_ROTATIONS_TT"] = "Montrer Rotations"
L["ROB_LOADED"] = "Rotation Builder v%s chargé"
L["ROB_OPTION_ENEMY"] = "Cibles hostiles ou neutres"
L["ROB_OPTION_ENEMY_TT"] = "N'affiche les îcones que pour les cibles hostiles ou neutres"
L["ROB_OPTION_EXPORTBINDS"] = "Export des raccourcis"
L["ROB_OPTION_EXPORTBINDS_TT"] = "Ajoute l'export des raccourcis clavier à la fonction \"Exporter\""
L["ROB_OPTION_HIDECD"] = "Masquer les rechargements"
L["ROB_OPTION_HIDECD_TT"] = "Masque le temps de rechargements des techniques et les animations"
L["ROB_OPTION_ICONS"] = "Options de l'icone :"
L["ROB_OPTION_ICONS_C_A"] = "Transparence de l'action actuelle :"
L["ROB_OPTION_ICONS_CV"] = "1"
L["ROB_OPTION_ICONS_MAX"] = "3.5"
L["ROB_OPTION_ICONS_MIN"] = ".1"
L["ROB_OPTION_ICONS_N_A"] = "Transparence de la prochaine action :"
L["ROB_OPTION_ICONS_T_A"] = "Activer la transparence des icones :"
L["ROB_OPTION_ICONS_T_ATT"] = [=[Entrez une valeur entre |cFF00FF00.1|r et |cFF00FF00 1|r
pour régler le niveau de transparence de l'icone.
— |cFF00FF00 1|r pour que celle-ci soit plainement visible.
— |cFF00FF00 .1|r pour qu'elle soit pratiquement invisible.]=]
L["ROB_OPTION_ICONSCALE"] = "Taille de l'icone :"
L["ROB_OPTION_IMPORT"] = "Options d'Import/Export :"
L["ROB_OPTION_LOADDEFAULT"] = "Charger"
L["ROB_OPTION_LOADDEFAULT_TT"] = "Charge les rotations pas défaut de votre classe"
L["ROB_OPTION_LOCKICONS"] = "Vérouiller les icones"
L["ROB_OPTION_LOCKICONS_TT"] = "Vérouiller les icones pour éviter leur déplacement"
L["ROB_OPTION_MINIMAP"] = "Bouton de la Minimap :"
L["ROB_OPTION_MINIMAP_TT"] = "Activer le bouton de la Minimap"
L["ROB_OPTION_MINIMAPO"] = "Options de la Minimap :"
L["ROB_OPTION_MINIMAPPOS"] = "Position autour de la Minimap"
L["ROB_OPTION_MINIMAPRAD"] = "Rayon hors de la Minimap"
L["ROB_OPTION_MMPOS_CV"] = "300"
L["ROB_OPTION_MMPOS_MAX"] = "360"
L["ROB_OPTION_MMPOS_MIN"] = "1"
L["ROB_OPTION_MMRAD_CV"] = "80"
L["ROB_OPTION_MMRAD_MAX"] = "120"
L["ROB_OPTION_MMRAD_MIN"] = "1"
L["ROB_OPTION_NAIL"] = "Position de la prochaine action :"
L["ROB_OPTION_OVERWRITE"] = "Écraser"
L["ROB_OPTION_OVERWRITE_TT"] = "Autoriser l'écrasement de rotations existantes lors de l'import de rotations"
L["ROB_OPTION_RESETUI"] = "Réinitialiser l'interface"
L["ROB_OPTION_RESETUI_EXP"] = "Réinitialise la position des fenêtres de RotationBuilder au centre de l'écran"
L["ROB_OPTION_RESETUI_TT"] = "Réinitialiser la position des fenêtres de l'interface"
L["ROB_OPTION_UI"] = "Options d'interface :"
L["ROB_OPTION_UISCALE"] = "Échelle de l'interface"
L["ROB_OPTION_UISCALE_ADD"] = "+"
L["ROB_OPTION_UISCALE_MIN"] = "-"
L["ROB_OPTION_UPDATERATE"] = "Rafraichissement pas secondes :"
L["ROB_OPTION_UPDATERATE_CV"] = "5"
L["ROB_OPTION_UPDATERATE_MAX"] = "10"
L["ROB_OPTION_UPDATERATE_MIN"] = "1"
L["ROB_PROMPT_LIST_DELETE"] = "Êtes vous sûr de vouloir la supprimer ?"
L["ROB_UI_A_ADD"] = "Ajouter"
L["ROB_UI_A_ADD_TT"] = "Ajouter une nouvelle action dans la rotation"
L["ROB_UI_A_COPY"] = "Copier"
L["ROB_UI_A_COPY_TT"] = "Copier l'action sélectionnée dans le presse-papier"
L["ROB_UI_A_PASTE"] = "Coller"
L["ROB_UI_A_PASTE_TT"] = "Coller l'action copiée du presse-papier vers la rotation"
L["ROB_UI_ACTION_COLUMN"] = "Actions"
L["ROB_UI_ADD_ACTION_CFAIL"] = "Les noms d'action ne peuvent utiliser les caractères suivant : [],="
L["ROB_UI_ADD_ROTATION_CFAIL"] = "Les noms de rotation ne peuvent utiliser les caractères suivant : [],"
L["ROB_UI_AO_G_CHARGES"] = "Charges du sort:"
L["ROB_UI_AO_G_CHARGES_TT"] = [=[Cochez cette option pour vérifier le nombre de charges du sort
Ceci est utilisé pour calculer la prochaine action disponible]=]
L["ROB_UI_AO_G_CHARGESIB_TT"] = [=[Entrez le nombre de charges
Example: |cFF00FF001|r]=]
L["ROB_UI_AO_G_DEBUG"] = "Debug"
L["ROB_UI_AO_G_DEBUG_TT"] = "Active les message de debug pour cette action"
L["ROB_UI_AO_G_DISABLE"] = "Désactiver"
L["ROB_UI_AO_G_DISABLE_TT"] = "Désactive cette action quand on ne veut pas la supprimer"
L["ROB_UI_AO_G_DURATION"] = "Attendre avant de relancer:"
L["ROB_UI_AO_G_DURATION_TT"] = [=[Attendre le nombre de secondes indiqué avant de relancer cette action
Utile pour donner le temps aux sort en vol d'atteindre leur cible avant de calculer l'action suivante]=]
L["ROB_UI_AO_G_DURATIONIB_TT"] = "Entrez le nombre de secondes avant de réafficher cette action"
L["ROB_UI_AO_G_GSPELLCOST"] = "Coûte des ressources:"
L["ROB_UI_AO_G_GSPELLCOST_TT"] = [=[Cochez cette option si l'action utilise une ressource
Ceci est utilisé pour calculer la prochaine action disponible]=]
L["ROB_UI_AO_G_GSPELLCOST1_TT"] = [=[Entrez le type de ressource
|cFF00FF000|r=MANA |cFF00FF001|r=RAGE |cFF00FF002|r=FOCALISATION |cFF00FF003|r=ENERGIE  |cFF00FF004|r=POINTS DE COMBO |cFF00FF006|r=PUISSANCE RUNIQUE |cFF00FF007|r=ECLATS D'AME
|cFF00FF008|r=PUISSANCE ASTRALE |cFF00FF009|r=PUISSANCE SACRE |cFF00FF0011|r=MAELSTROM |cFF00FF0012|r=CHI |cFF00FF0013|r=DEMENCE |cFF00FF0016|r=PUISSANCE DES ARCANES
|cFF00FF0017|r=FUREUR  |cFF00FF0018|r=SOUFFRANCE]=]
L["ROB_UI_AO_G_GSPELLCOST2_TT"] = [=[Entrez la quantitée de ressource
Example1: |cFF00FF003|r
Example2: |cFF00FF0090%|r]=]
L["ROB_UI_AO_G_GUNITPOWER"] = "Génère des ressources:"
L["ROB_UI_AO_G_GUNITPOWER_TT"] = [=[Coché cette option si l'action génère des ressources
Ceci est utilisé pour calculer la prochaine action disponible]=]
L["ROB_UI_AO_G_GUNITPOWER1_TT"] = [=[Entrez le type de ressource
|cFF00FF000|r=MANA |cFF00FF001|r=RAGE |cFF00FF002|r=FOCALISATION |cFF00FF003|r=ENERGIE  |cFF00FF004|r=POINTS DE COMBO |cFF00FF006|r=PUISSANCE RUNIQUE |cFF00FF007|r=ECLATS D'AME
|cFF00FF008|r=PUISSANCE ASTRALE |cFF00FF009|r=PUISSANCE SACRE |cFF00FF0011|r=MAELSTROM |cFF00FF0012|r=CHI |cFF00FF0013|r=DEMENCE |cFF00FF0016|r=PUISSANCE DES ARCANES
|cFF00FF0017|r=FUREUR  |cFF00FF0018|r=SOUFFRANCE]=]
L["ROB_UI_AO_G_GUNITPOWER2_TT"] = [=[Entrez la quantitée de ressource
Example1: |cFF00FF003|r
Example2: |cFF00FF0090%|r]=]
L["ROB_UI_AO_G_HASPROC"] = "A un proc"
L["ROB_UI_AO_G_HASPROC_TT"] = "N'affiche l'action que si elle a un proc"
L["ROB_UI_AO_G_ICON_L"] = "Icône:"
L["ROB_UI_AO_G_ICON_TT"] = [=[Entrez le nom/id du sort dont vous voulez afficher l'icône
Le nom du sort sera utiliser si cette case reste vide]=]
L["ROB_UI_AO_G_INCOMBAT"] = "En combat"
L["ROB_UI_AO_G_INCOMBAT_TT"] = "N'affiche l'action que si le joueur est en combat"
L["ROB_UI_AO_G_LASTCAST"] = "Dernier sort lancé:"
L["ROB_UI_AO_G_LASTCAST_TT"] = "N'affiche l'action que si ceci était le dernier sort lancé"
L["ROB_UI_AO_G_LASTCASTIB_TT"] = "Entrez le nom/id du dernier sort lancé"
L["ROB_UI_AO_G_MAXCASTS"] = "Max d'utilisation séquentielle:"
L["ROB_UI_AO_G_MAXCASTS_TT"] = "N'affiche cette action que X fois de suite"
L["ROB_UI_AO_G_MAXCASTSIB_TT"] = "Entrez le nombre de succession"
L["ROB_UI_AO_G_MOVING"] = "En mouvement"
L["ROB_UI_AO_G_MOVING_TT"] = "N'affiche l'action que si le joueur est en mouvement"
L["ROB_UI_AO_G_NMOVING"] = "A l'arrêt"
L["ROB_UI_AO_G_NMOVING_TT"] = "N'affiche l'action que si le joueur ne bouge pas"
L["ROB_UI_AO_G_NOTINCOMBAT"] = "Hors combat"
L["ROB_UI_AO_G_NOTINCOMBAT_TT"] = "N'affiche l'action que si le joueur est hors combat"
L["ROB_UI_AO_G_NOTINSPELLBOOK"] = "Pas un sort du personnage"
L["ROB_UI_AO_G_NOTINSPELLBOOK_TT"] = [=[N'affiche l'action que si le sort n'est pas un sort de votre personnage
Example : Si c'est un sort de familier (familier du chasseur, démon du démoniste, élémentaire d'eau du mage, ...]=]
L["ROB_UI_AO_G_NOTSPELL"] = "Pas un sort"
L["ROB_UI_AO_G_NOTSPELL_TT"] = [=[Ignore les conditions de ressources, utilisez juste votre objet
Utilisez ceci quand le nom est Trinket0Slot ou HandsSlot, ...]=]
L["ROB_UI_AO_G_OTHERCD"] = "Cooldown d'un autre sort:"
L["ROB_UI_AO_G_OTHERCD_TT"] = "N'affiche cette action que si le cooldown de l'autre sort à les conditions requises"
L["ROB_UI_AO_G_OTHERCDNIB_TT"] = "Entrez le nom/id du sort dont le cooldown doit être vérifié"
L["ROB_UI_AO_G_OTHERCDVIB_TT"] = [=[Entrez la valeur du cooldown à vérifier
Example1: |cFF00FF00<3|r n'affiche l'action que si le cooldown est inférieur à 3 secondes
Example2: |cFF00FF00>3|r n'affiche l'action que si le cooldown est supérieur à 3 secondes
Example3: |cFF00FF00<=3|r  n'affiche l'action que si le cooldown est inférieur ou égal à 3 secondes
Example4: |cFF00FF00=3|r  n'affiche l'action que si le cooldown est strictement égal à 3 secondes]=]
L["ROB_UI_AO_G_OTHERCHARGES"] = "Charges d'un autre sort:"
L["ROB_UI_AO_G_OTHERCHARGES_TT"] = [=[Cochez cette option pour vérifier les charges d'un autre sort
Ceci est utilisé pour calculé la prochaine action disponible]=]
L["ROB_UI_AO_G_OTHERCHARGESNIB_TT"] = "Entrez le nom/id du sort pour lequel vérifier les charges"
L["ROB_UI_AO_G_SID_VFAIL"] = "Sort ou Emplacement non trouvé"
L["ROB_UI_AO_G_SPELLNAME_L"] = [=[Nom de sort
ou emplacement d'inventaire :]=]
L["ROB_UI_AO_G_SPELLNAME_TT"] = [=[Entrez le nom d'un sort ou d'un emplacement d'inventaire
Exemple 1 : |cFF00FF00Trinket0Slot|r pour le premier emplacement de bijou
Exemple 2 : |cFF00FF00Trinket1Slot|r pour le second emplacement de bijou
Exemple 3 : |cFF00FF00HandsSlot|r
Exemple 4 : |cFF00FF00Grondement|r
Exemple 5 : |cFF00FF0089;7|r id pour Grondement]=]
L["ROB_UI_AO_GENERAL_LABEL"] = "Options General :"
L["ROB_UI_AO_GENERAL_TAB"] = "General"
L["ROB_UI_AO_P_HAVEBUFF"] = "A le buff:"
L["ROB_UI_AO_P_HAVEBUFF_TT"] = "N'affiche cette action que si le joueur a le(s) buff(s) spécifié(s)"
L["ROB_UI_AO_P_HAVEBUFFIB_TT"] = [=[Entrez le(s) nom/id(s) du(des) buff(s)
Syntaxe: |cFF00FF00| |r= OU |cFF00FF00&|r = ET |cFF00FF00_|r = placé par le joueur |cFF00FF00#|r = nombre de cumul |cFF00FF00^|r = rafraichir à x secondes
Example1: |cFF00FF00Earth Shield#2|r n'affiche cette action que si le joueur a le buff Earth Shield avec 2 cumuls
Example2: |cFF00FF00_Earth Shield#2|r n'affiche cette action que si le joueur a le buff Earth Shield avec 2 cumul placé par vous
Example3: |cFF00FF00_Earth Shield#2^3|r n'affiche cette action que si le joueur a le buff Earth Shield avec 2 cumul placé par vous avec 3+ secondes restantes
Example4: |cFF00FF00Earth Shield||Inner Fire|r n'affiche cette action que si le joueur a le buff Earth Shield ou Inner Fire
Example5: |cFF00FF00Earth Shield&Inner Fire|r n'affiche cette action que si le joueur a les buffs Earth Shield et Inner Fire]=]
L["ROB_UI_AO_P_HAVEDB"] = "A le debuff:"
L["ROB_UI_AO_P_HAVEDB_TT"] = "N'affiche cette action que si le joueur a le(s) debuff(s) spécifié(s)"
L["ROB_UI_AO_P_HAVEDBIB_TT"] = [=[Entrez le(s) nom/id(s) du(des) debuff(s)
Syntaxe: |cFF00FF00| |r= OU |cFF00FF00&|r = ET |cFF00FF00_|r = placé par le joueur |cFF00FF00#|r = nombre de cumul |cFF00FF00^|r = rafraichir à x secondes
Example1: |cFF00FF00Dark Plague#2|r n'affiche cette action que si le joueur a le debuff Dark Plague avec 2 cumuls
Example2: |cFF00FF00_Dark Plague#2|r n'affiche cette action que si le joueur a le debuff Dark Plague avec 2 cumul placé par vous
Example3: |cFF00FF00_Dark Plague#2^3|r n'affiche cette action que si le joueur a le debuff Dark Plague avec 2 cumul placé par vous avec 3+ secondes restantes
Example4: |cFF00FF00Dark Plague|Forbearance|r n'affiche cette action que si le joueur a le debuff Dark Plague ou Forbearance
Example5: |cFF00FF00Dark Plague&Forbearance|r n'affiche cette action que si le joueur a les debuffs Dark Plague et Forbearance]=]
L["ROB_UI_AO_P_HP"] = "HP:"
L["ROB_UI_AO_P_HP_TT"] = "N'affiche cette action que si le joueur à la quantitée spécifiée de vie"
L["ROB_UI_AO_P_HPIB_TT"] = [=[Entrez la valeur de vie à vérifier
Example1: |cFF00FF00<90%|r n'affiche l'action que si le joueur à moins de 90% de vie
Example2: |cFF00FF00>90%|r n'affiche l'action que si le joueur à plus de 90% de vie
Example3: |cFF00FF00<=90%|r n'affiche l'action que si le joueur à moins ou tout juste 90% de vie
Example4: |cFF00FF00>=90%|r n'affiche l'action que si le joueur à plus ou tout juste 90% de vie
Example5: |cFF00FF00=90%|r n'affiche l'action que si le joueur à tout juste 90% de vie]=]
L["ROB_UI_AO_P_ISSTEALTHED"] = "Camouflé"
L["ROB_UI_AO_P_ISSTEALTHED_TT"] = "N'affiche l'action que lorsque le joueur est camouflé"
L["ROB_UI_AO_P_KNOWNOTSPELL"] = "Ne connait pas le sort"
L["ROB_UI_AO_P_KNOWNOTSPELL_TT"] = "N'affiche cette action que si le sort/talent n'est pas connu"
L["ROB_UI_AO_P_KNOWNOTSPELLIB_TT"] = "Entrez le nom/id du sort à vérifier"
L["ROB_UI_AO_P_KNOWSPELL"] = "Connait le sort"
L["ROB_UI_AO_P_KNOWSPELL_TT"] = "N'affiche cette action que si le sort/talent est connu"
L["ROB_UI_AO_P_KNOWSPELLIB_TT"] = "Entrez le nom/id du sort à vérifier"
L["ROB_UI_AO_P_NEEDBUFF"] = "A besoin du buff:"
L["ROB_UI_AO_P_NEEDBUFF_TT"] = "N'affiche cette action que si le joueur n'a pas le(s) buff(s) spécifié(s)"
L["ROB_UI_AO_P_NEEDBUFFIB_TT"] = [=[Entrez le(s) nom/id(s) du(des) buff(s)
Syntaxe: |cFF00FF00| |r= OU |cFF00FF00&|r = ET |cFF00FF00_|r = placé par le joueur |cFF00FF00#|r = nombre de cumul |cFF00FF00^|r = rafraichir à x secondes
Example1: |cFF00FF00Earth Shield#2|r n'affiche cette action que si le joueur a besoin du buff Earth Shield avec 2 cumuls
Example2: |cFF00FF00_Earth Shield#2|r n'affiche cette action que si le joueur a besoin du buff Earth Shield avec 2 cumul placé par vous
Example3: |cFF00FF00_Earth Shield#2^3|r n'affiche cette action que si le joueur a besoin du buff Earth Shield avec 2 cumul placé par vous avec 3+ secondes restantes
Example4: |cFF00FF00Earth Shield||Inner Fire|r n'affiche cette action que si le joueur a besoin du buff Earth Shield ou Inner Fire
Example5: |cFF00FF00Earth Shield&Inner Fire|r n'affiche cette action que si le joueur a besoin des buffs Earth Shield et Inner Fire]=]
L["ROB_UI_AO_P_NEEDDB"] = "A besoin du debuff:"
L["ROB_UI_AO_P_NEEDDB_TT"] = "N'affiche cette action que si le joueur n'a pas le(s) debuff(s) spécifié(s)"
L["ROB_UI_AO_P_NEEDDBIB_TT"] = [=[Entrez le(s) nom/id(s) du(des) debuff(s)
Syntaxe: |cFF00FF00| |r= OU |cFF00FF00&|r = ET |cFF00FF00_|r = placé par le joueur |cFF00FF00#|r = nombre de cumul |cFF00FF00^|r = rafraichir à x secondes
Example1: |cFF00FF00Dark Plague#2|r n'affiche cette action que si le joueur a besoin du debuff Dark Plague avec 2 cumuls
Example2: |cFF00FF00_Dark Plague#2|r n'affiche cette action que si le joueur a besoin du debuff Dark Plague avec 2 cumul placé par vous
Example3: |cFF00FF00_Dark Plague#2^3|r n'affiche cette action que si le joueur a besoin du debuff Dark Plague avec 2 cumul placé par vous avec 3+ secondes restantes
Example4: |cFF00FF00Dark Plague|Forbearance|r n'affiche cette action que si le joueur a besoin du debuff Dark Plague ou Forbearance
Example5: |cFF00FF00Dark Plague&Forbearance|r n'affiche cette action que si le joueur a besoin des debuffs Dark Plague et Forbearance]=]
L["ROB_UI_AO_P_POWER"] = "Ressource:"
L["ROB_UI_AO_P_POWER_TT"] = "N'affiche cette action que quand le joueur a la quantitée de ressource spécifiée"
L["ROB_UI_AO_P_POWER1_TT"] = [=[Entrez le type de ressource
|cFF00FF000|r=MANA |cFF00FF001|r=RAGE |cFF00FF002|r=FOCALISATION |cFF00FF003|r=ENERGIE  |cFF00FF004|r=POINTS DE COMBO |cFF00FF006|r=PUISSANCE RUNIQUE |cFF00FF007|r=ECLATS D'AME
|cFF00FF008|r=PUISSANCE ASTRALE |cFF00FF009|r=PUISSANCE SACRE |cFF00FF0011|r=MAELSTROM |cFF00FF0012|r=CHI |cFF00FF0013|r=DEMENCE |cFF00FF0016|r=PUISSANCE DES ARCANES
|cFF00FF0017|r=FUREUR  |cFF00FF0018|r=SOUFFRANCE]=]
L["ROB_UI_AO_P_POWER2"] = "Ressource 2:"
L["ROB_UI_AO_P_POWER2_TT"] = [=[Entez la quantitée de ressources requise
Example1: |cFF00FF00>20|r
Example2: |cFF00FF00<=20|r
Example3: |cFF00FF00=20|r
Example4: |cFF00FF00<90%|r]=]
L["ROB_UI_AO_P_RUNES"] = "Runes:"
L["ROB_UI_AO_P_RUNES_TT"] = "N'affiche cette action que quand le joueur a le nombre spécifié de runes"
L["ROB_UI_AO_P_RUNESIB_TT"] = [=[Entrez le nombre de runes
Example1: |cFF00FF00>1|r n'affiche l'action que quand le joueur à plus d'une rune
Example2: |cFF00FF00<=1|r n'affiche l'action que quand le joueur à une rune ou moins
Example3: |cFF00FF00>=1|r n'affiche l'action que quand le joueur à une rune ou plus]=]
L["ROB_UI_AO_PET_HAVEBUFF"] = "A le buff:"
L["ROB_UI_AO_PET_HAVEBUFF_TT"] = "N'affiche cette action que si le familier a le(s) buff(s) spécifié(s)"
L["ROB_UI_AO_PET_HAVEBUFFIB_TT"] = [=[Entrez le(s) nom/id(s) du(des) buff(s)
Syntaxe: |cFF00FF00| |r= OU |cFF00FF00&|r = ET |cFF00FF00_|r = placé par le joueur |cFF00FF00#|r = nombre de cumul |cFF00FF00^|r = rafraichir à x secondes
Example1: |cFF00FF00Earth Shield#2|r n'affiche cette action que si le familier a le buff Earth Shield avec 2 cumuls
Example2: |cFF00FF00_Earth Shield#2|r n'affiche cette action que si le familier a le buff Earth Shield avec 2 cumul placé par vous
Example3: |cFF00FF00_Earth Shield#2^3|r n'affiche cette action que si le familier a le buff Earth Shield avec 2 cumul placé par vous avec 3+ secondes restantes
Example4: |cFF00FF00Earth Shield||Inner Fire|r n'affiche cette action que si le familier a le du buff Earth Shield ou Inner Fire
Example5: |cFF00FF00Earth Shield&Inner Fire|r n'affiche cette action que si le familier a les buffs Earth Shield et Inner Fire]=]
L["ROB_UI_AO_PET_HP_TT"] = "N'affiche cette action que si le familier à la quantitée spécifiée de vie"
L["ROB_UI_AO_PET_HPIB_TT"] = [=[Entrez la valeur de vie à vérifier
Example1: |cFF00FF00<90%|r n'affiche l'action que si le familier à moins de 90% de vie
Example2: |cFF00FF00>90%|r n'affiche l'action que si le familier à plus de 90% de vie
Example3: |cFF00FF00<=90%|r n'affiche l'action que si le familier à moins ou tout juste 90% de vie
Example4: |cFF00FF00>=90%|r n'affiche l'action que si le familier à plus ou tout juste 90% de vie
Example5: |cFF00FF00=90%|r n'affiche l'action que si le familier à tout juste 90% de vie]=]
L["ROB_UI_AO_PET_NEEDBUFF"] = "A besoin du buff:"
L["ROB_UI_AO_PET_NEEDBUFF_TT"] = "N'affiche cette action que si le familier n'a pas le(s) buff(s) spécifié(s)"
L["ROB_UI_AO_PET_NEEDBUFFIB_TT"] = [=[Entrez le(s) nom/id(s) du(des) buff(s)
Syntaxe: |cFF00FF00| |r= OU |cFF00FF00&|r = ET |cFF00FF00_|r = placé par le joueur |cFF00FF00#|r = nombre de cumul |cFF00FF00^|r = rafraichir à x secondes
Example1: |cFF00FF00Earth Shield#2|r n'affiche cette action que si le familier a besoin du buff Earth Shield avec 2 cumuls
Example2: |cFF00FF00_Earth Shield#2|r n'affiche cette action que si le familier a besoin du buff Earth Shield avec 2 cumul placé par vous
Example3: |cFF00FF00_Earth Shield#2^3|r n'affiche cette action que si le familier a besoin du buff Earth Shield avec 2 cumul placé par vous avec 3+ secondes restantes
Example4: |cFF00FF00Earth Shield||Inner Fire|r n'affiche cette action que si le familier a besoin du buff Earth Shield ou Inner Fire
Example5: |cFF00FF00Earth Shield&Inner Fire|r n'affiche cette action que si le familier a besoin des buffs Earth Shield et Inner Fire]=]
L["ROB_UI_AO_PET_TAB"] = "Familier"
L["ROB_UI_AO_PLAYER_TAB"] = "Joueur"
L["ROB_UI_AO_T_BOSS"] = "Boss"
L["ROB_UI_AO_T_BOSS_TT"] = "N'affiche cette action que si la cible est un boss"
L["ROB_UI_AO_T_DISPEL"] = "Dissipation"
L["ROB_UI_AO_T_DISPEL_TT"] = "N'affiche cette action que si la cible à un buff dissipable"
L["ROB_UI_AO_T_HAVEBUFF"] = "A le buff:"
L["ROB_UI_AO_T_HAVEBUFF_TT"] = "N'affiche cette action que si la cible a le(s) buff(s) spécifié(s)"
L["ROB_UI_AO_T_HAVEBUFFIB_TT"] = [=[Entrez le(s) nom/id(s) du(des) buff(s)
Syntaxe: |cFF00FF00| |r= OU |cFF00FF00&|r = ET |cFF00FF00_|r = placé par le joueur |cFF00FF00#|r = nombre de cumul |cFF00FF00^|r = rafraichir à x secondes
Example1: |cFF00FF00Earth Shield#2|r n'affiche cette action que si la cible a le buff Earth Shield avec 2 cumuls
Example2: |cFF00FF00_Earth Shield#2|r n'affiche cette action que si la cible a le buff Earth Shield avec 2 cumul placé par vous
Example3: |cFF00FF00_Earth Shield#2^3|r n'affiche cette action que si la cible a le buff Earth Shield avec 2 cumul placé par vous avec 3+ secondes restantes
Example4: |cFF00FF00Earth Shield||Inner Fire|r n'affiche cette action que si la cible a le du buff Earth Shield ou Inner Fire
Example5: |cFF00FF00Earth Shield&Inner Fire|r n'affiche cette action que si la cible a les buffs Earth Shield et Inner Fire]=]
L["ROB_UI_AO_T_HAVEDB"] = "A le debuff:"
L["ROB_UI_AO_T_HAVEDB_TT"] = "N'affiche cette action que si la cible a le(s) debuff(s) spécifié(s)"
L["ROB_UI_AO_T_HAVEDBIB_TT"] = [=[Entrez le(s) nom/id(s) du(des) debuff(s)
Syntaxe: |cFF00FF00| |r= OU |cFF00FF00&|r = ET |cFF00FF00_|r = placé par le joueur |cFF00FF00#|r = nombre de cumul |cFF00FF00^|r = rafraichir à x secondes
Example1: |cFF00FF00Dark Plague#2|r n'affiche cette action que si la cible a le debuff Dark Plague avec 2 cumuls
Example2: |cFF00FF00_Dark Plague#2|r n'affiche cette action que si la cible a le debuff Dark Plague avec 2 cumul placé par vous
Example3: |cFF00FF00_Dark Plague#2^3|r n'affiche cette action que si la cible a le debuff Dark Plague avec 2 cumul placé par vous avec 3+ secondes restantes
Example4: |cFF00FF00Dark Plague|Forbearance|r n'affiche cette action que si la cible a le debuff Dark Plague ou Forbearance
Example5: |cFF00FF00Dark Plague&Forbearance|r n'affiche cette action que si la cible a les debuffs Dark Plague et Forbearance]=]
L["ROB_UI_AO_T_HP_TT"] = "N'affiche cette action que si la cible à la quantitée spécifiée de vie"
L["ROB_UI_AO_T_HPIB_TT"] = [=[Entrez la valeur de vie à vérifier
Example1: |cFF00FF00<90%|r n'affiche l'action que si la cible à moins de 90% de vie
Example2: |cFF00FF00>90%|r n'affiche l'action que si la cible à plus de 90% de vie
Example3: |cFF00FF00<=90%|r n'affiche l'action que si la cible à moins ou tout juste 90% de vie
Example4: |cFF00FF00>=90%|r n'affiche l'action que si la cible à plus ou tout juste 90% de vie
Example5: |cFF00FF00=90%|r n'affiche l'action que si la cible à tout juste 90% de vie]=]
L["ROB_UI_AO_T_INTERRUPT"] = "Interruption"
L["ROB_UI_AO_T_INTERRUPT_TT"] = "N'affiche cette action que si la cible lance un sort interruptible"
L["ROB_UI_AO_T_NEEDBUFF"] = "A besoin du buff:"
L["ROB_UI_AO_T_NEEDBUFF_TT"] = "N'affiche cette action que si la cible n'a pas le(s) buff(s) spécifié(s)"
L["ROB_UI_AO_T_NEEDBUFFIB_TT"] = [=[Entrez le(s) nom/id(s) du(des) buff(s)
Syntaxe: |cFF00FF00| |r= OU |cFF00FF00&|r = ET |cFF00FF00_|r = placé par le joueur |cFF00FF00#|r = nombre de cumul |cFF00FF00^|r = rafraichir à x secondes
Example1: |cFF00FF00Earth Shield#2|r n'affiche cette action que si la cible a besoin du buff Earth Shield avec 2 cumuls
Example2: |cFF00FF00_Earth Shield#2|r n'affiche cette action que si la cible a besoin du buff Earth Shield avec 2 cumul placé par vous
Example3: |cFF00FF00_Earth Shield#2^3|r n'affiche cette action que si la cible a besoin du buff Earth Shield avec 2 cumul placé par vous avec 3+ secondes restantes
Example4: |cFF00FF00Earth Shield||Inner Fire|r n'affiche cette action que si la cible a besoin du buff Earth Shield ou Inner Fire
Example5: |cFF00FF00Earth Shield&Inner Fire|r n'affiche cette action que si la cible a besoin des buffs Earth Shield et Inner Fire]=]
L["ROB_UI_AO_T_NEEDDB"] = "A besoin du debuff:"
L["ROB_UI_AO_T_NEEDDB_TT"] = "N'affiche cette action que si la cible n'a pas le(s) debuff(s) spécifié(s)"
L["ROB_UI_AO_T_NEEDDBIB_TT"] = [=[Entrez le(s) nom/id(s) du(des) debuff(s)
Syntaxe: |cFF00FF00| |r= OU |cFF00FF00&|r = ET |cFF00FF00_|r = placé par le joueur |cFF00FF00#|r = nombre de cumul |cFF00FF00^|r = rafraichir à x secondes
Example1: |cFF00FF00Dark Plague#2|r n'affiche cette action que si la cible a besoin du debuff Dark Plague avec 2 cumuls
Example2: |cFF00FF00_Dark Plague#2|r n'affiche cette action que si la cible a besoin du debuff Dark Plague avec 2 cumul placé par vous
Example3: |cFF00FF00_Dark Plague#2^3|r n'affiche cette action que si la cible a besoin du debuff Dark Plague avec 2 cumul placé par vous avec 3+ secondes restantes
Example4: |cFF00FF00Dark Plague|Forbearance|r n'affiche cette action que si la cible a besoin du debuff Dark Plague ou Forbearance
Example5: |cFF00FF00Dark Plague&Forbearance|r n'affiche cette action que si la cible a besoin des debuffs Dark Plague et Forbearance]=]
L["ROB_UI_AO_T_NOTABOSS"] = "N'est pas un boss"
L["ROB_UI_AO_T_NOTABOSS_TT"] = "N'affiche cette action que si la cible n'est pas un boss"
L["ROB_UI_AO_T_SPELLSTEAL"] = "Vol de sort"
L["ROB_UI_AO_T_SPELLSTEAL_TT"] = "N'affiche cette action que si la cible à un buff volable"
L["ROB_UI_AO_TARGET_TAB"] = "Cible"
L["ROB_UI_CANCEL_BUTTON"] = "Annuler"
L["ROB_UI_CLOSE_BUTTON"] = "Fermer"
L["ROB_UI_CREATE"] = "Créer"
L["ROB_UI_CREATE_TT"] = "Créer une nouvelle rotation"
L["ROB_UI_DEBUG_E1"] = "N'affiche pas l'action : "
L["ROB_UI_DEBUG_E2"] = "L'action : "
L["ROB_UI_DEBUG_PREFIX"] = "Debug : "
L["ROB_UI_DELETE"] = "Supprimer"
L["ROB_UI_DELETE_TT"] = "Supprimer rotation sélectionnée"
L["ROB_UI_DISCARD"] = "Annuler"
L["ROB_UI_DISCARD_TT"] = "Annuler les modifications de la rotation sélectionnée"
L["ROB_UI_EXPORT"] = "Exporter"
L["ROB_UI_EXPORT_MESSAGE"] = "Pressez CTRL+C pour copier la rotation dans le presse-papier afin de la coller (CTRL+V) plus tard."
L["ROB_UI_EXPORT_TT"] = "Exporter la rotation"
L["ROB_UI_IMPORT"] = "Importer"
L["ROB_UI_IMPORT_ERROR1"] = "Échec de l'importation : aucun nom trouvé pour la rotation."
L["ROB_UI_IMPORT_ERROR2"] = "Échec de l'importation : une rotation existe déjà avec le même nom."
L["ROB_UI_IMPORT_ERROR3"] = "Échec de l'importation : la chaîne de caractères collée ne correspond pas au format d'export de « Rotation Builder »."
L["ROB_UI_IMPORT_MESSAGE"] = "Pressez CTRL+V pour coller ici la chaîne de caractères représentant une rotation copier à partir d'une autre source :"
L["ROB_UI_IMPORT_SUCCESS"] = "Importation réussie"
L["ROB_UI_IMPORT_TT"] = "Importer une rotation"
L["ROB_UI_LDB_TT1"] = "<Clic Droit> pour ouvrir Rotation Builder"
L["ROB_UI_LDB_TT2"] = "<Clic Gauche> pour sélectionner une Rotation"
L["ROB_UI_MODIFY"] = "Modifier"
L["ROB_UI_MODIFY_TT"] = "Modifier rotation sélectionnée"
L["ROB_UI_OK_BUTTON"] = "Ok"
L["ROB_UI_OPTIONS_TAB"] = "Options"
L["ROB_UI_PRESSKEY"] = "Appuyez sur une touche"
L["ROB_UI_RCOLUMNHEADER"] = "Rotations"
L["ROB_UI_RN_LABEL"] = "Nom de la Rotation:"
L["ROB_UI_ROTATION_E1"] = "Aucune rotation n'est spécifié pour ce raccourcie"
L["ROB_UI_ROTATION_E2"] = "La Rotation n'a pas été trouvé"
L["ROB_UI_ROTATION_TAB"] = "Rotations"
L["ROB_UI_RS_LABEL"] = "Rotation Spécialisation :"
L["ROB_UI_SAVE"] = "Sauvegarder"
L["ROB_UI_SAVE_TT"] = "Sauvegarder rotation sélectionnée"
L["ROB_UI_TITLE"] = "Rotation Builder"
L["ROB_UI_TOGGLE"] = "Ouvrir la fenêtre des options de Rotation Builder"
L["ROB_UI_VERSION_LABEL"] = "Version :"
L["ui/keybinds/toggleCustomCase/text"] = "Activer/Désactiver cas particulier :"
L["ui/keybinds/toggleMultiTarget/text"] = "Activer/Désactiver le mode multi-cibles"
L["ui/options/importExport/useOld/text"] = "Ancien import/export"
L["ui/options/importExport/useOld/tooltip"] = "Utilisez l'ancien système d'import/export (Pour des raisons de compatibilité)"
L["ui/rotations/toggleMultiTarget/text"] = "Activer/Désactiver le mode multi-cibles"
L["ui/spells/general/isCustomCase/text"] = "Cas personalisé "
L["ui/spells/general/isCustomCase/tooltip"] = "N’afficher cette action qu’uniquement si ce cas personalisé est activé"
L["ui/spells/general/notCustomCase/text"] = "Pas cas personalisé "
L["ui/spells/general/notCustomCase/tooltip"] = "N’afficher cette action qu’uniquement si ce cas personalisé est désactivé"
--@end-do-not-package@
--@localization(locale="frFR", format="lua_additive_table")@
