-- The default rotations generator for ROGUES.
local deathKnightRotationsGenerator = function ()
	local rotation = {
		["defaultRotation/DeathKnight/Sang 5.0.4"] = {
			["ActionList"] = {
				["defaultRotation/DeathKnight/Chancre impie"] = {
					["v_t_needsdebuff"] = "_55095&_55078",
					["b_t_dr"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "115989",
					["b_t_needsdebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "111673",
					["v_actionicon"] = "115989",
				},
				["defaultRotation/DeathKnight/Frappe de mort (Givre + Impie)"] = {
					["b_p_frostrunes"] = true,
					["v_keybind"] = "<keybind>",
					["b_p_unholyrunes"] = true,
					["v_gcdspell"] = "111673",
					["v_togglename"] = "Toggle 1",
					["v_p_hp"] = "<90%",
					["v_p_unholyrunes"] = "=2",
					["v_actionicon"] = "49998",
					["v_spellname"] = "49998",
					["v_p_frostrunes"] = "=2",
					["b_p_hp"] = true,
					["v_durationstartedtime"] = 0,
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Parasite de peste (Sang)"] = {
					["v_t_needsdebuff"] = "_55095^4&_55078^4",
					["b_p_bloodrunes"] = true,
					["v_actionicon"] = "123693",
					["b_rangecheck"] = true,
					["v_gcdspell"] = "111673",
					["v_keybind"] = "<keybind>",
					["b_checkothercd"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "123693",
					["b_t_needsdebuff"] = true,
					["v_checkothercdvalue"] = "<1",
					["v_p_bloodrunes"] = "=0",
					["v_checkothercdname"] = "77575",
				},
				["defaultRotation/DeathKnight/Cor de l'hiver"] = {
					["v_p_needbuff"] = "57330|19506|6673",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "57330",
					["v_spellname"] = "57330",
					["b_p_needbuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "111673",
					["v_durationstartedtime"] = 0,
				},
				["defaultRotation/DeathKnight/Furoncle sanglant (Fléau)"] = {
					["b_t_dr"] = true,
					["v_gcdspell"] = "111673",
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "48721",
					["v_actionicon"] = "48721",
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "_81141",
					["b_p_havebuff"] = true,
				},
				["defaultRotation/DeathKnight/Changeliche"] = {
					["v_actionicon"] = "49039",
					["v_p_hp"] = "<50%",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "49039",
					["v_togglename"] = "Toggle 1",
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "0",
					["b_p_hp"] = true,
				},
				["defaultRotation/DeathKnight/Drain sanglant (Givre + Vie)"] = {
					["b_p_frostrunes"] = true,
					["v_togglename"] = "Toggle 1",
					["v_gcdspell"] = "0",
					["v_p_frostrunes"] = "=0",
					["b_p_havebuff"] = true,
					["v_p_hp"] = "<80%",
					["v_actionicon"] = "45529",
					["v_spellname"] = "45529",
					["v_durationstartedtime"] = 0,
					["b_p_hp"] = true,
					["v_p_havebuff"] = "_114851#5",
					["v_keybind"] = "<keybind>",
				},
				["defaultRotation/DeathKnight/Cor de l'hiver (Puissance)"] = {
					["v_gcdspell"] = "111673",
					["b_p_unitpower"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "57330",
					["v_p_unitpowertype"] = "6",
					["v_keybind"] = "<keybind>",
					["v_p_unitpower"] = "<80",
					["v_actionicon"] = "57330",
				},
				["defaultRotation/DeathKnight/Furoncle sanglant"] = {
					["v_t_needsdebuff"] = "_55095^4&_55078^4",
					["b_t_dr"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "48721",
					["b_t_needsdebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "111673",
					["v_actionicon"] = "48721",
				},
				["defaultRotation/DeathKnight/Sang vampirique"] = {
					["v_actionicon"] = "55233",
					["v_p_hp"] = "<70%",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "55233",
					["v_togglename"] = "Toggle 1",
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "0",
					["b_p_hp"] = true,
				},
				["defaultRotation/DeathKnight/Faucheur d'âme"] = {
					["b_p_bloodrunes"] = true,
					["v_gcdspell"] = "111673",
					["b_rangecheck"] = true,
					["v_actionicon"] = "114866",
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "114866",
					["b_t_hp"] = true,
					["v_keybind"] = "<keybind>",
					["v_p_bloodrunes"] = ">=1",
					["v_t_hp"] = "<=35%",
				},
				["defaultRotation/DeathKnight/Frappe de peste"] = {
					["v_t_needsdebuff"] = "_55078",
					["b_t_hasdebuff"] = true,
					["b_p_unholyrunes"] = true,
					["v_gcdspell"] = "111673",
					["b_rangecheck"] = true,
					["v_togglename"] = "Toggle 1",
					["v_p_unholyrunes"] = ">=1",
					["v_actionicon"] = "45462",
					["v_spellname"] = "45462",
					["b_t_needsdebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_durationstartedtime"] = 0,
					["v_t_hasdebuff"] = "_55095",
				},
				["defaultRotation/DeathKnight/Toucher de glace"] = {
					["v_t_needsdebuff"] = "_55095",
					["b_p_frostrunes"] = true,
					["b_p_unholyrunes"] = true,
					["v_gcdspell"] = "111673",
					["v_durationstartedtime"] = 0,
					["v_togglename"] = "Toggle 1",
					["v_p_unholyrunes"] = ">=1",
					["v_actionicon"] = "45477",
					["v_spellname"] = "45477",
					["b_t_needsdebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_p_frostrunes"] = ">=1",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Drain sanglant (Sang)"] = {
					["b_p_bloodrunes"] = true,
					["v_gcdspell"] = "0",
					["v_p_havebuff"] = "_114851#10",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "45529",
					["v_spellname"] = "45529",
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
					["v_p_bloodrunes"] = "=0",
					["b_p_havebuff"] = true,
				},
				["defaultRotation/DeathKnight/Frappe runique"] = {
					["v_gcdspell"] = "111673",
					["v_actionicon"] = "56815",
					["b_p_unitpower"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "56815",
					["v_p_unitpowertype"] = "6",
					["v_keybind"] = "<keybind>",
					["v_p_unitpower"] = ">60",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Connexion runique"] = {
					["b_p_bloodrunes"] = true,
					["v_gcdspell"] = "0",
					["v_togglename"] = "Toggle 1",
					["v_p_hp"] = "<80%",
					["v_actionicon"] = "48982",
					["v_spellname"] = "48982",
					["v_durationstartedtime"] = 0,
					["b_p_hp"] = true,
					["v_p_bloodrunes"] = ">=1",
					["v_keybind"] = "<keybind>",
				},
				["defaultRotation/DeathKnight/Conversion"] = {
					["v_p_needbuff"] = "_119975",
					["b_p_needbuff"] = true,
					["v_p_hp"] = "<70%",
					["v_actionicon"] = "119975",
					["v_spellname"] = "119975",
					["v_togglename"] = "Toggle 1",
					["b_p_hp"] = true,
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
				},
				["defaultRotation/DeathKnight/Siphon mortel"] = {
					["v_p_deathrunes"] = ">=1",
					["b_p_deathrunes"] = true,
					["v_gcdspell"] = "111673",
					["v_keybind"] = "<keybind>",
					["v_p_hp"] = "<90%",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "108196",
					["v_togglename"] = "Toggle 1",
					["b_p_hp"] = true,
					["v_actionicon"] = "108196",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Frappe de mort (Mort)"] = {
					["v_p_deathrunes"] = ">=2",
					["b_p_deathrunes"] = true,
					["v_gcdspell"] = "111673",
					["v_keybind"] = "<keybind>",
					["v_p_hp"] = "<90%",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "49998",
					["v_togglename"] = "Toggle 1",
					["b_p_hp"] = true,
					["v_actionicon"] = "49998",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Drain sanglant (Impie + Vie)"] = {
					["v_togglename"] = "Toggle 1",
					["b_p_unholyrunes"] = true,
					["v_gcdspell"] = "0",
					["v_p_hp"] = "<80%",
					["v_actionicon"] = "45529",
					["v_p_unholyrunes"] = "=0",
					["b_p_havebuff"] = true,
					["v_spellname"] = "45529",
					["v_durationstartedtime"] = 0,
					["b_p_hp"] = true,
					["v_p_havebuff"] = "_114851#5",
					["v_keybind"] = "<keybind>",
				},
				["defaultRotation/DeathKnight/Renforcer l'arme runique"] = {
					["b_p_frostrunes"] = true,
					["b_p_unholyrunes"] = true,
					["v_gcdspell"] = "0",
					["v_togglename"] = "Toggle 1",
					["v_p_hp"] = "<60%",
					["v_p_unholyrunes"] = "=0",
					["v_actionicon"] = "47568",
					["v_spellname"] = "47568",
					["v_p_frostrunes"] = "=0",
					["b_p_hp"] = true,
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
				},
				["defaultRotation/DeathKnight/Poussée de fièvre"] = {
					["v_t_needsdebuff"] = "_55095&_55078",
					["v_gcdspell"] = "111673",
					["v_keybind"] = "<keybind>",
					["v_togglename"] = "Toggle 1",
					["v_p_knownotspell"] = "59332",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "77575",
					["b_t_needsdebuff"] = true,
					["b_p_knownotspell"] = true,
					["v_actionicon"] = "77575",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Frappe au coeur"] = {
					["b_p_bloodrunes"] = true,
					["v_rangespell"] = "45462",
					["v_gcdspell"] = "111673",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "55050",
					["v_spellname"] = "55050",
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
					["v_p_bloodrunes"] = ">=1",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Frappe de mort"] = {
					["b_p_frostrunes"] = true,
					["v_keybind"] = "<keybind>",
					["b_p_unholyrunes"] = true,
					["v_gcdspell"] = "111673",
					["v_togglename"] = "Toggle 1",
					["v_p_hp"] = "<80%",
					["v_p_unholyrunes"] = ">=1",
					["v_actionicon"] = "49998",
					["v_spellname"] = "49998",
					["v_p_frostrunes"] = ">=1",
					["b_p_hp"] = true,
					["v_durationstartedtime"] = 0,
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Mort et décomposition"] = {
					["v_gcdspell"] = "111673",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "43265",
					["v_spellname"] = "43265",
					["b_p_havebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "_81141",
					["v_durationstartedtime"] = 0,
				},
				["defaultRotation/DeathKnight/Drain sanglant (Impie)"] = {
					["v_gcdspell"] = "0",
					["b_p_unholyrunes"] = true,
					["v_togglename"] = "Toggle 1",
					["v_p_unholyrunes"] = "=0",
					["v_actionicon"] = "45529",
					["v_spellname"] = "45529",
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "_114851#10",
					["b_p_havebuff"] = true,
				},
				["defaultRotation/DeathKnight/Frappe au coeur (Sang)"] = {
					["b_p_bloodrunes"] = true,
					["v_rangespell"] = "45462",
					["v_gcdspell"] = "111673",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "55050",
					["v_spellname"] = "55050",
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
					["v_p_bloodrunes"] = "=2",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Voile mortel (Changeliche)"] = {
					["b_p_havebuff"] = true,
					["v_togglename"] = "Toggle 1",
					["v_p_unitpower"] = ">=40",
					["v_gcdspell"] = "111673",
					["b_p_unitpower"] = true,
					["v_actionicon"] = "47541",
					["v_p_hp"] = "<100%",
					["v_p_unitpowertype"] = "6",
					["v_spellname"] = "47541",
					["v_durationstartedtime"] = 0,
					["b_p_hp"] = true,
					["v_p_havebuff"] = "_49039",
					["v_keybind"] = "<keybind>",
				},
				["defaultRotation/DeathKnight/Drain sanglant (Sang + Vie)"] = {
					["b_p_bloodrunes"] = true,
					["v_togglename"] = "Toggle 1",
					["v_gcdspell"] = "0",
					["b_p_havebuff"] = true,
					["v_p_havebuff"] = "_114851#5",
					["v_p_hp"] = "<80%",
					["v_actionicon"] = "45529",
					["v_spellname"] = "45529",
					["v_durationstartedtime"] = 0,
					["b_p_hp"] = true,
					["v_p_bloodrunes"] = "=0",
					["v_keybind"] = "<keybind>",
				},
				["defaultRotation/DeathKnight/Drain sanglant (Givre)"] = {
					["b_p_frostrunes"] = true,
					["v_gcdspell"] = "0",
					["b_p_havebuff"] = true,
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "45529",
					["v_spellname"] = "45529",
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "_114851#10",
					["v_p_frostrunes"] = "=0",
				},
				["defaultRotation/DeathKnight/Faucheur d'âme (Sang)"] = {
					["b_p_bloodrunes"] = true,
					["v_gcdspell"] = "111673",
					["b_rangecheck"] = true,
					["v_actionicon"] = "114866",
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "114866",
					["b_t_hp"] = true,
					["v_keybind"] = "<keybind>",
					["v_p_bloodrunes"] = "=2",
					["v_t_hp"] = "<=35%",
				},
				["defaultRotation/DeathKnight/Réanimation morbide"] = {
					["v_actionicon"] = "46584",
					["v_p_hp"] = "<35%",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "46584",
					["v_togglename"] = "Toggle 1",
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "111673",
					["b_p_hp"] = true,
				},
				["defaultRotation/DeathKnight/Pacte mortel"] = {
					["v_actionicon"] = "48743",
					["v_p_hp"] = "<35%",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "48743",
					["v_togglename"] = "Toggle 1",
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "0",
					["b_p_hp"] = true,
				},
				["defaultRotation/DeathKnight/Parasite de peste (Givre + Impie)"] = {
					["v_t_needsdebuff"] = "_55095^4&_55078^4",
					["b_p_frostrunes"] = true,
					["v_p_deathrunes"] = "<4",
					["v_gcdspell"] = "111673",
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "123693",
					["b_t_needsdebuff"] = true,
					["v_checkothercdvalue"] = "<1",
					["v_checkothercdname"] = "77575",
					["b_p_deathrunes"] = true,
					["b_checkothercd"] = true,
					["v_p_unholyrunes"] = "=0",
					["v_actionicon"] = "123693",
					["b_p_unholyrunes"] = true,
					["v_keybind"] = "<keybind>",
					["b_rangecheck"] = true,
					["v_p_frostrunes"] = "=0",
				},
				["defaultRotation/DeathKnight/Bouclier d'os"] = {
					["v_p_needbuff"] = "_49222",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "49222",
					["v_spellname"] = "49222",
					["b_p_needbuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "0",
					["v_durationstartedtime"] = 0,
				},
				["defaultRotation/DeathKnight/Poussée de fièvre (Glyphe)"] = {
					["v_t_needsdebuff"] = "_55095&_55078",
					["v_p_unitpowertype"] = "6",
					["v_p_knowspell"] = "59332",
					["b_p_unitpower"] = true,
					["v_gcdspell"] = "111673",
					["v_actionicon"] = "77575",
					["b_p_knowspell"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "77575",
					["b_t_needsdebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_p_unitpower"] = ">=40",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Présence de sang"] = {
					["v_p_notstance"] = "1",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "48263",
					["v_spellname"] = "48263",
					["b_p_notstance"] = true,
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "111673",
					["v_durationstartedtime"] = 0,
				},
			},
			["SortedActions"] = {
				"defaultRotation/DeathKnight/Voile mortel (Changeliche)", -- [1]
				"defaultRotation/DeathKnight/Présence de sang", -- [2]
				"defaultRotation/DeathKnight/Cor de l'hiver", -- [3]
				"defaultRotation/DeathKnight/Sang vampirique", -- [4]
				"defaultRotation/DeathKnight/Bouclier d'os", -- [5]
				"defaultRotation/DeathKnight/Réanimation morbide", -- [6]
				"defaultRotation/DeathKnight/Pacte mortel", -- [7]
				"defaultRotation/DeathKnight/Renforcer l'arme runique", -- [8]
				"defaultRotation/DeathKnight/Changeliche", -- [9]
				"defaultRotation/DeathKnight/Conversion", -- [10]
				"defaultRotation/DeathKnight/Drain sanglant (Sang)", -- [11]
				"defaultRotation/DeathKnight/Drain sanglant (Givre)", -- [12]
				"defaultRotation/DeathKnight/Drain sanglant (Impie)", -- [13]
				"defaultRotation/DeathKnight/Drain sanglant (Sang + Vie)", -- [14]
				"defaultRotation/DeathKnight/Drain sanglant (Givre + Vie)", -- [15]
				"defaultRotation/DeathKnight/Drain sanglant (Impie + Vie)", -- [16]
				"defaultRotation/DeathKnight/Chancre impie", -- [17]
				"defaultRotation/DeathKnight/Poussée de fièvre", -- [18]
				"defaultRotation/DeathKnight/Poussée de fièvre (Glyphe)", -- [19]
				"defaultRotation/DeathKnight/Parasite de peste (Givre + Impie)", -- [20]
				"defaultRotation/DeathKnight/Parasite de peste (Sang)", -- [21]
				"defaultRotation/DeathKnight/Furoncle sanglant", -- [22]
				"defaultRotation/DeathKnight/Toucher de glace", -- [23]
				"defaultRotation/DeathKnight/Frappe de peste", -- [24]
				"defaultRotation/DeathKnight/Frappe de mort (Givre + Impie)", -- [25]
				"defaultRotation/DeathKnight/Siphon mortel", -- [26]
				"defaultRotation/DeathKnight/Frappe de mort (Mort)", -- [27]
				"defaultRotation/DeathKnight/Connexion runique", -- [28]
				"defaultRotation/DeathKnight/Faucheur d'âme (Sang)", -- [29]
				"defaultRotation/DeathKnight/Frappe au coeur (Sang)", -- [30]
				"defaultRotation/DeathKnight/Frappe runique", -- [31]
				"defaultRotation/DeathKnight/Mort et décomposition", -- [32]
				"defaultRotation/DeathKnight/Furoncle sanglant (Fléau)", -- [33]
				"defaultRotation/DeathKnight/Frappe de mort", -- [34]
				"defaultRotation/DeathKnight/Faucheur d'âme", -- [35]
				"defaultRotation/DeathKnight/Frappe au coeur", -- [36]
				"defaultRotation/DeathKnight/Cor de l'hiver (Puissance)", -- [37]
			},
			["keybind"] = "<keybind>",
		},
		["defaultRotation/DeathKnight/Givre armes à 1 main 5.0.4"] = {
			["ActionList"] = {
				["defaultRotation/DeathKnight/Chancre impie"] = {
					["v_t_needsdebuff"] = "_55095&_55078",
					["b_t_dr"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "115989",
					["b_t_needsdebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "111673",
					["v_actionicon"] = "115989",
				},
				["defaultRotation/DeathKnight/Rafale hurlante (Frimas)"] = {
					["v_gcdspell"] = "111673",
					["v_durationstartedtime"] = 0,
					["v_togglename"] = "Toggle 1",
					["b_p_havebuff"] = true,
					["v_spellname"] = "49184",
					["v_actionicon"] = "49184",
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "_59052",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Parasite de peste (Impie)"] = {
					["v_t_needsdebuff"] = "_55095^4&_55078^4",
					["v_gcdspell"] = "111673",
					["v_p_deathrunes"] = "<6",
					["b_p_unholyrunes"] = true,
					["b_rangecheck"] = true,
					["v_togglename"] = "Toggle 1",
					["b_p_deathrunes"] = true,
					["v_keybind"] = "<keybind>",
					["b_checkothercd"] = true,
					["v_p_unholyrunes"] = "=0",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "123693",
					["b_t_needsdebuff"] = true,
					["v_checkothercdvalue"] = "<1",
					["v_actionicon"] = "123693",
					["v_checkothercdname"] = "77575",
				},
				["defaultRotation/DeathKnight/Cor de l'hiver"] = {
					["v_p_needbuff"] = "57330|19506|6673",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "57330",
					["v_spellname"] = "57330",
					["b_p_needbuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "111673",
					["v_durationstartedtime"] = 0,
				},
				["defaultRotation/DeathKnight/Changeliche"] = {
					["v_actionicon"] = "49039",
					["v_p_hp"] = "<50%",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "49039",
					["v_togglename"] = "Toggle 1",
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "0",
					["b_p_hp"] = true,
				},
				["defaultRotation/DeathKnight/Mort et décomposition"] = {
					["v_togglename"] = "Toggle 1",
					["v_p_unholyrunes"] = "=2",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "43265",
					["b_p_unholyrunes"] = true,
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "111673",
					["v_actionicon"] = "43265",
				},
				["defaultRotation/DeathKnight/Rafale hurlante"] = {
					["b_p_frostrunes"] = true,
					["v_gcdspell"] = "111673",
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "49184",
					["v_actionicon"] = "49184",
					["v_p_frostrunes"] = ">=1",
					["v_keybind"] = "<keybind>",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Anéantissement (Machine + Mort)"] = {
					["v_gcdspell"] = "111673",
					["v_p_deathrunes"] = ">=1",
					["b_t_hasdebuff"] = true,
					["b_p_unholyrunes"] = true,
					["b_rangecheck"] = true,
					["b_p_deathrunes"] = true,
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "49020",
					["v_p_unholyrunes"] = "=2",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "49020",
					["b_p_havebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "_51124",
					["v_t_hasdebuff"] = "_55095^2&_55078^2",
				},
				["defaultRotation/DeathKnight/Anéantissement (Machine)"] = {
					["b_p_frostrunes"] = true,
					["v_togglename"] = "Toggle 1",
					["b_t_hasdebuff"] = true,
					["b_p_unholyrunes"] = true,
					["b_rangecheck"] = true,
					["v_gcdspell"] = "111673",
					["v_durationstartedtime"] = 0,
					["v_p_frostrunes"] = ">=1",
					["v_p_unholyrunes"] = "=2",
					["v_actionicon"] = "49020",
					["v_spellname"] = "49020",
					["b_p_havebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "_51124",
					["v_t_hasdebuff"] = "_55095^2&_55078^2",
				},
				["defaultRotation/DeathKnight/Rafale hurlante (Mort)"] = {
					["v_p_deathrunes"] = ">=1",
					["b_p_deathrunes"] = true,
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "49184",
					["v_spellname"] = "49184",
					["v_gcdspell"] = "111673",
					["v_keybind"] = "<keybind>",
					["v_durationstartedtime"] = 0,
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Parasite de peste (Givre)"] = {
					["v_t_needsdebuff"] = "_55095^4&_55078^4",
					["b_p_frostrunes"] = true,
					["v_p_deathrunes"] = "<6",
					["v_gcdspell"] = "111673",
					["b_rangecheck"] = true,
					["v_p_frostrunes"] = "=0",
					["b_p_deathrunes"] = true,
					["v_keybind"] = "<keybind>",
					["b_checkothercd"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "123693",
					["b_t_needsdebuff"] = true,
					["v_checkothercdvalue"] = "<1",
					["v_actionicon"] = "123693",
					["v_checkothercdname"] = "77575",
				},
				["defaultRotation/DeathKnight/Frappe de peste"] = {
					["v_t_needsdebuff"] = "_55078",
					["v_checkothercdname"] = "77575",
					["b_p_unholyrunes"] = true,
					["b_t_hasdebuff"] = true,
					["b_rangecheck"] = true,
					["v_togglename"] = "Toggle 1",
					["v_gcdspell"] = "111673",
					["v_actionicon"] = "45462",
					["b_checkothercd"] = true,
					["v_p_unholyrunes"] = ">=1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "45462",
					["b_t_needsdebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_checkothercdvalue"] = ">5",
					["v_t_hasdebuff"] = "_55095",
				},
				["defaultRotation/DeathKnight/Faucheur d'âme (Givre)"] = {
					["b_p_frostrunes"] = true,
					["v_gcdspell"] = "111673",
					["b_rangecheck"] = true,
					["v_actionicon"] = "130735",
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "130735",
					["b_t_hp"] = true,
					["v_keybind"] = "<keybind>",
					["v_p_frostrunes"] = ">=1",
					["v_t_hp"] = "<=35%",
				},
				["defaultRotation/DeathKnight/Parasite de peste (Mort)"] = {
					["v_t_needsdebuff"] = "_55095^4&_55078^4",
					["v_p_deathrunes"] = "<2",
					["v_gcdspell"] = "111673",
					["b_rangecheck"] = true,
					["b_p_deathrunes"] = true,
					["v_keybind"] = "<keybind>",
					["b_checkothercd"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "123693",
					["b_t_needsdebuff"] = true,
					["v_checkothercdvalue"] = "<1",
					["v_actionicon"] = "123693",
					["v_checkothercdname"] = "77575",
				},
				["defaultRotation/DeathKnight/Drain sanglant (Sang)"] = {
					["b_p_bloodrunes"] = true,
					["v_gcdspell"] = "0",
					["v_p_havebuff"] = "_114851#5",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "45529",
					["v_spellname"] = "45529",
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
					["v_p_bloodrunes"] = "=0",
					["b_p_havebuff"] = true,
				},
				["defaultRotation/DeathKnight/Présence de givre"] = {
					["v_p_notstance"] = "2",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "48266",
					["v_spellname"] = "48266",
					["b_p_notstance"] = true,
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "111673",
					["v_durationstartedtime"] = 0,
				},
				["defaultRotation/DeathKnight/Frappe de givre (Machine)"] = {
					["v_gcdspell"] = "111673",
					["b_rangecheck"] = true,
					["b_t_hasdebuff"] = true,
					["b_p_havebuff"] = true,
					["v_p_unitpower"] = ">=20",
					["v_rangespell"] = "49020",
					["b_p_unitpower"] = true,
					["v_actionicon"] = "49143",
					["v_togglename"] = "Toggle 1",
					["v_p_unitpowertype"] = "6",
					["v_spellname"] = "49143",
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "_51124",
					["v_t_hasdebuff"] = "_55095^2&_55078^2",
				},
				["defaultRotation/DeathKnight/Rafale hurlante (Fièvre)"] = {
					["v_t_needsdebuff"] = "_55095",
					["b_p_frostrunes"] = true,
					["v_keybind"] = "<keybind>",
					["b_p_unholyrunes"] = true,
					["b_rangecheck"] = true,
					["v_togglename"] = "Toggle 1",
					["v_gcdspell"] = "111673",
					["v_p_frostrunes"] = ">=1",
					["b_checkothercd"] = true,
					["v_p_unholyrunes"] = ">=1",
					["v_actionicon"] = "49184",
					["v_spellname"] = "49184",
					["b_t_needsdebuff"] = true,
					["v_checkothercdvalue"] = ">5",
					["v_durationstartedtime"] = 0,
					["v_checkothercdname"] = "77575",
				},
				["defaultRotation/DeathKnight/Conversion"] = {
					["v_p_needbuff"] = "_119975",
					["b_p_needbuff"] = true,
					["v_p_hp"] = "<70%",
					["v_actionicon"] = "119975",
					["v_spellname"] = "119975",
					["v_togglename"] = "Toggle 1",
					["b_p_hp"] = true,
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
				},
				["defaultRotation/DeathKnight/Siphon mortel"] = {
					["v_p_deathrunes"] = ">=1",
					["b_p_deathrunes"] = true,
					["v_gcdspell"] = "111673",
					["v_keybind"] = "<keybind>",
					["v_p_hp"] = "<70%",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "108196",
					["v_togglename"] = "Toggle 1",
					["b_p_hp"] = true,
					["v_actionicon"] = "108196",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Pacte mortel"] = {
					["v_gcdspell"] = "0",
					["v_keybind"] = "<keybind>",
					["v_pet_hp"] = ">0",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "48743",
					["v_spellname"] = "48743",
					["v_p_hp"] = "<35%",
					["b_p_hp"] = true,
					["v_durationstartedtime"] = 0,
					["b_pet_hp"] = true,
				},
				["defaultRotation/DeathKnight/Anéantissement"] = {
					["b_p_frostrunes"] = true,
					["b_t_hasdebuff"] = true,
					["b_p_unholyrunes"] = true,
					["v_gcdspell"] = "111673",
					["b_rangecheck"] = true,
					["v_togglename"] = "Toggle 1",
					["v_p_unholyrunes"] = "=2",
					["v_actionicon"] = "49020",
					["v_spellname"] = "49020",
					["v_p_frostrunes"] = ">=1",
					["v_keybind"] = "<keybind>",
					["v_durationstartedtime"] = 0,
					["v_t_hasdebuff"] = "_55095^2&_55078^2",
				},
				["defaultRotation/DeathKnight/Frappe de givre (Puissance)"] = {
					["v_gcdspell"] = "111673",
					["v_rangespell"] = "49020",
					["v_actionicon"] = "49143",
					["b_p_unitpower"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "49143",
					["v_p_unitpowertype"] = "6",
					["v_keybind"] = "<keybind>",
					["v_p_unitpower"] = ">=90",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Pillier de givre"] = {
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "51271",
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "0",
					["v_actionicon"] = "51271",
				},
				["defaultRotation/DeathKnight/Poussée de fièvre"] = {
					["v_t_needsdebuff"] = "_55095&_55078",
					["v_gcdspell"] = "111673",
					["v_keybind"] = "<keybind>",
					["v_togglename"] = "Toggle 1",
					["v_p_knownotspell"] = "59332",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "77575",
					["b_t_needsdebuff"] = true,
					["b_p_knownotspell"] = true,
					["v_actionicon"] = "77575",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Drain sanglant (Impie)"] = {
					["v_gcdspell"] = "0",
					["b_p_unholyrunes"] = true,
					["v_togglename"] = "Toggle 1",
					["v_p_unholyrunes"] = "=0",
					["v_actionicon"] = "45529",
					["v_spellname"] = "45529",
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "_114851#5",
					["b_p_havebuff"] = true,
				},
				["defaultRotation/DeathKnight/Voile mortel (Changeliche)"] = {
					["b_p_havebuff"] = true,
					["v_togglename"] = "Toggle 1",
					["v_p_unitpower"] = ">=40",
					["v_gcdspell"] = "111673",
					["b_p_unitpower"] = true,
					["v_actionicon"] = "47541",
					["v_p_hp"] = "<100%",
					["v_p_unitpowertype"] = "6",
					["v_spellname"] = "47541",
					["v_durationstartedtime"] = 0,
					["b_p_hp"] = true,
					["v_p_havebuff"] = "_49039",
					["v_keybind"] = "<keybind>",
				},
				["defaultRotation/DeathKnight/Poussée de fièvre (Glyphe)"] = {
					["v_t_needsdebuff"] = "_55095&_55078",
					["v_p_unitpowertype"] = "6",
					["v_p_knowspell"] = "59332",
					["b_p_unitpower"] = true,
					["v_gcdspell"] = "111673",
					["v_actionicon"] = "77575",
					["b_p_knowspell"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "77575",
					["b_t_needsdebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_p_unitpower"] = ">=40",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Faucheur d'âme (Mort)"] = {
					["v_p_deathrunes"] = ">=1",
					["b_p_deathrunes"] = true,
					["v_gcdspell"] = "111673",
					["b_rangecheck"] = true,
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "130735",
					["b_t_hp"] = true,
					["v_spellname"] = "130735",
					["v_keybind"] = "<keybind>",
					["v_durationstartedtime"] = 0,
					["v_t_hp"] = "<=35%",
				},
				["defaultRotation/DeathKnight/Réanimation morbide"] = {
					["v_gcdspell"] = "111673",
					["v_keybind"] = "<keybind>",
					["v_pet_hp"] = "=0",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "46584",
					["v_spellname"] = "46584",
					["v_p_hp"] = "<35%",
					["b_p_hp"] = true,
					["v_durationstartedtime"] = 0,
					["b_pet_hp"] = true,
				},
				["defaultRotation/DeathKnight/Cor de l'hiver (Puissance)"] = {
					["v_gcdspell"] = "111673",
					["b_p_unitpower"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "57330",
					["v_p_unitpowertype"] = "6",
					["v_keybind"] = "<keybind>",
					["v_p_unitpower"] = "<90",
					["v_actionicon"] = "57330",
				},
				["defaultRotation/DeathKnight/Frappe de givre"] = {
					["v_gcdspell"] = "111673",
					["v_rangespell"] = "49020",
					["v_actionicon"] = "49143",
					["b_p_unitpower"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "49143",
					["v_p_unitpowertype"] = "6",
					["v_keybind"] = "<keybind>",
					["v_p_unitpower"] = ">=20",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Anéantissement (Mort)"] = {
					["v_p_deathrunes"] = ">=1",
					["b_t_hasdebuff"] = true,
					["v_gcdspell"] = "111673",
					["b_p_deathrunes"] = true,
					["b_p_unholyrunes"] = true,
					["b_rangecheck"] = true,
					["v_p_unholyrunes"] = "=2",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "49020",
					["v_togglename"] = "Toggle 1",
					["v_keybind"] = "<keybind>",
					["v_actionicon"] = "49020",
					["v_t_hasdebuff"] = "_55095^2&_55078^2",
				},
				["defaultRotation/DeathKnight/Renforcer l'arme runique"] = {
					["b_p_frostrunes"] = true,
					["v_p_deathrunes"] = "=0",
					["v_gcdspell"] = "0",
					["b_p_unholyrunes"] = true,
					["b_p_deathrunes"] = true,
					["v_togglename"] = "Toggle 1",
					["b_p_bloodrunes"] = true,
					["v_p_unholyrunes"] = "=0",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "47568",
					["v_p_frostrunes"] = "=0",
					["v_keybind"] = "<keybind>",
					["v_p_bloodrunes"] = "=0",
					["v_actionicon"] = "47568",
				},
				["defaultRotation/DeathKnight/Drain sanglant (Givre)"] = {
					["b_p_frostrunes"] = true,
					["v_gcdspell"] = "0",
					["b_p_havebuff"] = true,
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "45529",
					["v_spellname"] = "45529",
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "_114851#5",
					["v_p_frostrunes"] = "=0",
				},
			},
			["SortedActions"] = {
				"defaultRotation/DeathKnight/Voile mortel (Changeliche)", -- [1]
				"defaultRotation/DeathKnight/Présence de givre", -- [2]
				"defaultRotation/DeathKnight/Cor de l'hiver", -- [3]
				"defaultRotation/DeathKnight/Réanimation morbide", -- [4]
				"defaultRotation/DeathKnight/Pacte mortel", -- [5]
				"defaultRotation/DeathKnight/Renforcer l'arme runique", -- [6]
				"defaultRotation/DeathKnight/Changeliche", -- [7]
				"defaultRotation/DeathKnight/Conversion", -- [8]
				"defaultRotation/DeathKnight/Drain sanglant (Sang)", -- [9]
				"defaultRotation/DeathKnight/Drain sanglant (Givre)", -- [10]
				"defaultRotation/DeathKnight/Drain sanglant (Impie)", -- [11]
				"defaultRotation/DeathKnight/Pillier de givre", -- [12]
				"defaultRotation/DeathKnight/Faucheur d'âme (Givre)", -- [13]
				"defaultRotation/DeathKnight/Faucheur d'âme (Mort)", -- [14]
				"defaultRotation/DeathKnight/Chancre impie", -- [15]
				"defaultRotation/DeathKnight/Poussée de fièvre", -- [16]
				"defaultRotation/DeathKnight/Poussée de fièvre (Glyphe)", -- [17]
				"defaultRotation/DeathKnight/Parasite de peste (Givre)", -- [18]
				"defaultRotation/DeathKnight/Parasite de peste (Impie)", -- [19]
				"defaultRotation/DeathKnight/Parasite de peste (Mort)", -- [20]
				"defaultRotation/DeathKnight/Rafale hurlante (Fièvre)", -- [21]
				"defaultRotation/DeathKnight/Frappe de peste", -- [22]
				"defaultRotation/DeathKnight/Frappe de givre (Machine)", -- [23]
				"defaultRotation/DeathKnight/Mort et décomposition", -- [24]
				"defaultRotation/DeathKnight/Anéantissement (Machine)", -- [25]
				"defaultRotation/DeathKnight/Anéantissement (Machine + Mort)", -- [26]
				"defaultRotation/DeathKnight/Frappe de givre (Puissance)", -- [27]
				"defaultRotation/DeathKnight/Rafale hurlante (Frimas)", -- [28]
				"defaultRotation/DeathKnight/Siphon mortel", -- [29]
				"defaultRotation/DeathKnight/Anéantissement", -- [30]
				"defaultRotation/DeathKnight/Anéantissement (Mort)", -- [31]
				"defaultRotation/DeathKnight/Frappe de givre", -- [32]
				"defaultRotation/DeathKnight/Rafale hurlante", -- [33]
				"defaultRotation/DeathKnight/Rafale hurlante (Mort)", -- [34]
				"defaultRotation/DeathKnight/Cor de l'hiver (Puissance)", -- [35]
			},
			["keybind"] = "<keybind>",
		},
		["defaultRotation/DeathKnight/Givre arme à 2 mains 5.0.4"] = {
			["ActionList"] = {
				["defaultRotation/DeathKnight/Chancre impie"] = {
					["v_t_needsdebuff"] = "_55095&_55078",
					["b_t_dr"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "115989",
					["b_t_needsdebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "111673",
					["v_actionicon"] = "115989",
				},
				["defaultRotation/DeathKnight/Présence de givre"] = {
					["v_p_notstance"] = "2",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "48266",
					["v_spellname"] = "48266",
					["b_p_notstance"] = true,
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "111673",
					["v_durationstartedtime"] = 0,
				},
				["defaultRotation/DeathKnight/Rafale hurlante (Frimas)"] = {
					["v_gcdspell"] = "111673",
					["v_durationstartedtime"] = 0,
					["v_togglename"] = "Toggle 1",
					["b_p_havebuff"] = true,
					["v_spellname"] = "49184",
					["v_actionicon"] = "49184",
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "_59052",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Parasite de peste (Impie)"] = {
					["v_t_needsdebuff"] = "_55095^4&_55078^4",
					["v_gcdspell"] = "111673",
					["v_p_deathrunes"] = "<6",
					["b_p_unholyrunes"] = true,
					["b_rangecheck"] = true,
					["v_togglename"] = "Toggle 1",
					["b_p_deathrunes"] = true,
					["v_keybind"] = "<keybind>",
					["b_checkothercd"] = true,
					["v_p_unholyrunes"] = "=0",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "123693",
					["b_t_needsdebuff"] = true,
					["v_checkothercdvalue"] = "<1",
					["v_actionicon"] = "123693",
					["v_checkothercdname"] = "77575",
				},
				["defaultRotation/DeathKnight/Rafale hurlante (Fièvre)"] = {
					["v_t_needsdebuff"] = "_55095",
					["b_p_frostrunes"] = true,
					["v_keybind"] = "<keybind>",
					["b_p_unholyrunes"] = true,
					["b_rangecheck"] = true,
					["v_togglename"] = "Toggle 1",
					["v_gcdspell"] = "111673",
					["v_p_frostrunes"] = ">=1",
					["b_checkothercd"] = true,
					["v_p_unholyrunes"] = ">=1",
					["v_actionicon"] = "49184",
					["v_spellname"] = "49184",
					["b_t_needsdebuff"] = true,
					["v_checkothercdvalue"] = ">5",
					["v_durationstartedtime"] = 0,
					["v_checkothercdname"] = "77575",
				},
				["defaultRotation/DeathKnight/Cor de l'hiver"] = {
					["v_p_needbuff"] = "57330|19506|6673",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "57330",
					["v_spellname"] = "57330",
					["b_p_needbuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "111673",
					["v_durationstartedtime"] = 0,
				},
				["defaultRotation/DeathKnight/Conversion"] = {
					["v_p_needbuff"] = "_119975",
					["b_p_needbuff"] = true,
					["v_p_hp"] = "<70%",
					["v_actionicon"] = "119975",
					["v_spellname"] = "119975",
					["v_togglename"] = "Toggle 1",
					["b_p_hp"] = true,
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
				},
				["defaultRotation/DeathKnight/Siphon mortel"] = {
					["v_p_deathrunes"] = ">=1",
					["b_p_deathrunes"] = true,
					["v_gcdspell"] = "111673",
					["v_keybind"] = "<keybind>",
					["v_p_hp"] = "<70%",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "108196",
					["v_togglename"] = "Toggle 1",
					["b_p_hp"] = true,
					["v_actionicon"] = "108196",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Changeliche"] = {
					["v_actionicon"] = "49039",
					["v_p_hp"] = "<50%",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "49039",
					["v_togglename"] = "Toggle 1",
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "0",
					["b_p_hp"] = true,
				},
				["defaultRotation/DeathKnight/Pacte mortel"] = {
					["v_gcdspell"] = "0",
					["v_keybind"] = "<keybind>",
					["v_pet_hp"] = ">0",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "48743",
					["v_spellname"] = "48743",
					["v_p_hp"] = "<35%",
					["b_p_hp"] = true,
					["v_durationstartedtime"] = 0,
					["b_pet_hp"] = true,
				},
				["defaultRotation/DeathKnight/Renforcer l'arme runique"] = {
					["b_p_frostrunes"] = true,
					["v_p_deathrunes"] = "=0",
					["v_gcdspell"] = "0",
					["b_p_unholyrunes"] = true,
					["b_p_deathrunes"] = true,
					["v_togglename"] = "Toggle 1",
					["b_p_bloodrunes"] = true,
					["v_p_unholyrunes"] = "=0",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "47568",
					["v_p_frostrunes"] = "=0",
					["v_keybind"] = "<keybind>",
					["v_p_bloodrunes"] = "=0",
					["v_actionicon"] = "47568",
				},
				["defaultRotation/DeathKnight/Frappe de givre (Puissance)"] = {
					["v_gcdspell"] = "111673",
					["v_rangespell"] = "49020",
					["v_actionicon"] = "49143",
					["b_p_unitpower"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "49143",
					["v_p_unitpowertype"] = "6",
					["v_keybind"] = "<keybind>",
					["v_p_unitpower"] = ">=90",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Cor de l'hiver (Puissance)"] = {
					["v_gcdspell"] = "111673",
					["b_p_unitpower"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "57330",
					["v_p_unitpowertype"] = "6",
					["v_keybind"] = "<keybind>",
					["v_p_unitpower"] = "<90",
					["v_actionicon"] = "57330",
				},
				["defaultRotation/DeathKnight/Anéantissement (Machine + Mort)"] = {
					["v_p_deathrunes"] = ">=2",
					["b_t_hasdebuff"] = true,
					["v_gcdspell"] = "111673",
					["b_p_deathrunes"] = true,
					["b_rangecheck"] = true,
					["v_actionicon"] = "49020",
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "49020",
					["b_p_havebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "_51124",
					["v_t_hasdebuff"] = "_55095^2&_55078^2",
				},
				["defaultRotation/DeathKnight/Poussée de fièvre"] = {
					["v_t_needsdebuff"] = "_55095&_55078",
					["v_gcdspell"] = "111673",
					["v_keybind"] = "<keybind>",
					["v_togglename"] = "Toggle 1",
					["v_p_knownotspell"] = "59332",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "77575",
					["b_t_needsdebuff"] = true,
					["b_p_knownotspell"] = true,
					["v_actionicon"] = "77575",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Frappe de givre"] = {
					["v_gcdspell"] = "111673",
					["v_rangespell"] = "49020",
					["v_actionicon"] = "49143",
					["b_p_unitpower"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "49143",
					["v_p_unitpowertype"] = "6",
					["v_keybind"] = "<keybind>",
					["v_p_unitpower"] = ">=20",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Anéantissement"] = {
					["b_p_frostrunes"] = true,
					["b_t_hasdebuff"] = true,
					["b_p_unholyrunes"] = true,
					["v_gcdspell"] = "111673",
					["b_rangecheck"] = true,
					["v_togglename"] = "Toggle 1",
					["v_p_unholyrunes"] = ">=1",
					["v_actionicon"] = "49020",
					["v_spellname"] = "49020",
					["v_p_frostrunes"] = ">=1",
					["v_keybind"] = "<keybind>",
					["v_durationstartedtime"] = 0,
					["v_t_hasdebuff"] = "_55095^2&_55078^2",
				},
				["defaultRotation/DeathKnight/Anéantissement (Machine)"] = {
					["b_p_frostrunes"] = true,
					["v_togglename"] = "Toggle 1",
					["b_t_hasdebuff"] = true,
					["b_p_unholyrunes"] = true,
					["b_rangecheck"] = true,
					["v_gcdspell"] = "111673",
					["v_durationstartedtime"] = 0,
					["v_p_frostrunes"] = "=2",
					["v_p_unholyrunes"] = "=2",
					["v_actionicon"] = "49020",
					["v_spellname"] = "49020",
					["b_p_havebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "_51124",
					["v_t_hasdebuff"] = "_55095^2&_55078^2",
				},
				["defaultRotation/DeathKnight/Drain sanglant (Impie)"] = {
					["v_gcdspell"] = "0",
					["b_p_unholyrunes"] = true,
					["v_togglename"] = "Toggle 1",
					["v_p_unholyrunes"] = "=0",
					["v_actionicon"] = "45529",
					["v_spellname"] = "45529",
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "_114851#5",
					["b_p_havebuff"] = true,
				},
				["defaultRotation/DeathKnight/Drain sanglant (Givre)"] = {
					["b_p_frostrunes"] = true,
					["v_gcdspell"] = "0",
					["b_p_havebuff"] = true,
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "45529",
					["v_spellname"] = "45529",
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "_114851#5",
					["v_p_frostrunes"] = "=0",
				},
				["defaultRotation/DeathKnight/Parasite de peste (Givre)"] = {
					["v_t_needsdebuff"] = "_55095^4&_55078^4",
					["b_p_frostrunes"] = true,
					["v_p_deathrunes"] = "<6",
					["v_gcdspell"] = "111673",
					["b_rangecheck"] = true,
					["v_p_frostrunes"] = "=0",
					["b_p_deathrunes"] = true,
					["v_keybind"] = "<keybind>",
					["b_checkothercd"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "123693",
					["b_t_needsdebuff"] = true,
					["v_checkothercdvalue"] = "<1",
					["v_actionicon"] = "123693",
					["v_checkothercdname"] = "77575",
				},
				["defaultRotation/DeathKnight/Frappe de peste"] = {
					["v_t_needsdebuff"] = "_55078",
					["v_checkothercdname"] = "77575",
					["b_p_unholyrunes"] = true,
					["b_t_hasdebuff"] = true,
					["b_rangecheck"] = true,
					["v_togglename"] = "Toggle 1",
					["v_gcdspell"] = "111673",
					["v_actionicon"] = "45462",
					["b_checkothercd"] = true,
					["v_p_unholyrunes"] = ">=1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "45462",
					["b_t_needsdebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_checkothercdvalue"] = ">5",
					["v_t_hasdebuff"] = "_55095",
				},
				["defaultRotation/DeathKnight/Poussée de fièvre (Glyphe)"] = {
					["v_t_needsdebuff"] = "_55095&_55078",
					["v_p_unitpowertype"] = "6",
					["v_p_knowspell"] = "59332",
					["b_p_unitpower"] = true,
					["v_gcdspell"] = "111673",
					["v_actionicon"] = "77575",
					["b_p_knowspell"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "77575",
					["b_t_needsdebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_p_unitpower"] = ">=40",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Faucheur d'âme (Mort)"] = {
					["v_p_deathrunes"] = ">=1",
					["b_p_deathrunes"] = true,
					["v_gcdspell"] = "111673",
					["b_rangecheck"] = true,
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "130735",
					["b_t_hp"] = true,
					["v_spellname"] = "130735",
					["v_keybind"] = "<keybind>",
					["v_durationstartedtime"] = 0,
					["v_t_hp"] = "<=35%",
				},
				["defaultRotation/DeathKnight/Réanimation morbide"] = {
					["v_gcdspell"] = "111673",
					["v_keybind"] = "<keybind>",
					["v_pet_hp"] = "=0",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "46584",
					["v_spellname"] = "46584",
					["v_p_hp"] = "<35%",
					["b_p_hp"] = true,
					["v_durationstartedtime"] = 0,
					["b_pet_hp"] = true,
				},
				["defaultRotation/DeathKnight/Faucheur d'âme (Givre)"] = {
					["b_p_frostrunes"] = true,
					["v_gcdspell"] = "111673",
					["b_rangecheck"] = true,
					["v_actionicon"] = "130735",
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "130735",
					["b_t_hp"] = true,
					["v_keybind"] = "<keybind>",
					["v_p_frostrunes"] = ">=1",
					["v_t_hp"] = "<=35%",
				},
				["defaultRotation/DeathKnight/Parasite de peste (Mort)"] = {
					["v_t_needsdebuff"] = "_55095^4&_55078^4",
					["v_p_deathrunes"] = "<2",
					["v_gcdspell"] = "111673",
					["b_rangecheck"] = true,
					["b_p_deathrunes"] = true,
					["v_keybind"] = "<keybind>",
					["b_checkothercd"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "123693",
					["b_t_needsdebuff"] = true,
					["v_checkothercdvalue"] = "<1",
					["v_actionicon"] = "123693",
					["v_checkothercdname"] = "77575",
				},
				["defaultRotation/DeathKnight/Voile mortel (Changeliche)"] = {
					["b_p_havebuff"] = true,
					["v_togglename"] = "Toggle 1",
					["v_p_unitpower"] = ">=40",
					["v_gcdspell"] = "111673",
					["b_p_unitpower"] = true,
					["v_actionicon"] = "47541",
					["v_p_hp"] = "<100%",
					["v_p_unitpowertype"] = "6",
					["v_spellname"] = "47541",
					["v_durationstartedtime"] = 0,
					["b_p_hp"] = true,
					["v_p_havebuff"] = "_49039",
					["v_keybind"] = "<keybind>",
				},
				["defaultRotation/DeathKnight/Drain sanglant (Sang)"] = {
					["b_p_bloodrunes"] = true,
					["v_gcdspell"] = "0",
					["v_p_havebuff"] = "_114851#5",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "45529",
					["v_spellname"] = "45529",
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
					["v_p_bloodrunes"] = "=0",
					["b_p_havebuff"] = true,
				},
				["defaultRotation/DeathKnight/Pillier de givre"] = {
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "51271",
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "0",
					["v_actionicon"] = "51271",
				},
			},
			["SortedActions"] = {
				"defaultRotation/DeathKnight/Voile mortel (Changeliche)", -- [1]
				"defaultRotation/DeathKnight/Présence de givre", -- [2]
				"defaultRotation/DeathKnight/Cor de l'hiver", -- [3]
				"defaultRotation/DeathKnight/Réanimation morbide", -- [4]
				"defaultRotation/DeathKnight/Pacte mortel", -- [5]
				"defaultRotation/DeathKnight/Renforcer l'arme runique", -- [6]
				"defaultRotation/DeathKnight/Changeliche", -- [7]
				"defaultRotation/DeathKnight/Conversion", -- [8]
				"defaultRotation/DeathKnight/Drain sanglant (Sang)", -- [9]
				"defaultRotation/DeathKnight/Drain sanglant (Givre)", -- [10]
				"defaultRotation/DeathKnight/Drain sanglant (Impie)", -- [11]
				"defaultRotation/DeathKnight/Pillier de givre", -- [12]
				"defaultRotation/DeathKnight/Faucheur d'âme (Givre)", -- [13]
				"defaultRotation/DeathKnight/Faucheur d'âme (Mort)", -- [14]
				"defaultRotation/DeathKnight/Anéantissement (Machine)", -- [15]
				"defaultRotation/DeathKnight/Anéantissement (Machine + Mort)", -- [16]
				"defaultRotation/DeathKnight/Chancre impie", -- [17]
				"defaultRotation/DeathKnight/Poussée de fièvre", -- [18]
				"defaultRotation/DeathKnight/Poussée de fièvre (Glyphe)", -- [19]
				"defaultRotation/DeathKnight/Parasite de peste (Givre)", -- [20]
				"defaultRotation/DeathKnight/Parasite de peste (Impie)", -- [21]
				"defaultRotation/DeathKnight/Parasite de peste (Mort)", -- [22]
				"defaultRotation/DeathKnight/Rafale hurlante (Fièvre)", -- [23]
				"defaultRotation/DeathKnight/Frappe de peste", -- [24]
				"defaultRotation/DeathKnight/Frappe de givre (Puissance)", -- [25]
				"defaultRotation/DeathKnight/Rafale hurlante (Frimas)", -- [26]
				"defaultRotation/DeathKnight/Siphon mortel", -- [27]
				"defaultRotation/DeathKnight/Anéantissement", -- [28]
				"defaultRotation/DeathKnight/Frappe de givre", -- [29]
				"defaultRotation/DeathKnight/Cor de l'hiver (Puissance)", -- [30]
			},
			["keybind"] = "<keybind>",
		},
		["defaultRotation/DeathKnight/Impie 5.0.4"] = {
			["ActionList"] = {
				["defaultRotation/DeathKnight/Chancre impie"] = {
					["v_t_needsdebuff"] = "_55095&_55078",
					["b_t_dr"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "115989",
					["b_t_needsdebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "111673",
					["v_actionicon"] = "115989",
				},
				["defaultRotation/DeathKnight/Frappe du fléau (Mort)"] = {
					["v_p_deathrunes"] = ">=1",
					["b_p_deathrunes"] = true,
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "55090",
					["v_spellname"] = "55090",
					["v_gcdspell"] = "111673",
					["v_keybind"] = "<keybind>",
					["v_durationstartedtime"] = 0,
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Invocation d'une gargouille"] = {
					["b_p_havebuff"] = true,
					["v_actionicon"] = "49206",
					["v_gcdspell"] = "111673",
					["v_p_unitpower"] = ">60",
					["b_p_unitpower"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "49206",
					["v_p_unitpowertype"] = "6",
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "49016",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Parasite de peste (Impie)"] = {
					["v_t_needsdebuff"] = "_55095^4&_55078^4",
					["v_togglename"] = "Toggle 1",
					["b_p_unholyrunes"] = true,
					["b_rangecheck"] = true,
					["v_gcdspell"] = "111673",
					["v_keybind"] = "<keybind>",
					["b_checkothercd"] = true,
					["v_p_unholyrunes"] = "=0",
					["v_actionicon"] = "123693",
					["v_spellname"] = "123693",
					["b_t_needsdebuff"] = true,
					["v_checkothercdvalue"] = "<1",
					["v_durationstartedtime"] = 0,
					["v_checkothercdname"] = "77575",
				},
				["defaultRotation/DeathKnight/Cor de l'hiver"] = {
					["v_p_needbuff"] = "57330|19506|6673",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "57330",
					["v_spellname"] = "57330",
					["b_p_needbuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "111673",
					["v_durationstartedtime"] = 0,
				},
				["defaultRotation/DeathKnight/Changeliche"] = {
					["v_actionicon"] = "49039",
					["v_p_hp"] = "<50%",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "49039",
					["v_togglename"] = "Toggle 1",
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "0",
					["b_p_hp"] = true,
				},
				["defaultRotation/DeathKnight/Mort et décomposition (Impie)"] = {
					["v_togglename"] = "Toggle 1",
					["v_p_unholyrunes"] = ">=1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "43265",
					["b_p_unholyrunes"] = true,
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "111673",
					["v_actionicon"] = "43265",
				},
				["defaultRotation/DeathKnight/Cor de l'hiver (Puissance)"] = {
					["v_gcdspell"] = "111673",
					["b_p_unitpower"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "57330",
					["v_p_unitpowertype"] = "6",
					["v_keybind"] = "<keybind>",
					["v_p_unitpower"] = "<90",
					["v_actionicon"] = "57330",
				},
				["defaultRotation/DeathKnight/Présence impie"] = {
					["v_p_notstance"] = "3",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "48265",
					["v_spellname"] = "48265",
					["b_p_notstance"] = true,
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "111673",
					["v_durationstartedtime"] = 0,
				},
				["defaultRotation/DeathKnight/Frappe de peste"] = {
					["v_t_needsdebuff"] = "_55078",
					["v_checkothercdname"] = "77575",
					["b_p_unholyrunes"] = true,
					["b_t_hasdebuff"] = true,
					["b_rangecheck"] = true,
					["v_togglename"] = "Toggle 1",
					["v_gcdspell"] = "111673",
					["v_actionicon"] = "45462",
					["b_checkothercd"] = true,
					["v_p_unholyrunes"] = ">=1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "45462",
					["b_t_needsdebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_checkothercdvalue"] = ">5",
					["v_t_hasdebuff"] = "_55095",
				},
				["defaultRotation/DeathKnight/Toucher de glace"] = {
					["v_t_needsdebuff"] = "_55095",
					["b_p_frostrunes"] = true,
					["v_keybind"] = "<keybind>",
					["b_p_unholyrunes"] = true,
					["b_rangecheck"] = true,
					["v_togglename"] = "Toggle 1",
					["v_gcdspell"] = "111673",
					["v_p_frostrunes"] = ">=1",
					["b_checkothercd"] = true,
					["v_p_unholyrunes"] = ">=1",
					["v_actionicon"] = "45477",
					["v_spellname"] = "45477",
					["b_t_needsdebuff"] = true,
					["v_checkothercdvalue"] = ">5",
					["v_durationstartedtime"] = 0,
					["v_checkothercdname"] = "77575",
				},
				["defaultRotation/DeathKnight/Drain sanglant (Sang)"] = {
					["b_p_bloodrunes"] = true,
					["v_gcdspell"] = "0",
					["v_p_havebuff"] = "_114851#5",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "45529",
					["v_spellname"] = "45529",
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
					["v_p_bloodrunes"] = "=0",
					["b_p_havebuff"] = true,
				},
				["defaultRotation/DeathKnight/Conversion"] = {
					["v_p_needbuff"] = "_119975",
					["b_p_needbuff"] = true,
					["v_p_hp"] = "<70%",
					["v_actionicon"] = "119975",
					["v_spellname"] = "119975",
					["v_togglename"] = "Toggle 1",
					["b_p_hp"] = true,
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
				},
				["defaultRotation/DeathKnight/Siphon mortel"] = {
					["v_p_deathrunes"] = ">=1",
					["b_p_deathrunes"] = true,
					["v_gcdspell"] = "111673",
					["v_keybind"] = "<keybind>",
					["v_p_hp"] = "<70%",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "108196",
					["v_togglename"] = "Toggle 1",
					["b_p_hp"] = true,
					["v_actionicon"] = "108196",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Voile mortel (Puissance)"] = {
					["v_gcdspell"] = "111673",
					["v_actionicon"] = "47541",
					["b_p_unitpower"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "47541",
					["v_p_unitpowertype"] = "6",
					["v_keybind"] = "<keybind>",
					["v_p_unitpower"] = ">=90",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Renforcer l'arme runique"] = {
					["b_p_frostrunes"] = true,
					["v_p_deathrunes"] = "=0",
					["v_gcdspell"] = "0",
					["b_p_unholyrunes"] = true,
					["b_p_deathrunes"] = true,
					["v_togglename"] = "Toggle 1",
					["b_p_bloodrunes"] = true,
					["v_p_unholyrunes"] = "=0",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "47568",
					["v_p_frostrunes"] = "=0",
					["v_keybind"] = "<keybind>",
					["v_p_bloodrunes"] = "=0",
					["v_actionicon"] = "47568",
				},
				["defaultRotation/DeathKnight/Mort et décomposition (Mort)"] = {
					["v_gcdspell"] = "111673",
					["v_togglename"] = "Toggle 1",
					["v_p_deathrunes"] = ">=1",
					["v_spellname"] = "43265",
					["v_actionicon"] = "43265",
					["v_keybind"] = "<keybind>",
					["b_p_deathrunes"] = true,
					["v_durationstartedtime"] = 0,
				},
				["defaultRotation/DeathKnight/Poussée de fièvre"] = {
					["v_t_needsdebuff"] = "_55095&_55078",
					["v_gcdspell"] = "111673",
					["v_keybind"] = "<keybind>",
					["v_togglename"] = "Toggle 1",
					["v_p_knownotspell"] = "59332",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "77575",
					["b_t_needsdebuff"] = true,
					["b_p_knownotspell"] = true,
					["v_actionicon"] = "77575",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Frénésie impie"] = {
					["v_p_needbuff"] = "32182|2825|90355|80353|49016",
					["b_p_needbuff"] = true,
					["v_gcdspell"] = "0",
					["v_actionicon"] = "49016",
					["v_p_unitpowertype"] = "6",
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "49016",
					["b_t_boss"] = true,
					["v_keybind"] = "<keybind>",
					["v_p_unitpower"] = ">60",
					["b_p_unitpower"] = true,
				},
				["defaultRotation/DeathKnight/Sombre transformation (Mort)"] = {
					["v_pet_hasbuff"] = "91342#5",
					["v_p_deathrunes"] = ">=1",
					["b_pet_hasbuff"] = true,
					["b_p_deathrunes"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "63560",
					["v_gcdspell"] = "111673",
					["v_keybind"] = "<keybind>",
					["v_actionicon"] = "63560",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Voile mortel (Changeliche)"] = {
					["b_p_havebuff"] = true,
					["v_togglename"] = "Toggle 1",
					["v_p_unitpower"] = ">=32",
					["v_gcdspell"] = "111673",
					["b_p_unitpower"] = true,
					["v_actionicon"] = "47541",
					["v_p_hp"] = "<100%",
					["v_p_unitpowertype"] = "6",
					["v_spellname"] = "47541",
					["v_durationstartedtime"] = 0,
					["b_p_hp"] = true,
					["v_p_havebuff"] = "_49039",
					["v_keybind"] = "<keybind>",
				},
				["defaultRotation/DeathKnight/Drain sanglant (Impie)"] = {
					["v_gcdspell"] = "0",
					["b_p_unholyrunes"] = true,
					["v_togglename"] = "Toggle 1",
					["v_p_unholyrunes"] = "=0",
					["v_actionicon"] = "45529",
					["v_spellname"] = "45529",
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "_114851#5",
					["b_p_havebuff"] = true,
				},
				["defaultRotation/DeathKnight/Sombre transformation"] = {
					["v_pet_hasbuff"] = "91342#5",
					["b_pet_hasbuff"] = true,
					["v_gcdspell"] = "111673",
					["b_p_unholyrunes"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "63560",
					["v_actionicon"] = "63560",
					["v_keybind"] = "<keybind>",
					["v_p_unholyrunes"] = ">=1",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Frappe purulente"] = {
					["b_p_frostrunes"] = true,
					["b_p_bloodrunes"] = true,
					["v_gcdspell"] = "111673",
					["v_p_frostrunes"] = ">=1",
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "85948",
					["v_spellname"] = "85948",
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
					["v_p_bloodrunes"] = ">=1",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Pacte mortel"] = {
					["v_actionicon"] = "48743",
					["v_p_hp"] = "<35%",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "48743",
					["v_togglename"] = "Toggle 1",
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "0",
					["b_p_hp"] = true,
				},
				["defaultRotation/DeathKnight/Drain sanglant (Givre)"] = {
					["b_p_frostrunes"] = true,
					["v_gcdspell"] = "0",
					["b_p_havebuff"] = true,
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "45529",
					["v_spellname"] = "45529",
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "_114851#5",
					["v_p_frostrunes"] = "=0",
				},
				["defaultRotation/DeathKnight/Faucheur d'âme (Mort)"] = {
					["v_p_deathrunes"] = ">=1",
					["b_p_deathrunes"] = true,
					["v_gcdspell"] = "111673",
					["b_rangecheck"] = true,
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "130736",
					["b_t_hp"] = true,
					["v_spellname"] = "130736",
					["v_keybind"] = "<keybind>",
					["v_durationstartedtime"] = 0,
					["v_t_hp"] = "<=35%",
				},
				["defaultRotation/DeathKnight/Parasite de peste (Sang + Givre)"] = {
					["v_t_needsdebuff"] = "_55095^4&_55078^4",
					["b_p_frostrunes"] = true,
					["b_p_bloodrunes"] = true,
					["v_gcdspell"] = "111673",
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "123693",
					["b_t_needsdebuff"] = true,
					["v_checkothercdvalue"] = "<1",
					["v_p_bloodrunes"] = "=0",
					["v_checkothercdname"] = "77575",
					["b_p_deathrunes"] = true,
					["b_checkothercd"] = true,
					["v_actionicon"] = "123693",
					["b_rangecheck"] = true,
					["v_keybind"] = "<keybind>",
					["v_p_deathrunes"] = "<4",
					["v_p_frostrunes"] = "=0",
				},
				["defaultRotation/DeathKnight/Réanimation morbide"] = {
					["v_pet_hp"] = "=0",
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "46584",
					["v_actionicon"] = "46584",
					["v_keybind"] = "<keybind>",
					["v_gcdspell"] = "111673",
					["b_pet_hp"] = true,
				},
				["defaultRotation/DeathKnight/Faucheur d'âme (Impie)"] = {
					["b_p_unholyrunes"] = true,
					["v_gcdspell"] = "111673",
					["b_rangecheck"] = true,
					["v_togglename"] = "Toggle 1",
					["v_p_unholyrunes"] = ">=1",
					["v_actionicon"] = "130736",
					["v_spellname"] = "130736",
					["v_durationstartedtime"] = 0,
					["v_keybind"] = "<keybind>",
					["b_t_hp"] = true,
					["v_t_hp"] = "<=35%",
				},
				["defaultRotation/DeathKnight/Frappe du fléau (Impie)"] = {
					["v_gcdspell"] = "111673",
					["b_p_unholyrunes"] = true,
					["v_togglename"] = "Toggle 1",
					["v_actionicon"] = "55090",
					["v_spellname"] = "55090",
					["v_p_unholyrunes"] = ">=1",
					["v_keybind"] = "<keybind>",
					["v_durationstartedtime"] = 0,
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Poussée de fièvre (Glyphe)"] = {
					["v_t_needsdebuff"] = "_55095&_55078",
					["v_p_unitpowertype"] = "6",
					["v_p_knowspell"] = "59332",
					["b_p_unitpower"] = true,
					["v_gcdspell"] = "111673",
					["v_actionicon"] = "77575",
					["b_p_knowspell"] = true,
					["v_togglename"] = "Toggle 1",
					["v_durationstartedtime"] = 0,
					["v_spellname"] = "77575",
					["b_t_needsdebuff"] = true,
					["v_keybind"] = "<keybind>",
					["v_p_unitpower"] = ">=40",
					["b_rangecheck"] = true,
				},
				["defaultRotation/DeathKnight/Voile mortel"] = {
					["v_gcdspell"] = "111673",
					["v_durationstartedtime"] = 0,
					["v_togglename"] = "Toggle 1",
					["b_p_havebuff"] = true,
					["v_spellname"] = "47541",
					["v_actionicon"] = "47541",
					["v_keybind"] = "<keybind>",
					["v_p_havebuff"] = "_81340",
					["b_rangecheck"] = true,
				},
			},
			["SortedActions"] = {
				"defaultRotation/DeathKnight/Voile mortel (Changeliche)", -- [1]
				"defaultRotation/DeathKnight/Présence impie", -- [2]
				"defaultRotation/DeathKnight/Cor de l'hiver", -- [3]
				"defaultRotation/DeathKnight/Réanimation morbide", -- [4]
				"defaultRotation/DeathKnight/Pacte mortel", -- [5]
				"defaultRotation/DeathKnight/Renforcer l'arme runique", -- [6]
				"defaultRotation/DeathKnight/Changeliche", -- [7]
				"defaultRotation/DeathKnight/Conversion", -- [8]
				"defaultRotation/DeathKnight/Frénésie impie", -- [9]
				"defaultRotation/DeathKnight/Invocation d'une gargouille", -- [10]
				"defaultRotation/DeathKnight/Drain sanglant (Sang)", -- [11]
				"defaultRotation/DeathKnight/Drain sanglant (Givre)", -- [12]
				"defaultRotation/DeathKnight/Drain sanglant (Impie)", -- [13]
				"defaultRotation/DeathKnight/Chancre impie", -- [14]
				"defaultRotation/DeathKnight/Poussée de fièvre", -- [15]
				"defaultRotation/DeathKnight/Poussée de fièvre (Glyphe)", -- [16]
				"defaultRotation/DeathKnight/Parasite de peste (Sang + Givre)", -- [17]
				"defaultRotation/DeathKnight/Parasite de peste (Impie)", -- [18]
				"defaultRotation/DeathKnight/Toucher de glace", -- [19]
				"defaultRotation/DeathKnight/Frappe de peste", -- [20]
				"defaultRotation/DeathKnight/Sombre transformation", -- [21]
				"defaultRotation/DeathKnight/Sombre transformation (Mort)", -- [22]
				"defaultRotation/DeathKnight/Faucheur d'âme (Impie)", -- [23]
				"defaultRotation/DeathKnight/Faucheur d'âme (Mort)", -- [24]
				"defaultRotation/DeathKnight/Voile mortel (Puissance)", -- [25]
				"defaultRotation/DeathKnight/Voile mortel", -- [26]
				"defaultRotation/DeathKnight/Mort et décomposition (Impie)", -- [27]
				"defaultRotation/DeathKnight/Mort et décomposition (Mort)", -- [28]
				"defaultRotation/DeathKnight/Siphon mortel", -- [29]
				"defaultRotation/DeathKnight/Frappe du fléau (Impie)", -- [30]
				"defaultRotation/DeathKnight/Frappe du fléau (Mort)", -- [31]
				"defaultRotation/DeathKnight/Frappe purulente", -- [32]
				"defaultRotation/DeathKnight/Cor de l'hiver (Puissance)", -- [33]
			},
			["keybind"] = "<keybind>",
		},
	}

	-- Restore the true state of the saved data.
	--	return RotationBuilder:restoreTable({}, rotation);
	return rotation;
end

local deathKnightRotationsGeneratorData = {
	["version"] = 1, 
	["generator"] = deathKnightRotationsGenerator
};

RotationBuilder:addDefaultRotationsGenerator("DEATHKNIGHT", deathKnightRotationsGeneratorData);