local L = LibStub("AceLocale-3.0"):NewLocale("RotationBuilder", "enUS", true, true)
if not L then return end

--@do-not-package@
-- Default localization for development stage.
L["rotation/rogue/adrenaline_rush"] = "Adrenaline Rush"
L["rotation/rogue/ambush"] = "Ambush"
L["rotation/rogue/assassination"] = "Assassination 7.0.3"
L["rotation/rogue/backstab"] = "Backstab"
L["rotation/rogue/between_the_eyes"] = "Between the Eyes"
L["rotation/rogue/death_from_above"] = "Death from Above"
L["rotation/rogue/envenom"] = "Envenom"
L["rotation/rogue/eviscerate"] = "Eviscerate"
L["rotation/rogue/garrote"] = "Garrot"
L["rotation/rogue/killing_spree"] = "Killing Spree"
L["rotation/rogue/deadly_poison"] = "Lethal Poison"
L["rotation/rogue/marked_for_death"] = "Marked for Death"
L["rotation/rogue/mutilate"] = "Mutilate"
L["rotation/rogue/nightblade"] = "Nightblade"
L["rotation/rogue/outlaw"] = "Outlaw 7.0.3"
L["rotation/rogue/pistol_shot"] = "Pistol Shot"
L["rotation/rogue/roll_the_bones"] = "Roll the Bones"
L["rotation/rogue/run_through"] = "Run Through"
L["rotation/rogue/rupture"] = "Rupture"
L["rotation/rogue/saber_slash"] = "Saber Slash"
L["rotation/rogue/shadow_blades"] = "Shadow Blades"
L["rotation/rogue/shadow_dance"] = "Shadow Dance"
L["rotation/rogue/shadowstrikes"] = "Shadowstrikes"
L["rotation/rogue/slice_and_dice"] = "Slice and Dice"
L["rotation/rogue/subtlety"] = "Subtlety 7.0.3"
L["rotation/rogue/symbols_of_death"] = "Symbols of Death"
L["rotation/rogue/hemorrhage"] = "Hemorrhage"
L["rotation/rogue/marked_for_death&anticipation"] = "Marked for death + Anticipation"
L["rotation/rogue/agonizing_poison"] = "Agonizing poison"
L["rotation/rogue/death_from_above&stratagem"] = "Death from above + Stratagem"
L["rotation/rogue/envenom&stratagem"] = "Envenom + Stratagem"
L["rotation/rogue/rupture&stratagem"] = "Rupture + Stratagem"
L["rotation/rogue/exsanguinate"] = "Exsanguinate"
L["rotation/rogue/vendetta"] = "Vendetta"
L["rotation/rogue/eviscerate&stratagem"] = "Eviscerate + Stratagem"
L["rotation/rogue/enveloping_shadows"] = "Enveloping shadows"
L["rotation/rogue/nightblade&stratagem"] = "Nightblade + Stratagem"
L["rotation/rogue/between_the_eyes&stratagem"] = "Between the eyes + Stratagem"
L["rotation/rogue/pistol_shot&quick_draw"] = "Pistol shot + Guick draw"
L["rotation/rogue/pistol_shot&quick_draw&stratagem"] = "Pistol shot + Guick draw + Stratagem"
L["rotation/rogue/pistol_shot&quick_draw&anticipation"] = "Pistol shot + Guick draw + Anticipation"
L["rotation/rogue/ghostly_strike"] = "Ghostly strike"
L["rotation/rogue/run_through&stratagem"] = "Run through + Stratagem"
L["rotation/rogue/slice_and_dice&stratagem"] = "Slice and dice + Stratagem"
L["rotation/rogue/cannonball_barage"] = "Cannonball barage"
L["rotation/rogue/roll_the_bones&stratagem"] = "Roll the bones + Stratagem"
--@end-do-not-package@

--@localization(locale="enUS", format="lua_additive_table", namespace="RotationBuilder_Rogue")@
