local L = LibStub("AceLocale-3.0"):NewLocale("RotationBuilder", "enUS", true, true)
if not L then return end

--@do-not-package@
-- Default localization for development stage.
L["rotation/rogue/adrenaline_rush"] = "Adrenaline Rush"
L["rotation/rogue/ambush"] = "Ambush"
L["rotation/rogue/assassination"] = "Assassination 8.0.1"
L["rotation/rogue/assassination_multi"] = "Assassination Multi 8.0.1"
L["rotation/rogue/backstab"] = "Backstab"
L["rotation/rogue/between_the_eyes"] = "Between the Eyes"
L["rotation/rogue/blade_flurry"] = "Blade Flurry"
L["rotation/rogue/blade_rush"] = "Blade Rush"
L["rotation/rogue/blindside"] = "Blindside"
L["rotation/rogue/blindside_blindside"] = "Blindside (Blindside)"
L["rotation/rogue/cold_blood"] = "Cold Blood"
L["rotation/rogue/crimson_tempest"] = "Crimson Tempest"
L["rotation/rogue/crimson_vial"] = "Crimson Vial"
L["rotation/rogue/crimson_vial_iron_stomach"] = "Crimson Vial (Iron Stomach)"
L["rotation/rogue/deadly_poison"] = "Deadly Poison"
L["rotation/rogue/deadly_poison_leeching_poison"] = "Deadly Poison (Leeching Poison)"
L["rotation/rogue/death_from_above"] = "Death from Above"
L["rotation/rogue/envenom"] = "Envenom"
L["rotation/rogue/eviscerate"] = "Eviscerate"
L["rotation/rogue/exsanguinate"] = "Exsanguinate"
L["rotation/rogue/fan_of_knives"] = "Fan of Knives"
L["rotation/rogue/garrote"] = "Garrote"
L["rotation/rogue/garrote_exsanguinate"] = "Garrote (Exsanguinate)"
L["rotation/rogue/garrote_stealth"] = "Garrote (Stealth)"
L["rotation/rogue/ghostly_strike"] = "Ghostly strike"
L["rotation/rogue/kick"] = "Kick"
L["rotation/rogue/killing_spree"] = "Killing Spree"
L["rotation/rogue/marked_for_death"] = "Marked for Death"
L["rotation/rogue/mutilate"] = "Mutilate"
L["rotation/rogue/mutilate_stealth"] = "Mutilate (Stealth)"
L["rotation/rogue/neurotoxin"] = "Neurotoxin"
L["rotation/rogue/nightblade"] = "Nightblade"
L["rotation/rogue/outlaw"] = "Outlaw 8.0.1"
L["rotation/rogue/outlaw_multi"] = "Outlaw Multi 8.0.1"
L["rotation/rogue/pistol_shot"] = "Pistol Shot"
L["rotation/rogue/pistol_shot_quick_draw"] = "Pistol Shot (Quick Draw)"
L["rotation/rogue/roll_the_bones"] = "Roll the Bones"
L["rotation/rogue/run_through"] = "Dispatch"
L["rotation/rogue/rupture"] = "Rupture"
L["rotation/rogue/rupture_stealth"] = "Rupture (Stealth)"
L["rotation/rogue/saber_slash"] = "Sinister Strike"
L["rotation/rogue/secret_technique"] = "Secret Technique"
L["rotation/rogue/shadow_blades"] = "Shadow Blades"
L["rotation/rogue/shadow_dance"] = "Shadow Dance"
L["rotation/rogue/shadow_dance_2_charges"] = "Shadow Dance (2 Charges)"
L["rotation/rogue/shadow_dance_enveloping_shadows"] = "Shadow Dance (Enveloping Shadows)"
L["rotation/rogue/shadow_dance_enveloping_shadows_3_charges"] = "Shadow Dance (Enveloping Shadows (3 Charges))"
L["rotation/rogue/shadow_dance_master_of_shadows"] = "Shadow Dance (Master of Shadows)"
L["rotation/rogue/shadow_dance_master_of_shadows_ 2_charges"] = "Shadow Dance (Master of Shadows (2 Charges))"
L["rotation/rogue/shadow_dance_master_of_shadows_enveloping_shadows"] = "Shadow Dance (Master of Shadows (Enveloping Shadows))"
L["rotation/rogue/shadow_dance_master_of_shadows_enveloping_shadows_3_charges"] = "Shadow Dance (Master of Shadows (Enveloping Shadows (3 Charges)))"
L["rotation/rogue/shadow_dance_symbols_of_death"] = "Shadow Dance (Symbols of Death)"
L["rotation/rogue/shadowstrikes"] = "Shadowstrikes"
L["rotation/rogue/shiv"] = "Shiv"
L["rotation/rogue/shuriken_storm"] = "Shuriken Storm"
L["rotation/rogue/shuriken_storm_stealth"] = "Shuriken Storm (Stealth)"
L["rotation/rogue/shuriken_tornado"] = "Shuriken Tornado"
L["rotation/rogue/slice_and_dice"] = "Slice and Dice"
L["rotation/rogue/subtlety"] = "Subtlety 8.0.1"
L["rotation/rogue/subtlety_multi"] = "Subtlety Multi 8.0.1"
L["rotation/rogue/symbols_of_death"] = "Symbols of Death"
L["rotation/rogue/toxic_blade"] = "Toxic Blade"
L["rotation/rogue/vendetta"] = "Vendetta"
--@end-do-not-package@

--@localization(locale="enUS", format="lua_additive_table", namespace="RotationBuilder_Rogue")@
