local L = LibStub("AceLocale-3.0"):NewLocale("RotationBuilder", "frFR")
if not L then return end

--@do-not-package@
-- Default localization for development stage.
L["rotation/rogue/adrenaline_rush"] = "Poussée d'adrénaline"
L["rotation/rogue/ambush"] = "Embuscade"
L["rotation/rogue/assassination"] = "Assassinat 8.0.1"
L["rotation/rogue/assassination_multi"] = "Assassinat Multi 8.0.1"
L["rotation/rogue/backstab"] = "Attaque sournoise"
L["rotation/rogue/between_the_eyes"] = "Entre les deux yeux"
L["rotation/rogue/blade_flurry"] = "Déluge de lames"
L["rotation/rogue/blade_rush"] = "Volée de lames"
L["rotation/rogue/blindside"] = "Angle mort"
L["rotation/rogue/blindside_blindside"] = "Angle mort (Angle mort)"
L["rotation/rogue/cold_blood"] = "Sang froid (JcJ)"
L["rotation/rogue/crimson_tempest"] = "Tempête cramoisie"
L["rotation/rogue/crimson_vial"] = "Fiole cramoisie"
L["rotation/rogue/crimson_vial_iron_stomach"] = "Fiole cramoisie (Estomac de fer)"
L["rotation/rogue/deadly_poison"] = "Poison mortel"
L["rotation/rogue/deadly_poison_leeching_poison"] = "Poison mortel (Poison sangsue)"
L["rotation/rogue/death_from_above"] = "La mort venue d'en haut (JcJ)"
L["rotation/rogue/envenom"] = "Envenimer"
L["rotation/rogue/eviscerate"] = "Eviscération"
L["rotation/rogue/exsanguinate"] = "Exsangue"
L["rotation/rogue/fan_of_knives"] = "Eventail de couteaux"
L["rotation/rogue/garrote"] = "Garrot"
L["rotation/rogue/garrote_exsanguinate"] = "Garrot (Exsangue)"
L["rotation/rogue/garrote_stealth"] = "Garrot (Camouflage)"
L["rotation/rogue/ghostly_strike"] = "Frappe fantomatique"
L["rotation/rogue/kick"] = "Coup de pied"
L["rotation/rogue/killing_spree"] = "Série meurtrière"
L["rotation/rogue/marked_for_death"] = "Désigné pour mourir"
L["rotation/rogue/mutilate"] = "Estropier"
L["rotation/rogue/mutilate_stealth"] = "Estropier (Camouflage)"
L["rotation/rogue/neurotoxin"] = "Neurotoxine (JcJ)"
L["rotation/rogue/nightblade"] = "Lamenuit"
L["rotation/rogue/outlaw"] = "Hors-la-loi 8.0.1"
L["rotation/rogue/outlaw_multi"] = "Hors-la-loi Multi 8.0.1"
L["rotation/rogue/pistol_shot"] = "Coup de pistolet"
L["rotation/rogue/pistol_shot_quick_draw"] = "Coup de pistolet (Tireur rapide)"
L["rotation/rogue/roll_the_bones"] = "Jet d'osselets"
L["rotation/rogue/run_through"] = "Couperet"
L["rotation/rogue/rupture"] = "Rupture"
L["rotation/rogue/rupture_stealth"] = "Rupture (Camouflage)"
L["rotation/rogue/saber_slash"] = "Attaque pernicieuse"
L["rotation/rogue/secret_technique"] = "Technique secrète"
L["rotation/rogue/shadow_blades"] = "Lames de l'ombre"
L["rotation/rogue/shadow_dance"] = "Danse de l'ombre"
L["rotation/rogue/shadow_dance_2_charges"] = "Danse de l'ombre (2 Charges)"
L["rotation/rogue/shadow_dance_enveloping_shadows"] = "Danse de l'ombre (Ombres enveloppantes)"
L["rotation/rogue/shadow_dance_enveloping_shadows_3_charges"] = "Danse de l'ombre (Ombres enveloppantes (3 Charges))"
L["rotation/rogue/shadow_dance_master_of_shadows"] = "Danse de l'ombre (Maître des Ombres)"
L["rotation/rogue/shadow_dance_master_of_shadows_2_charges"] = "Danse de l'ombre (Maître des Ombres (2 Charges))"
L["rotation/rogue/shadow_dance_master_of_shadows_enveloping_shadows"] = "Danse de l'ombre (Maître des Ombres (Ombres enveloppantes))"
L["rotation/rogue/shadow_dance_master_of_shadows_enveloping_shadows_3_charges"] = "Danse de l'ombre (Maître des Ombres (Ombres enveloppantes (3 Charges)))"
L["rotation/rogue/shadow_dance_symbols_of_death"] = "Danse de l'ombre (Symboles de mort)"
L["rotation/rogue/shadowstrikes"] = "Frappe-ténèbres"
L["rotation/rogue/shiv"] = "Kriss (JcJ)"
L["rotation/rogue/shuriken_storm"] = "Tempête de shurikens"
L["rotation/rogue/shuriken_storm_stealth"] = "Tempête de shurikens (Camouflage)"
L["rotation/rogue/shuriken_tornado"] = "Tornade de shurikens"
L["rotation/rogue/slice_and_dice"] = "Débiter"
L["rotation/rogue/subtlety"] = "Finesse 8.0.1"
L["rotation/rogue/subtlety_multi"] = "Finesse Multi 8.0.1"
L["rotation/rogue/symbols_of_death"] = "Symboles de mort"
L["rotation/rogue/toxic_blade"] = "Lame toxique"
L["rotation/rogue/vendetta"] = "Vendetta"
--@end-do-not-package@

--@localization(locale="frFR", format="lua_additive_table", namespace="RotationBuilder_Rogue")@
