local L = LibStub("AceLocale-3.0"):NewLocale("RotationBuilder", "frFR")
if not L then return end

--@do-not-package@
-- Default localization for development stage.
L["rotation/rogue/ambush"] = "Embuscade"
L["rotation/rogue/assassination"] = "Assassinat 7.0.3"
L["rotation/rogue/backstab"] = "Attaque sournoise"
L["rotation/rogue/between_the_eyes"] = "Entre les deux yeux"
L["rotation/rogue/death_from_above"] = "La mort venu d’en haut"
L["rotation/rogue/envenom"] = "Envenimer"
L["rotation/rogue/eviscerate"] = "Eviscération"
L["rotation/rogue/garrote"] = "Garrot"
L["rotation/rogue/killing_spree"] = "Série meurtrière"
L["rotation/rogue/deadly_poison"] = "Poison mortel"
L["rotation/rogue/marked_for_death"] = "Désigné pour mourir"
L["rotation/rogue/mutilate"] = "Estropier"
L["rotation/rogue/nightblade"] = "Lamenuit"
L["rotation/rogue/outlaw"] = "Hors-la-loi 7.0.3"
L["rotation/rogue/pistol_shot"] = "Coup de pistolet"
L["rotation/rogue/roll_the_bones"] = "Jet d’osselets"
L["rotation/rogue/run_through"] = "Percée"
L["rotation/rogue/rupture"] = "Rupture"
L["rotation/rogue/saber_slash"] = "Coup de sabre"
L["rotation/rogue/shadow_blades"] = "Lames de l’ombre"
L["rotation/rogue/shadow_dance"] = "Danse de l'ombre"
L["rotation/rogue/shadowstrikes"] = "Frappe-ténèbres"
L["rotation/rogue/slice_and_dice"] = "Débiter"
L["rotation/rogue/subtlety"] = "Finesse 7.0.3"
L["rotation/rogue/symbols_of_death"] = "Symboles de mort"
L["rotation/rogue/hemorrhage"] = "Hémorragie"
L["rotation/rogue/marked_for_death&anticipation"] = "Désigné pour mourrir + Anticipation"
L["rotation/rogue/agonizing_poison"] = "Poison déchirant"
L["rotation/rogue/death_from_above&stratagem"] = "La mort venu d’en haut + Stratagème"
L["rotation/rogue/envenom&stratagem"] = "Envenimer + Stratagème"
L["rotation/rogue/rupture&stratagem"] = "Rupture + Stratagème"
L["rotation/rogue/exsanguinate"] = "Exsangue"
L["rotation/rogue/vendetta"] = "Vendetta"
L["rotation/rogue/eviscerate&stratagem"] = "Eviscération + Stratagème"
L["rotation/rogue/enveloping_shadows"] = "Ombres enveloppantes"
L["rotation/rogue/nightblade&stratagem"] = "Lamenuit + Stratagème"
L["rotation/rogue/between_the_eyes&stratagem"] = "Entre les deux yeux + Stratagème"
L["rotation/rogue/pistol_shot&quick_draw"] = "Coup de pistolet + Tireur rapide"
L["rotation/rogue/pistol_shot&quick_draw&stratagem"] = "Coup de pistolet + Tireur rapide + Stratagème"
L["rotation/rogue/pistol_shot&quick_draw&anticipation"] = "Coup de pistolet + Tireur rapide + Anticipation"
L["rotation/rogue/ghostly_strike"] = "Frappe fantomatique"
L["rotation/rogue/run_through&stratagem"] = "Percée + Stratagème"
L["rotation/rogue/slice_and_dice&stratagem"] = "Débiter + Stratagème"
L["rotation/rogue/cannonball_barage"] = "Barrage de canons"
L["rotation/rogue/roll_the_bones&stratagem"] = "Jet d’osselets + Stratagème"
--@end-do-not-package@

--@localization(locale="frFR", format="lua_additive_table", namespace="RotationBuilder_Rogue")@
