local L = LibStub("AceLocale-3.0"):NewLocale("RotationBuilder", "frFR")
if not L then return end

--@do-not-package@
-- Default localization for development stage.
L["rotation/rogue/adrenaline_rush"] = "Poussée d’adrénaline"
L["rotation/rogue/agonizing_poison"] = "Poison déchirant"
L["rotation/rogue/ambush"] = "Embuscade"
L["rotation/rogue/assassination"] = "Assassinat 7.0.3"
L["rotation/rogue/backstab_anticipation"] = "Attaque sournoise (Anticipation)"
L["rotation/rogue/backstab_deeper_stratagem"] = "Attaque sournoise (Stratagème approfondi)"
L["rotation/rogue/backstab"] = "Attaque sournoise"
L["rotation/rogue/between_the_eyes_deeper_stratagem"] = "Entre les deux yeux (Stratagème approfondi)"
L["rotation/rogue/between_the_eyes"] = "Entre les deux yeux"
L["rotation/rogue/cannonball_barrage"] = "Barrage de canons"
L["rotation/rogue/crimson_vial_iron_stomach"] = "Fiole cramoisie (Estomac de fer)"
L["rotation/rogue/crimson_vial"] = "Fiole cramoisie"
L["rotation/rogue/deadly_poison"] = "Poison mortel"
L["rotation/rogue/death_from_above_deeper_stratagem"] = "La mort venue d'en haut (Stratagème approfondi)"
L["rotation/rogue/death_from_above"] = "La mort venue d’en haut"
L["rotation/rogue/enveloping_shadows_deeper_stratagem"] = "Ombres enveloppantes (Stratagème approfondi)"
L["rotation/rogue/enveloping_shadows"] = "Ombres enveloppantes"
L["rotation/rogue/envenom_deeper_stratagem"] = "Envenimer (Stratagème approfondi)"
L["rotation/rogue/envenom"] = "Envenimer"
L["rotation/rogue/eviscerate_deeper_stratagem"] = "Eviscération (Stratagème approfondi)"
L["rotation/rogue/eviscerate"] = "Eviscération"
L["rotation/rogue/exsanguinate"] = "Exsangue"
L["rotation/rogue/garrote_stealth"] = "Garrot (Camouflage)"
L["rotation/rogue/garrote"] = "Garrot"
L["rotation/rogue/ghostly_strike"] = "Frappe fantomatique"
L["rotation/rogue/hemorrhage_deeper_stratagem"] = "Hémorragie (Stratagème approfondi)"
L["rotation/rogue/hemorrhage_refresh"] = "Hémorragie (Rafraîchir)"
L["rotation/rogue/hemorrhage"] = "Hémorragie"
L["rotation/rogue/killing_spree"] = "Série meurtrière"
L["rotation/rogue/leeching_poison"] = "Poison sangsue"
L["rotation/rogue/marked_for_death_anticipation"] = "Désigné pour mourir (Anticipation)"
L["rotation/rogue/marked_for_death_deeper_stratagem"] = "Désigné pour mourir (Stratagème approfondi)"
L["rotation/rogue/marked_for_death"] = "Désigné pour mourir"
L["rotation/rogue/mutilate_deeper_stratagem"] = "Estropier (Stratagème approfondi)"
L["rotation/rogue/mutilate"] = "Estropier"
L["rotation/rogue/nightblade_deeper_stratagem"] = "Lamenuit (Stratagème approfondi)"
L["rotation/rogue/nightblade"] = "Lamenuit"
L["rotation/rogue/outlaw"] = "Hors-la-loi 7.0.3"
L["rotation/rogue/pistol_shot_anticipation"] = "Coup de pistolet (Anticipation)"
L["rotation/rogue/pistol_shot_deeper_stratagem"] = "Coup de pistolet (Stratagème approfondi)"
L["rotation/rogue/pistol_shot_quick_draw_anticipation"] = "Coup de pistolet (Tireur rapide (Anticipation))"
L["rotation/rogue/pistol_shot_quick_draw_deeper_stratagem"] = "Coup de pistolet (Tireur Rapide (Stratagème approfondi))"
L["rotation/rogue/pistol_shot_quick_draw"] = "Coup de pistolet (Tireur rapide)"
L["rotation/rogue/pistol_shot"] = "Coup de pistolet"
L["rotation/rogue/roll_the_bones_deeper_stratagem"] = "Jet d'osselets (Stratagème approfondi)"
L["rotation/rogue/roll_the_bones"] = "Jet d’osselets"
L["rotation/rogue/run_through_deeper_stratagem"] = "Percée (Stratagème approfondi)"
L["rotation/rogue/run_through"] = "Percée"
L["rotation/rogue/rupture_deeper_stratagem"] = "Rupture (Stratagème approfondi)"
L["rotation/rogue/rupture"] = "Rupture"
L["rotation/rogue/saber_slash"] = "Coup de sabre"
L["rotation/rogue/shadow_blades"] = "Lames de l’ombre"
L["rotation/rogue/shadow_dance"] = "Danse de l'ombre"
L["rotation/rogue/shadowstrikes"] = "Frappe-ténèbres"
L["rotation/rogue/subtlety"] = "Finesse 7.0.3"
L["rotation/rogue/symbols_of_death"] = "Symboles de mort"
L["rotation/rogue/vendetta"] = "Vendetta"
--@end-do-not-package@

--@localization(locale="frFR", format="lua_additive_table", namespace="RotationBuilder_Rogue")@
